// SDG color palette (UN official)
const SDG_COLORS = [
  '#E5243B','#DDA63A','#4C9F38','#C5192D','#FF3A21','#26BDE2','#FCC30B','#A21942',
  '#FD6925','#DD1367','#FD9D24','#BF8B2E','#3F7E44','#0A97D9','#56C02B','#00689D','#19486A',
];

// News DB: correct SDGs apply across languages; localized text per language.
const NEWS_DB = [
  {
    correct: [2,1,13,17],
    tags: { ko:['식량','기아','아프리카','FAO'], en:['food','hunger','Africa','FAO'], ja:['食料','飢餓','アフリカ','FAO'] },
    url: 'https://news.un.org/en/story/2024/07/1152236',
    i18n: {
      ko: {
        source:'UN뉴스', title:'전 세계 7억 3천만 명이 여전히 극심한 굶주림에 시달려',
        body:'유엔 식량농업기구(FAO)는 2024년 보고서에서 전 세계 약 7억 3천만 명이 만성적인 식량 부족 상태에 있다고 밝혔습니다. 특히 사하라 이남 아프리카와 남아시아에서 상황이 심각하며, 기후 변화와 분쟁이 주요 원인으로 꼽힙니다. 어린이 영양실조도 여전히 심각한 문제로 남아 있습니다.',
        hint:'음식이 부족한 사람들과 관련된 목표, 그리고 그 원인인 기후와 가난을 함께 생각해보세요.',
        fc:'훌륭해요! 기아(SDG 2)가 핵심이지만, 빈곤(SDG 1), 기후변화(SDG 13), 국제 협력(SDG 17)과도 깊이 연결돼요.',
        fp:'좋은 시작이에요! 기아(SDG 2)는 잘 찾았어요. 빈곤(SDG 1)과 기후변화(SDG 13)도 함께 생각해보세요.',
        fm:'기사에서 "굶주림"이라는 단어를 주목해보세요. 식량 문제와 기후·빈곤의 관계를 떠올려 봐요.',
        lc:'우리가 음식을 낭비하지 않고 급식을 남기지 않는 것도 SDG 2를 실천하는 거예요.',
        bonus:'오늘 급식에서 음식을 하나도 남기지 않아 보세요. 먹지 못하는 친구들을 생각하며 감사히 먹는 것도 세계시민 행동이에요.',
      },
      en: {
        source:'UN News', title:'730 million people still face severe hunger worldwide',
        body:'In its 2024 report, the UN Food and Agriculture Organization (FAO) said about 730 million people remain chronically food-insecure. The situation is most severe in sub-Saharan Africa and South Asia, with climate change and conflict driving the crisis. Child malnutrition remains a serious problem.',
        hint:'Think about the goal directly linked to people without enough food, plus the climate and poverty causes behind it.',
        fc:'Excellent! Zero Hunger (SDG 2) is the core, but Poverty (1), Climate Action (13) and Partnerships (17) are deeply connected too.',
        fp:'Good start! You spotted Hunger (SDG 2). Try also Poverty (1) and Climate Action (13).',
        fm:'Notice the word "hunger" in the article — then think about how climate and poverty cause it.',
        lc:'Not wasting food at school lunch is already a small act for SDG 2.',
        bonus:'Try to leave no food on your plate today. Eating with gratitude for those who cannot is itself a global-citizen action.',
      },
      ja: {
        source:'UNニュース', title:'世界で7億3千万人が依然として深刻な飢餓に',
        body:'国連食糧農業機関(FAO)は2024年の報告書で、世界で約7億3千万人が慢性的な食料不足の状態にあると発表しました。特にサハラ以南のアフリカと南アジアで状況が深刻で、気候変動と紛争が主な原因とされています。子どもの栄養失調も依然として深刻です。',
        hint:'食べ物が足りない人々に直結する目標と、その原因である気候・貧困を一緒に考えてみよう。',
        fc:'素晴らしい!飢餓(SDG 2)が中心だけど、貧困(1)、気候変動(13)、パートナーシップ(17)とも深くつながっているよ。',
        fp:'いいスタート!飢餓(SDG 2)はバッチリ。貧困(1)と気候変動(13)も一緒に考えてみよう。',
        fm:'記事の「飢餓」という言葉に注目。気候や貧困との関係も考えてみよう。',
        lc:'給食を残さず食べることも、SDG 2の実践のひとつだよ。',
        bonus:'今日の給食を残さず食べてみよう。食べられない人を想い、感謝して食べることも世界市民の行動だよ。',
      },
    },
  },
  {
    correct: [13,3,4,1],
    tags: { ko:['기후변화','어린이','폭염','홍수'], en:['climate','children','heatwave','flood'], ja:['気候変動','子ども','猛暑','洪水'] },
    url: 'https://www.unicef.org/press-releases/1-billion-children',
    i18n: {
      ko: {
        source:'유니세프', title:'기후변화로 어린이 10억 명이 위험에 처해 있어',
        body:'유니세프는 기후변화로 인해 전 세계 어린이 약 10억 명이 폭염, 홍수, 사이클론 등 극단적 기상 현상에 매우 취약한 환경에서 살고 있다고 경고했습니다. 특히 남아시아와 사하라 이남 아프리카 지역 어린이들이 가장 큰 위험에 노출되어 있으며, 이는 교육 기회 박탈과 건강 문제로 이어지고 있습니다.',
        hint:'기후 위기와 직접 관련된 목표, 그리고 건강·교육에 미치는 영향을 함께 떠올려 봐요.',
        fc:'완벽해요! 기후행동(13), 건강(3), 교육(4), 빈곤(1)까지 연결한 뛰어난 분석이에요!',
        fp:'기후행동(13)은 필수예요. 건강(3)과 학교생활(4)에도 영향을 미쳐요.',
        fm:'"기후변화"에서 SDG를 찾고, 건강과 교육에 어떤 영향을 주는지도 연결해보세요.',
        lc:'전기를 아끼고 일회용품을 줄이는 것이 먼 나라 어린이들의 미래와 연결돼 있어요.',
        bonus:'오늘 사용하지 않는 전등과 전자기기 플러그를 뽑아보세요. 가족에게 이유를 설명해보면 더 좋아요.',
      },
      en: {
        source:'UNICEF', title:'One billion children at extreme risk from climate change',
        body:'UNICEF warns that about one billion children worldwide live in environments highly exposed to extreme weather such as heatwaves, floods and cyclones. Children in South Asia and sub-Saharan Africa face the highest risks, which also disrupt their schooling and health.',
        hint:'Start with the goal directly tied to climate, then think about the health and education impacts.',
        fc:'Perfect! Climate Action (13), Health (3), Education (4) and Poverty (1) — a brilliant connection!',
        fp:'Climate Action (13) is essential. It also affects Health (3) and Education (4).',
        fm:'Look for the SDG behind the words "climate change", then link it to health and school.',
        lc:'Saving electricity and cutting single-use items at home is linked to children\'s future across the world.',
        bonus:'Unplug lights and devices you are not using today. Bonus points if you explain why to your family.',
      },
      ja: {
        source:'UNICEF', title:'気候変動で10億人の子どもがリスクに',
        body:'ユニセフは、気候変動により世界で約10億人の子どもが、猛暑・洪水・サイクロンなど極端な気象現象に非常にさらされやすい環境で暮らしていると警告しました。特に南アジアやサハラ以南のアフリカの子どもたちが大きなリスクにさらされており、教育機会の喪失や健康問題にもつながっています。',
        hint:'気候危機に直結する目標と、健康・教育への影響を一緒に考えよう。',
        fc:'完璧!気候(13)、健康(3)、教育(4)、貧困(1)まで結びつけた素晴らしい分析!',
        fp:'気候行動(13)は必須。健康(3)と学校生活(4)にも影響するよ。',
        fm:'「気候変動」からSDGを探し、健康と教育への影響も結びつけてみよう。',
        lc:'電気を節約したり使い捨てを減らすことが、遠い国の子どもたちの未来とつながっているよ。',
        bonus:'今日、使っていない電気と家電のプラグを抜いてみよう。家族にも理由を説明できるとなおよし。',
      },
    },
  },
  {
    correct: [4,5,1,10],
    tags: { ko:['교육','여학생','성평등','유네스코'], en:['education','girls','equality','UNESCO'], ja:['教育','女子','ジェンダー','UNESCO'] },
    url: 'https://news.un.org/en/story/2024/03/1147712',
    i18n: {
      ko: {
        source:'UN뉴스', title:'전 세계 여학생 1억 2천만 명 학교 밖에 있어',
        body:'유네스코 보고서에 따르면 전 세계적으로 약 1억 2천만 명의 여학생이 학교에 다니지 못하고 있습니다. 빈곤, 조혼 문화, 성차별, 안전 문제 등이 주요 원인이며, 교육 격차는 취업 기회와 소득 불평등으로도 이어집니다.',
        hint:'학교에 못 가는 여학생들과 관련된 교육 목표와 성별 불평등 목표를 함께 찾아보세요.',
        fc:'훌륭해요! 교육(4)과 성평등(5)이 핵심이고, 빈곤(1)과 불평등(10)까지 연결했어요!',
        fp:'교육(4)은 찾았나요? "여학생"에서 성별 관련 SDG도 찾아보세요.',
        fm:'"여학생이 학교에 못 간다"에서 교육·성별 관련 SDG를 떠올려 봐요.',
        lc:'학교에서 열심히 배우는 것 자체가 SDG 4를 실천하는 거예요.',
        bonus:'오늘 수업에서 배운 내용 한 가지를 가족에게 가르쳐주세요. 배움을 나누는 것도 교육 나눔이에요.',
      },
      en: {
        source:'UN News', title:'120 million girls out of school worldwide',
        body:'According to a UNESCO report, about 120 million girls are out of school worldwide. Poverty, child marriage, gender discrimination and safety concerns are the main causes, and the education gap leads to wider gaps in jobs and income.',
        hint:'Pick the education goal first, then look for the goal about gender equality.',
        fc:'Excellent! Education (4) and Gender Equality (5) at the core, plus Poverty (1) and Inequality (10).',
        fp:'Did you spot Education (4)? "Girls" should also point to the gender-related SDG.',
        fm:'"Girls out of school" connects directly to education and gender SDGs.',
        lc:'Studying hard at school is, in itself, practicing SDG 4.',
        bonus:'Teach one thing you learned today to your family. Sharing knowledge is also an act of education.',
      },
      ja: {
        source:'UNニュース', title:'世界で1億2千万人の女子が学校に通えない',
        body:'ユネスコの報告書によると、世界で約1億2千万人の女子が学校に通えていません。貧困、早婚の慣習、性差別、安全の問題などが主な原因で、教育の格差は就業機会や所得の不平等にもつながります。',
        hint:'学校に通えない女子に関わる教育目標と、ジェンダー不平等の目標を一緒に探そう。',
        fc:'素晴らしい!教育(4)とジェンダー平等(5)が中心、貧困(1)・不平等(10)まで結びつけたね!',
        fp:'教育(4)は見つかった?「女子」からジェンダー関連のSDGも探してみよう。',
        fm:'「女子が学校に行けない」から、教育とジェンダーのSDGを思い出そう。',
        lc:'学校で一生懸命学ぶこと自体がSDG 4の実践になるよ。',
        bonus:'今日の授業で習ったことを1つ、家族に教えてみよう。学びを分かち合うのも教育のシェアだよ。',
      },
    },
  },
  {
    correct: [6,3,13,1],
    tags: { ko:['식수','위생','어린이','WHO'], en:['water','sanitation','children','WHO'], ja:['水','衛生','子ども','WHO'] },
    url: 'https://www.unicef.org/reports/water-under-fire',
    i18n: {
      ko: {
        source:'유니세프', title:'깨끗한 물 없이 생활하는 어린이 4억 5천만 명',
        body:'유니세프와 세계보건기구(WHO)의 공동 보고서에 따르면, 전 세계 4억 5천만 명의 어린이가 안전한 식수 없이 생활하고 있습니다. 오염된 물 사용으로 인한 설사병은 5세 미만 어린이 사망의 주요 원인 중 하나입니다. 기후변화로 인한 가뭄과 홍수가 상황을 악화시키고 있습니다.',
        hint:'"물"과 직접 관련된 SDG를 먼저 찾고, 오염된 물이 건강에 미치는 영향도 떠올려 보세요.',
        fc:'완벽해요! 깨끗한 물(6), 건강(3), 기후변화(13), 빈곤(1)까지 완벽히 연결했어요!',
        fp:'깨끗한 물(6)이 핵심이에요. 건강(3)도 함께 생각해보세요.',
        fm:'"깨끗한 물"을 SDGs에서 찾고, 오염된 물과 건강의 관계도 생각해보세요.',
        lc:'양치할 때 컵을 사용해 물을 절약해 보세요.',
        bonus:'오늘 물을 사용할 때마다 "이 물은 어디서 올까?"를 생각하고, 물 절약 방법 3가지를 적어보세요.',
      },
      en: {
        source:'UNICEF', title:'450 million children live without safe drinking water',
        body:'A joint UNICEF–WHO report finds 450 million children worldwide live without safe drinking water. Diarrhoea caused by contaminated water is among the leading causes of death for children under five. Climate-driven droughts and floods are making the situation worse.',
        hint:'Start with the SDG directly about "water", then think about its effect on health.',
        fc:'Perfect! Clean Water (6), Health (3), Climate (13) and Poverty (1) — beautifully connected!',
        fp:'Clean Water (6) is the core. Don\'t forget Health (3).',
        fm:'Find "clean water" in the SDGs, then connect dirty water to health.',
        lc:'Using a cup while brushing your teeth is a real way to save water.',
        bonus:'Every time you use water today, ask "where does this come from?" — then list three ways to save water.',
      },
      ja: {
        source:'UNICEF', title:'安全な水を使えない子ども4億5千万人',
        body:'ユニセフとWHOの共同報告書によると、世界で4億5千万人の子どもが安全な飲み水を利用できずに暮らしています。汚れた水による下痢は、5歳未満の子どもの死亡の主な原因の一つです。気候変動による干ばつや洪水が状況を悪化させています。',
        hint:'まず「水」に直結するSDGを探し、汚れた水が健康に与える影響も考えよう。',
        fc:'完璧!きれいな水(6)、健康(3)、気候(13)、貧困(1)までうまくつなげたね!',
        fp:'きれいな水(6)が中心。健康(3)も一緒に考えよう。',
        fm:'「きれいな水」をSDGsから探し、汚れた水と健康の関係も考えてみよう。',
        lc:'歯みがきのときコップを使うと、本当に水を節約できるよ。',
        bonus:'今日、水を使うたびに「この水はどこから?」と考え、節水の方法を3つ書き出してみよう。',
      },
    },
  },
  {
    correct: [14,12,17,3],
    tags: { ko:['플라스틱','해양오염','생태계','UNEP'], en:['plastic','ocean','ecosystem','UNEP'], ja:['プラスチック','海洋汚染','生態系','UNEP'] },
    url: 'https://www.unep.org/news-and-stories/press-release/plastic-pollution',
    i18n: {
      ko: {
        source:'UNDP', title:'해양 플라스틱 오염, 2040년까지 3배 증가 전망',
        body:'유엔환경계획(UNEP)은 현재 추세가 계속된다면 2040년까지 해양으로 유입되는 플라스틱 양이 지금의 3배에 달할 것이라고 경고했습니다. 매년 800만 톤 이상의 플라스틱이 바다로 흘러들어 해양 생태계를 파괴하고 먹이사슬을 통해 인간에게도 영향을 줍니다.',
        hint:'"바다"와 관련된 SDG와 플라스틱 소비 관련 목표를 함께 떠올려 보세요.',
        fc:'탁월해요! 해양(14), 책임있는 소비(12), 협력(17), 건강(3)까지 완벽해요!',
        fp:'해양생태계(14)는 꼭 포함해야 해요. 플라스틱을 줄이는 소비 관련 SDG도 찾아보세요.',
        fm:'"해양"에서 바다 관련 SDG를, 플라스틱 소비 습관에서 또 다른 SDG를 찾아보세요.',
        lc:'일회용 플라스틱 컵 하나를 덜 쓰는 것이 바다를 지키는 행동이에요.',
        bonus:'오늘 하루 일회용 플라스틱을 하나도 사용하지 않는 "플라스틱 프리 챌린지"에 도전해보세요.',
      },
      en: {
        source:'UNDP', title:'Ocean plastic pollution set to triple by 2040',
        body:'UNEP warns that if current trends continue, the amount of plastic flowing into the oceans will triple by 2040. Over 8 million tonnes of plastic enter the sea each year, destroying marine ecosystems and reaching humans through the food chain.',
        hint:'Look for the "ocean" SDG, and the goal about responsible consumption.',
        fc:'Outstanding! Life Below Water (14), Responsible Consumption (12), Partnerships (17) and Health (3) — perfect!',
        fp:'Life Below Water (14) is a must. Add the SDG about reducing consumption too.',
        fm:'Find the ocean SDG, then think about plastic habits and the consumption SDG.',
        lc:'Skipping one single-use plastic cup today is already a small act for the ocean.',
        bonus:'Try a one-day "plastic free" challenge — use zero single-use plastics today.',
      },
      ja: {
        source:'UNDP', title:'海洋プラスチック汚染、2040年までに3倍に',
        body:'国連環境計画(UNEP)は、現在の傾向が続けば2040年までに海に流れ込むプラスチックが現在の3倍になると警告しました。毎年800万トン以上のプラスチックが海に流れ込み、海洋生態系を破壊し、食物連鎖を通じて人間にも影響します。',
        hint:'「海」に関わるSDGと、プラスチック消費に関する目標を一緒に考えよう。',
        fc:'素晴らしい!海(14)、責任ある消費(12)、パートナーシップ(17)、健康(3)まで完璧!',
        fp:'海の生態系(14)は必ず含めよう。プラスチックを減らす消費のSDGも探してみて。',
        fm:'「海」から海のSDG、プラスチックの使い方から別のSDGを探してみよう。',
        lc:'使い捨てプラスチックのコップを1つ減らすことも、海を守る行動だよ。',
        bonus:'今日1日「プラスチックフリーチャレンジ」——使い捨てプラスチックを一切使わないことに挑戦しよう。',
      },
    },
  },
  {
    correct: [4,16,1,10],
    tags: { ko:['분쟁','교육','어린이','난민'], en:['conflict','education','children','refugees'], ja:['紛争','教育','子ども','難民'] },
    url: 'https://news.un.org/en/story/2024/09/1154321',
    i18n: {
      ko: {
        source:'UN뉴스', title:'분쟁 지역 어린이 4천만 명 교육 위기',
        body:'유엔은 현재 전 세계 분쟁 지역에서 약 4천만 명의 어린이가 학교 교육을 받지 못하고 있다고 발표했습니다. 우크라이나, 수단, 가자지구, 미얀마 등지에서 학교 시설이 파괴되거나 어린이들이 피란길에 오르면서 교육이 중단되고 있습니다.',
        hint:'전쟁·분쟁 관련 SDG와 교육 기회 박탈 관련 SDG를 함께 찾아보세요.',
        fc:'훌륭해요! 교육(4)과 평화(16)가 핵심이고, 빈곤(1)·불평등(10)까지 연결했어요!',
        fp:'교육(4)은 반드시 포함해야 해요. "분쟁 지역"에서 평화 관련 SDG도 찾아보세요.',
        fm:'"분쟁"과 "교육"이 두 핵심 단어예요. 각각 관련 SDG를 찾아봐요.',
        lc:'평화로운 환경에서 학교를 다닐 수 있다는 게 얼마나 소중한지 떠올려 보세요.',
        bonus:'학급에서 도움이 필요한 친구가 있는지 살펴보고, 오늘 한 명에게 먼저 말을 걸어보세요.',
      },
      en: {
        source:'UN News', title:'40 million children in conflict zones face education crisis',
        body:'The UN reports about 40 million children in conflict zones worldwide are missing school. In Ukraine, Sudan, Gaza, Myanmar and elsewhere, schools have been destroyed or families displaced, breaking children\'s education and risking a long-term cycle of poverty.',
        hint:'Look for the SDG about peace and the SDG about education together.',
        fc:'Excellent! Education (4) and Peace (16) at the core, plus Poverty (1) and Inequality (10).',
        fp:'Education (4) is a must. "Conflict zones" should also lead you to the peace SDG.',
        fm:'Two key words: "conflict" and "education". Find the SDG for each.',
        lc:'Being able to go to school in peace is something truly precious.',
        bonus:'Look for a classmate who needs help, and be the first to speak to them today.',
      },
      ja: {
        source:'UNニュース', title:'紛争地域の子ども4千万人が教育の危機に',
        body:'国連は、世界の紛争地域で約4千万人の子どもが学校に通えていないと発表しました。ウクライナ、スーダン、ガザ、ミャンマーなどで学校が破壊されたり、子どもたちが避難を余儀なくされたりして教育が中断しています。',
        hint:'戦争・紛争に関わるSDGと、教育の機会喪失に関わるSDGを一緒に探そう。',
        fc:'素晴らしい!教育(4)と平和(16)が中心、貧困(1)・不平等(10)もつなげられたね!',
        fp:'教育(4)は必ず。「紛争地域」から平和のSDGも探してみよう。',
        fm:'「紛争」と「教育」の2つがキーワード。それぞれのSDGを見つけよう。',
        lc:'平和な環境で学校に通えることがどんなに大切か、考えてみよう。',
        bonus:'クラスで助けが必要な友だちはいないかな?今日は1人に自分から声をかけてみよう。',
      },
    },
  },
  {
    correct: [3,1,10,17],
    tags: { ko:['백신','보건','어린이','코로나'], en:['vaccine','health','children','COVID'], ja:['ワクチン','保健','子ども','コロナ'] },
    url: 'https://www.unicef.org/press-releases/children-missed-vaccinations',
    i18n: {
      ko: {
        source:'유니세프', title:'코로나 이후 어린이 백신 접종률 여전히 회복 안 돼',
        body:'유니세프와 WHO는 코로나19 팬데믹 이후 전 세계 어린이 백신 접종률이 아직 팬데믹 이전 수준을 회복하지 못했다고 밝혔습니다. 약 6700만 명의 어린이가 정기 예방접종을 놓쳤으며, 홍역·소아마비 등 예방 가능한 질병 발생이 다시 증가하고 있습니다.',
        hint:'"백신"과 "건강"이 핵심이에요. 가난한 나라에서 더 심각한 불평등 측면도 떠올려 보세요.',
        fc:'완벽해요! 건강(3), 빈곤(1), 불평등(10), 협력(17)까지 연결했어요!',
        fp:'건강(3)은 꼭 포함해야 해요. 불평등 측면도 함께 생각해보세요.',
        fm:'"백신 접종"은 어떤 SDG와 관련 있을까요? 건강 관련 목표를 찾아봐요.',
        lc:'나의 건강을 잘 챙기는 것도 세계시민 의식의 시작이에요.',
        bonus:'오늘 내가 받은 예방접종 기록을 부모님과 함께 확인해보세요.',
      },
      en: {
        source:'UNICEF', title:'Child vaccination rates still below pre-COVID levels',
        body:'UNICEF and WHO say global child vaccination rates have not yet recovered to pre-pandemic levels. About 67 million children missed routine immunizations during COVID-19, and preventable diseases like measles and polio are rising again.',
        hint:'"Vaccines" and "health" are the keys. Also think about inequality — it hits poorer countries harder.',
        fc:'Perfect! Health (3), Poverty (1), Inequality (10) and Partnerships (17) — well connected!',
        fp:'Health (3) is a must. Also think about the inequality angle.',
        fm:'Which SDG matches "vaccination"? Find the one about health.',
        lc:'Looking after your own health is the start of being a global citizen.',
        bonus:'Check your immunization record with your parents today.',
      },
      ja: {
        source:'UNICEF', title:'コロナ後、子どものワクチン接種率がまだ回復せず',
        body:'ユニセフとWHOは、コロナ後も世界の子どものワクチン接種率がパンデミック前の水準まで回復していないと発表しました。約6,700万人の子どもが定期接種を逃しており、はしかやポリオなど予防可能な病気が再び増えています。',
        hint:'「ワクチン」と「健康」が鍵。貧しい国でより深刻な不平等の面も考えてみよう。',
        fc:'完璧!健康(3)、貧困(1)、不平等(10)、協力(17)までつなげたね!',
        fp:'健康(3)は必ず。不平等の側面も一緒に考えよう。',
        fm:'「ワクチン」はどのSDGと関わる?健康の目標を探してみよう。',
        lc:'自分の健康を大切にすることが、世界市民意識のはじまりだよ。',
        bonus:'今日、自分の予防接種の記録を保護者と一緒に確認してみよう。',
      },
    },
  },
  {
    correct: [13,7,17,11],
    tags: { ko:['기후변화','지구온난화','파리협정','WMO'], en:['climate','warming','Paris Agreement','WMO'], ja:['気候変動','温暖化','パリ協定','WMO'] },
    url: 'https://news.un.org/en/story/2024/11/1156789',
    i18n: {
      ko: {
        source:'UNDP', title:'지구 평균 기온, 산업화 이전 대비 1.5°C 첫 돌파',
        body:'세계기상기구(WMO)는 2024년이 관측 역사상 지구 평균 기온이 산업화 이전 수준보다 1.5°C 이상 높아진 첫 번째 해가 될 가능성이 높다고 발표했습니다. 이상 폭염, 초강력 태풍, 전례 없는 산불이 이를 뒷받침합니다. 파리협정 목표 달성을 위한 즉각적인 온실가스 감축이 촉구되고 있습니다.',
        hint:'기후변화 관련 SDG와 에너지 전환 관련 SDG를 함께 찾아보세요.',
        fc:'탁월해요! 기후행동(13), 청정에너지(7), 국제 협력(17), 지속가능 도시(11)까지 완벽해요!',
        fp:'기후행동(13)은 핵심이에요. 에너지 관련 SDG도 함께 생각해보세요.',
        fm:'"기온 상승"과 "기후"에서 SDG를 찾고, 에너지 문제와도 연결해보세요.',
        lc:'석탄 대신 태양광·풍력 전기를 쓰려는 노력이 지구 온도를 낮추는 데 도움이 돼요.',
        bonus:'오늘 에어컨이나 히터 온도를 1도 조절하고, 가족에게 기후변화와 연결해서 설명해보세요.',
      },
      en: {
        source:'UNDP', title:'Global temperature passes 1.5°C above pre-industrial for the first time',
        body:'The World Meteorological Organization (WMO) reports 2024 is likely to be the first year in recorded history where the global average temperature is more than 1.5°C above pre-industrial levels. Heatwaves, super typhoons and unprecedented wildfires support this. Immediate emission cuts are urgently needed to meet the Paris Agreement goal.',
        hint:'Look for the climate SDG and the SDG about clean energy together.',
        fc:'Outstanding! Climate Action (13), Clean Energy (7), Partnerships (17) and Sustainable Cities (11) — perfect!',
        fp:'Climate Action (13) is the core. Also think about the energy SDG.',
        fm:'Find the SDG behind "rising temperature", then connect it to energy.',
        lc:'Switching from coal to solar or wind power really helps cool the planet.',
        bonus:'Change your AC or heater by 1°C today, and explain to your family how it connects to climate change.',
      },
      ja: {
        source:'UNDP', title:'地球の平均気温、産業革命前比1.5°Cを初めて超える',
        body:'世界気象機関(WMO)は、2024年が観測史上初めて地球の平均気温が産業革命前を1.5°C以上上回る年になる可能性が高いと発表しました。猛暑、超大型台風、前例のない山火事がそれを裏付けています。パリ協定の目標達成に向けた即時の温室効果ガス削減が求められています。',
        hint:'気候変動に関わるSDGと、エネルギー転換に関わるSDGを一緒に探そう。',
        fc:'素晴らしい!気候行動(13)、クリーンエネルギー(7)、協力(17)、持続可能な都市(11)まで完璧!',
        fp:'気候行動(13)が中心。エネルギーのSDGも一緒に考えよう。',
        fm:'「気温上昇」「気候」からSDGを探し、エネルギー問題とも結びつけよう。',
        lc:'石炭の代わりに太陽光や風力の電気を使う取り組みが、地球の気温を下げる助けになるよ。',
        bonus:'今日、エアコンや暖房の温度を1度だけ調整して、家族に気候変動とのつながりを説明してみよう。',
      },
    },
  },
];
