// SDG color palette (UN official)
const SDG_COLORS = [
  '#E5243B','#DDA63A','#4C9F38','#C5192D','#FF3A21','#26BDE2','#FCC30B','#A21942',
  '#FD6925','#DD1367','#FD9D24','#BF8B2E','#3F7E44','#0A97D9','#56C02B','#00689D','#19486A',
];

// News DB: correct SDGs apply across languages; localized text per language.
const NEWS_DB = [
  {
    correct: [2,1,13,17],
    tags: { ko:['식량','기아','아프리카','FAO'], en:['food','hunger','Africa','FAO'], ja:['食料','飢餓','アフリカ','FAO'] },
    url: 'https://news.un.org/en/story/2024/07/1152236',
    i18n: {
      ko: {
        source:'UN뉴스', title:'전 세계 7억 3천만 명이 여전히 극심한 굶주림에 시달려',
        body:'유엔 식량농업기구(FAO)는 2024년 보고서에서 전 세계 약 7억 3천만 명이 만성적인 식량 부족 상태에 있다고 밝혔습니다. 특히 사하라 이남 아프리카와 남아시아에서 상황이 심각하며, 기후 변화와 분쟁이 주요 원인으로 꼽힙니다. 어린이 영양실조도 여전히 심각한 문제로 남아 있습니다.',
        hint:'음식이 부족한 사람들과 관련된 목표, 그리고 그 원인인 기후와 가난을 함께 생각해보세요.',
        fc:'훌륭해요! 기아(SDG 2)가 핵심이지만, 빈곤(SDG 1), 기후변화(SDG 13), 국제 협력(SDG 17)과도 깊이 연결돼요.',
        fp:'좋은 시작이에요! 기아(SDG 2)는 잘 찾았어요. 빈곤(SDG 1)과 기후변화(SDG 13)도 함께 생각해보세요.',
        fm:'기사에서 "굶주림"이라는 단어를 주목해보세요. 식량 문제와 기후·빈곤의 관계를 떠올려 봐요.',
        lc:'우리가 음식을 낭비하지 않고 급식을 남기지 않는 것도 SDG 2를 실천하는 거예요.',
        bonus:'오늘 급식에서 음식을 하나도 남기지 않아 보세요. 먹지 못하는 친구들을 생각하며 감사히 먹는 것도 세계시민 행동이에요.',
      },
      en: {
        source:'UN News', title:'730 million people still face severe hunger worldwide',
        body:'In its 2024 report, the UN Food and Agriculture Organization (FAO) said about 730 million people remain chronically food-insecure. The situation is most severe in sub-Saharan Africa and South Asia, with climate change and conflict driving the crisis. Child malnutrition remains a serious problem.',
        hint:'Think about the goal directly linked to people without enough food, plus the climate and poverty causes behind it.',
        fc:'Excellent! Zero Hunger (SDG 2) is the core, but Poverty (1), Climate Action (13) and Partnerships (17) are deeply connected too.',
        fp:'Good start! You spotted Hunger (SDG 2). Try also Poverty (1) and Climate Action (13).',
        fm:'Notice the word "hunger" in the article — then think about how climate and poverty cause it.',
        lc:'Not wasting food at school lunch is already a small act for SDG 2.',
        bonus:'Try to leave no food on your plate today. Eating with gratitude for those who cannot is itself a global-citizen action.',
      },
      ja: {
        source:'UNニュース', title:'世界で7億3千万人が依然として深刻な飢餓に',
        body:'国連食糧農業機関(FAO)は2024年の報告書で、世界で約7億3千万人が慢性的な食料不足の状態にあると発表しました。特にサハラ以南のアフリカと南アジアで状況が深刻で、気候変動と紛争が主な原因とされています。子どもの栄養失調も依然として深刻です。',
        hint:'食べ物が足りない人々に直結する目標と、その原因である気候・貧困を一緒に考えてみよう。',
        fc:'素晴らしい!飢餓(SDG 2)が中心だけど、貧困(1)、気候変動(13)、パートナーシップ(17)とも深くつながっているよ。',
        fp:'いいスタート!飢餓(SDG 2)はバッチリ。貧困(1)と気候変動(13)も一緒に考えてみよう。',
        fm:'記事の「飢餓」という言葉に注目。気候や貧困との関係も考えてみよう。',
        lc:'給食を残さず食べることも、SDG 2の実践のひとつだよ。',
        bonus:'今日の給食を残さず食べてみよう。食べられない人を想い、感謝して食べることも世界市民の行動だよ。',
      },
    },
  },
  {
    correct: [13,3,4,1],
    tags: { ko:['기후변화','어린이','폭염','홍수'], en:['climate','children','heatwave','flood'], ja:['気候変動','子ども','猛暑','洪水'] },
    url: 'https://www.unicef.org/press-releases/1-billion-children',
    i18n: {
      ko: {
        source:'유니세프', title:'기후변화로 어린이 10억 명이 위험에 처해 있어',
        body:'유니세프는 기후변화로 인해 전 세계 어린이 약 10억 명이 폭염, 홍수, 사이클론 등 극단적 기상 현상에 매우 취약한 환경에서 살고 있다고 경고했습니다. 특히 남아시아와 사하라 이남 아프리카 지역 어린이들이 가장 큰 위험에 노출되어 있으며, 이는 교육 기회 박탈과 건강 문제로 이어지고 있습니다.',
        hint:'기후 위기와 직접 관련된 목표, 그리고 건강·교육에 미치는 영향을 함께 떠올려 봐요.',
        fc:'완벽해요! 기후행동(13), 건강(3), 교육(4), 빈곤(1)까지 연결한 뛰어난 분석이에요!',
        fp:'기후행동(13)은 필수예요. 건강(3)과 학교생활(4)에도 영향을 미쳐요.',
        fm:'"기후변화"에서 SDG를 찾고, 건강과 교육에 어떤 영향을 주는지도 연결해보세요.',
        lc:'전기를 아끼고 일회용품을 줄이는 것이 먼 나라 어린이들의 미래와 연결돼 있어요.',
        bonus:'오늘 사용하지 않는 전등과 전자기기 플러그를 뽑아보세요. 가족에게 이유를 설명해보면 더 좋아요.',
      },
      en: {
        source:'UNICEF', title:'One billion children at extreme risk from climate change',
        body:'UNICEF warns that about one billion children worldwide live in environments highly exposed to extreme weather such as heatwaves, floods and cyclones. Children in South Asia and sub-Saharan Africa face the highest risks, which also disrupt their schooling and health.',
        hint:'Start with the goal directly tied to climate, then think about the health and education impacts.',
        fc:'Perfect! Climate Action (13), Health (3), Education (4) and Poverty (1) — a brilliant connection!',
        fp:'Climate Action (13) is essential. It also affects Health (3) and Education (4).',
        fm:'Look for the SDG behind the words "climate change", then link it to health and school.',
        lc:'Saving electricity and cutting single-use items at home is linked to children\'s future across the world.',
        bonus:'Unplug lights and devices you are not using today. Bonus points if you explain why to your family.',
      },
      ja: {
        source:'UNICEF', title:'気候変動で10億人の子どもがリスクに',
        body:'ユニセフは、気候変動により世界で約10億人の子どもが、猛暑・洪水・サイクロンなど極端な気象現象に非常にさらされやすい環境で暮らしていると警告しました。特に南アジアやサハラ以南のアフリカの子どもたちが大きなリスクにさらされており、教育機会の喪失や健康問題にもつながっています。',
        hint:'気候危機に直結する目標と、健康・教育への影響を一緒に考えよう。',
        fc:'完璧!気候(13)、健康(3)、教育(4)、貧困(1)まで結びつけた素晴らしい分析!',
        fp:'気候行動(13)は必須。健康(3)と学校生活(4)にも影響するよ。',
        fm:'「気候変動」からSDGを探し、健康と教育への影響も結びつけてみよう。',
        lc:'電気を節約したり使い捨てを減らすことが、遠い国の子どもたちの未来とつながっているよ。',
        bonus:'今日、使っていない電気と家電のプラグを抜いてみよう。家族にも理由を説明できるとなおよし。',
      },
    },
  },
  {
    correct: [4,5,1,10],
    tags: { ko:['교육','여학생','성평등','유네스코'], en:['education','girls','equality','UNESCO'], ja:['教育','女子','ジェンダー','UNESCO'] },
    url: 'https://news.un.org/en/story/2024/03/1147712',
    i18n: {
      ko: {
        source:'UN뉴스', title:'전 세계 여학생 1억 2천만 명 학교 밖에 있어',
        body:'유네스코 보고서에 따르면 전 세계적으로 약 1억 2천만 명의 여학생이 학교에 다니지 못하고 있습니다. 빈곤, 조혼 문화, 성차별, 안전 문제 등이 주요 원인이며, 교육 격차는 취업 기회와 소득 불평등으로도 이어집니다.',
        hint:'학교에 못 가는 여학생들과 관련된 교육 목표와 성별 불평등 목표를 함께 찾아보세요.',
        fc:'훌륭해요! 교육(4)과 성평등(5)이 핵심이고, 빈곤(1)과 불평등(10)까지 연결했어요!',
        fp:'교육(4)은 찾았나요? "여학생"에서 성별 관련 SDG도 찾아보세요.',
        fm:'"여학생이 학교에 못 간다"에서 교육·성별 관련 SDG를 떠올려 봐요.',
        lc:'학교에서 열심히 배우는 것 자체가 SDG 4를 실천하는 거예요.',
        bonus:'오늘 수업에서 배운 내용 한 가지를 가족에게 가르쳐주세요. 배움을 나누는 것도 교육 나눔이에요.',
      },
      en: {
        source:'UN News', title:'120 million girls out of school worldwide',
        body:'According to a UNESCO report, about 120 million girls are out of school worldwide. Poverty, child marriage, gender discrimination and safety concerns are the main causes, and the education gap leads to wider gaps in jobs and income.',
        hint:'Pick the education goal first, then look for the goal about gender equality.',
        fc:'Excellent! Education (4) and Gender Equality (5) at the core, plus Poverty (1) and Inequality (10).',
        fp:'Did you spot Education (4)? "Girls" should also point to the gender-related SDG.',
        fm:'"Girls out of school" connects directly to education and gender SDGs.',
        lc:'Studying hard at school is, in itself, practicing SDG 4.',
        bonus:'Teach one thing you learned today to your family. Sharing knowledge is also an act of education.',
      },
      ja: {
        source:'UNニュース', title:'世界で1億2千万人の女子が学校に通えない',
        body:'ユネスコの報告書によると、世界で約1億2千万人の女子が学校に通えていません。貧困、早婚の慣習、性差別、安全の問題などが主な原因で、教育の格差は就業機会や所得の不平等にもつながります。',
        hint:'学校に通えない女子に関わる教育目標と、ジェンダー不平等の目標を一緒に探そう。',
        fc:'素晴らしい!教育(4)とジェンダー平等(5)が中心、貧困(1)・不平等(10)まで結びつけたね!',
        fp:'教育(4)は見つかった?「女子」からジェンダー関連のSDGも探してみよう。',
        fm:'「女子が学校に行けない」から、教育とジェンダーのSDGを思い出そう。',
        lc:'学校で一生懸命学ぶこと自体がSDG 4の実践になるよ。',
        bonus:'今日の授業で習ったことを1つ、家族に教えてみよう。学びを分かち合うのも教育のシェアだよ。',
      },
    },
  },
  {
    correct: [6,3,13,1],
    tags: { ko:['식수','위생','어린이','WHO'], en:['water','sanitation','children','WHO'], ja:['水','衛生','子ども','WHO'] },
    url: 'https://www.unicef.org/reports/water-under-fire',
    i18n: {
      ko: {
        source:'유니세프', title:'깨끗한 물 없이 생활하는 어린이 4억 5천만 명',
        body:'유니세프와 세계보건기구(WHO)의 공동 보고서에 따르면, 전 세계 4억 5천만 명의 어린이가 안전한 식수 없이 생활하고 있습니다. 오염된 물 사용으로 인한 설사병은 5세 미만 어린이 사망의 주요 원인 중 하나입니다. 기후변화로 인한 가뭄과 홍수가 상황을 악화시키고 있습니다.',
        hint:'"물"과 직접 관련된 SDG를 먼저 찾고, 오염된 물이 건강에 미치는 영향도 떠올려 보세요.',
        fc:'완벽해요! 깨끗한 물(6), 건강(3), 기후변화(13), 빈곤(1)까지 완벽히 연결했어요!',
        fp:'깨끗한 물(6)이 핵심이에요. 건강(3)도 함께 생각해보세요.',
        fm:'"깨끗한 물"을 SDGs에서 찾고, 오염된 물과 건강의 관계도 생각해보세요.',
        lc:'양치할 때 컵을 사용해 물을 절약해 보세요.',
        bonus:'오늘 물을 사용할 때마다 "이 물은 어디서 올까?"를 생각하고, 물 절약 방법 3가지를 적어보세요.',
      },
      en: {
        source:'UNICEF', title:'450 million children live without safe drinking water',
        body:'A joint UNICEF–WHO report finds 450 million children worldwide live without safe drinking water. Diarrhoea caused by contaminated water is among the leading causes of death for children under five. Climate-driven droughts and floods are making the situation worse.',
        hint:'Start with the SDG directly about "water", then think about its effect on health.',
        fc:'Perfect! Clean Water (6), Health (3), Climate (13) and Poverty (1) — beautifully connected!',
        fp:'Clean Water (6) is the core. Don\'t forget Health (3).',
        fm:'Find "clean water" in the SDGs, then connect dirty water to health.',
        lc:'Using a cup while brushing your teeth is a real way to save water.',
        bonus:'Every time you use water today, ask "where does this come from?" — then list three ways to save water.',
      },
      ja: {
        source:'UNICEF', title:'安全な水を使えない子ども4億5千万人',
        body:'ユニセフとWHOの共同報告書によると、世界で4億5千万人の子どもが安全な飲み水を利用できずに暮らしています。汚れた水による下痢は、5歳未満の子どもの死亡の主な原因の一つです。気候変動による干ばつや洪水が状況を悪化させています。',
        hint:'まず「水」に直結するSDGを探し、汚れた水が健康に与える影響も考えよう。',
        fc:'完璧!きれいな水(6)、健康(3)、気候(13)、貧困(1)までうまくつなげたね!',
        fp:'きれいな水(6)が中心。健康(3)も一緒に考えよう。',
        fm:'「きれいな水」をSDGsから探し、汚れた水と健康の関係も考えてみよう。',
        lc:'歯みがきのときコップを使うと、本当に水を節約できるよ。',
        bonus:'今日、水を使うたびに「この水はどこから?」と考え、節水の方法を3つ書き出してみよう。',
      },
    },
  },
  {
    correct: [14,12,17,3],
    tags: { ko:['플라스틱','해양오염','생태계','UNEP'], en:['plastic','ocean','ecosystem','UNEP'], ja:['プラスチック','海洋汚染','生態系','UNEP'] },
    url: 'https://www.unep.org/news-and-stories/press-release/plastic-pollution',
    i18n: {
      ko: {
        source:'UNDP', title:'해양 플라스틱 오염, 2040년까지 3배 증가 전망',
        body:'유엔환경계획(UNEP)은 현재 추세가 계속된다면 2040년까지 해양으로 유입되는 플라스틱 양이 지금의 3배에 달할 것이라고 경고했습니다. 매년 800만 톤 이상의 플라스틱이 바다로 흘러들어 해양 생태계를 파괴하고 먹이사슬을 통해 인간에게도 영향을 줍니다.',
        hint:'"바다"와 관련된 SDG와 플라스틱 소비 관련 목표를 함께 떠올려 보세요.',
        fc:'탁월해요! 해양(14), 책임있는 소비(12), 협력(17), 건강(3)까지 완벽해요!',
        fp:'해양생태계(14)는 꼭 포함해야 해요. 플라스틱을 줄이는 소비 관련 SDG도 찾아보세요.',
        fm:'"해양"에서 바다 관련 SDG를, 플라스틱 소비 습관에서 또 다른 SDG를 찾아보세요.',
        lc:'일회용 플라스틱 컵 하나를 덜 쓰는 것이 바다를 지키는 행동이에요.',
        bonus:'오늘 하루 일회용 플라스틱을 하나도 사용하지 않는 "플라스틱 프리 챌린지"에 도전해보세요.',
      },
      en: {
        source:'UNDP', title:'Ocean plastic pollution set to triple by 2040',
        body:'UNEP warns that if current trends continue, the amount of plastic flowing into the oceans will triple by 2040. Over 8 million tonnes of plastic enter the sea each year, destroying marine ecosystems and reaching humans through the food chain.',
        hint:'Look for the "ocean" SDG, and the goal about responsible consumption.',
        fc:'Outstanding! Life Below Water (14), Responsible Consumption (12), Partnerships (17) and Health (3) — perfect!',
        fp:'Life Below Water (14) is a must. Add the SDG about reducing consumption too.',
        fm:'Find the ocean SDG, then think about plastic habits and the consumption SDG.',
        lc:'Skipping one single-use plastic cup today is already a small act for the ocean.',
        bonus:'Try a one-day "plastic free" challenge — use zero single-use plastics today.',
      },
      ja: {
        source:'UNDP', title:'海洋プラスチック汚染、2040年までに3倍に',
        body:'国連環境計画(UNEP)は、現在の傾向が続けば2040年までに海に流れ込むプラスチックが現在の3倍になると警告しました。毎年800万トン以上のプラスチックが海に流れ込み、海洋生態系を破壊し、食物連鎖を通じて人間にも影響します。',
        hint:'「海」に関わるSDGと、プラスチック消費に関する目標を一緒に考えよう。',
        fc:'素晴らしい!海(14)、責任ある消費(12)、パートナーシップ(17)、健康(3)まで完璧!',
        fp:'海の生態系(14)は必ず含めよう。プラスチックを減らす消費のSDGも探してみて。',
        fm:'「海」から海のSDG、プラスチックの使い方から別のSDGを探してみよう。',
        lc:'使い捨てプラスチックのコップを1つ減らすことも、海を守る行動だよ。',
        bonus:'今日1日「プラスチックフリーチャレンジ」——使い捨てプラスチックを一切使わないことに挑戦しよう。',
      },
    },
  },
  {
    correct: [4,16,1,10],
    tags: { ko:['분쟁','교육','어린이','난민'], en:['conflict','education','children','refugees'], ja:['紛争','教育','子ども','難民'] },
    url: 'https://news.un.org/en/story/2024/09/1154321',
    i18n: {
      ko: {
        source:'UN뉴스', title:'분쟁 지역 어린이 4천만 명 교육 위기',
        body:'유엔은 현재 전 세계 분쟁 지역에서 약 4천만 명의 어린이가 학교 교육을 받지 못하고 있다고 발표했습니다. 우크라이나, 수단, 가자지구, 미얀마 등지에서 학교 시설이 파괴되거나 어린이들이 피란길에 오르면서 교육이 중단되고 있습니다.',
        hint:'전쟁·분쟁 관련 SDG와 교육 기회 박탈 관련 SDG를 함께 찾아보세요.',
        fc:'훌륭해요! 교육(4)과 평화(16)가 핵심이고, 빈곤(1)·불평등(10)까지 연결했어요!',
        fp:'교육(4)은 반드시 포함해야 해요. "분쟁 지역"에서 평화 관련 SDG도 찾아보세요.',
        fm:'"분쟁"과 "교육"이 두 핵심 단어예요. 각각 관련 SDG를 찾아봐요.',
        lc:'평화로운 환경에서 학교를 다닐 수 있다는 게 얼마나 소중한지 떠올려 보세요.',
        bonus:'학급에서 도움이 필요한 친구가 있는지 살펴보고, 오늘 한 명에게 먼저 말을 걸어보세요.',
      },
      en: {
        source:'UN News', title:'40 million children in conflict zones face education crisis',
        body:'The UN reports about 40 million children in conflict zones worldwide are missing school. In Ukraine, Sudan, Gaza, Myanmar and elsewhere, schools have been destroyed or families displaced, breaking children\'s education and risking a long-term cycle of poverty.',
        hint:'Look for the SDG about peace and the SDG about education together.',
        fc:'Excellent! Education (4) and Peace (16) at the core, plus Poverty (1) and Inequality (10).',
        fp:'Education (4) is a must. "Conflict zones" should also lead you to the peace SDG.',
        fm:'Two key words: "conflict" and "education". Find the SDG for each.',
        lc:'Being able to go to school in peace is something truly precious.',
        bonus:'Look for a classmate who needs help, and be the first to speak to them today.',
      },
      ja: {
        source:'UNニュース', title:'紛争地域の子ども4千万人が教育の危機に',
        body:'国連は、世界の紛争地域で約4千万人の子どもが学校に通えていないと発表しました。ウクライナ、スーダン、ガザ、ミャンマーなどで学校が破壊されたり、子どもたちが避難を余儀なくされたりして教育が中断しています。',
        hint:'戦争・紛争に関わるSDGと、教育の機会喪失に関わるSDGを一緒に探そう。',
        fc:'素晴らしい!教育(4)と平和(16)が中心、貧困(1)・不平等(10)もつなげられたね!',
        fp:'教育(4)は必ず。「紛争地域」から平和のSDGも探してみよう。',
        fm:'「紛争」と「教育」の2つがキーワード。それぞれのSDGを見つけよう。',
        lc:'平和な環境で学校に通えることがどんなに大切か、考えてみよう。',
        bonus:'クラスで助けが必要な友だちはいないかな?今日は1人に自分から声をかけてみよう。',
      },
    },
  },
  {
    correct: [3,1,10,17],
    tags: { ko:['백신','보건','어린이','코로나'], en:['vaccine','health','children','COVID'], ja:['ワクチン','保健','子ども','コロナ'] },
    url: 'https://www.unicef.org/press-releases/children-missed-vaccinations',
    i18n: {
      ko: {
        source:'유니세프', title:'코로나 이후 어린이 백신 접종률 여전히 회복 안 돼',
        body:'유니세프와 WHO는 코로나19 팬데믹 이후 전 세계 어린이 백신 접종률이 아직 팬데믹 이전 수준을 회복하지 못했다고 밝혔습니다. 약 6700만 명의 어린이가 정기 예방접종을 놓쳤으며, 홍역·소아마비 등 예방 가능한 질병 발생이 다시 증가하고 있습니다.',
        hint:'"백신"과 "건강"이 핵심이에요. 가난한 나라에서 더 심각한 불평등 측면도 떠올려 보세요.',
        fc:'완벽해요! 건강(3), 빈곤(1), 불평등(10), 협력(17)까지 연결했어요!',
        fp:'건강(3)은 꼭 포함해야 해요. 불평등 측면도 함께 생각해보세요.',
        fm:'"백신 접종"은 어떤 SDG와 관련 있을까요? 건강 관련 목표를 찾아봐요.',
        lc:'나의 건강을 잘 챙기는 것도 세계시민 의식의 시작이에요.',
        bonus:'오늘 내가 받은 예방접종 기록을 부모님과 함께 확인해보세요.',
      },
      en: {
        source:'UNICEF', title:'Child vaccination rates still below pre-COVID levels',
        body:'UNICEF and WHO say global child vaccination rates have not yet recovered to pre-pandemic levels. About 67 million children missed routine immunizations during COVID-19, and preventable diseases like measles and polio are rising again.',
        hint:'"Vaccines" and "health" are the keys. Also think about inequality — it hits poorer countries harder.',
        fc:'Perfect! Health (3), Poverty (1), Inequality (10) and Partnerships (17) — well connected!',
        fp:'Health (3) is a must. Also think about the inequality angle.',
        fm:'Which SDG matches "vaccination"? Find the one about health.',
        lc:'Looking after your own health is the start of being a global citizen.',
        bonus:'Check your immunization record with your parents today.',
      },
      ja: {
        source:'UNICEF', title:'コロナ後、子どものワクチン接種率がまだ回復せず',
        body:'ユニセフとWHOは、コロナ後も世界の子どものワクチン接種率がパンデミック前の水準まで回復していないと発表しました。約6,700万人の子どもが定期接種を逃しており、はしかやポリオなど予防可能な病気が再び増えています。',
        hint:'「ワクチン」と「健康」が鍵。貧しい国でより深刻な不平等の面も考えてみよう。',
        fc:'完璧!健康(3)、貧困(1)、不平等(10)、協力(17)までつなげたね!',
        fp:'健康(3)は必ず。不平等の側面も一緒に考えよう。',
        fm:'「ワクチン」はどのSDGと関わる?健康の目標を探してみよう。',
        lc:'自分の健康を大切にすることが、世界市民意識のはじまりだよ。',
        bonus:'今日、自分の予防接種の記録を保護者と一緒に確認してみよう。',
      },
    },
  },
  {
    correct: [13,7,17,11],
    tags: { ko:['기후변화','지구온난화','파리협정','WMO'], en:['climate','warming','Paris Agreement','WMO'], ja:['気候変動','温暖化','パリ協定','WMO'] },
    url: 'https://news.un.org/en/story/2024/11/1156789',
    i18n: {
      ko: {
        source:'UNDP', title:'지구 평균 기온, 산업화 이전 대비 1.5°C 첫 돌파',
        body:'세계기상기구(WMO)는 2024년이 관측 역사상 지구 평균 기온이 산업화 이전 수준보다 1.5°C 이상 높아진 첫 번째 해가 될 가능성이 높다고 발표했습니다. 이상 폭염, 초강력 태풍, 전례 없는 산불이 이를 뒷받침합니다. 파리협정 목표 달성을 위한 즉각적인 온실가스 감축이 촉구되고 있습니다.',
        hint:'기후변화 관련 SDG와 에너지 전환 관련 SDG를 함께 찾아보세요.',
        fc:'탁월해요! 기후행동(13), 청정에너지(7), 국제 협력(17), 지속가능 도시(11)까지 완벽해요!',
        fp:'기후행동(13)은 핵심이에요. 에너지 관련 SDG도 함께 생각해보세요.',
        fm:'"기온 상승"과 "기후"에서 SDG를 찾고, 에너지 문제와도 연결해보세요.',
        lc:'석탄 대신 태양광·풍력 전기를 쓰려는 노력이 지구 온도를 낮추는 데 도움이 돼요.',
        bonus:'오늘 에어컨이나 히터 온도를 1도 조절하고, 가족에게 기후변화와 연결해서 설명해보세요.',
      },
      en: {
        source:'UNDP', title:'Global temperature passes 1.5°C above pre-industrial for the first time',
        body:'The World Meteorological Organization (WMO) reports 2024 is likely to be the first year in recorded history where the global average temperature is more than 1.5°C above pre-industrial levels. Heatwaves, super typhoons and unprecedented wildfires support this. Immediate emission cuts are urgently needed to meet the Paris Agreement goal.',
        hint:'Look for the climate SDG and the SDG about clean energy together.',
        fc:'Outstanding! Climate Action (13), Clean Energy (7), Partnerships (17) and Sustainable Cities (11) — perfect!',
        fp:'Climate Action (13) is the core. Also think about the energy SDG.',
        fm:'Find the SDG behind "rising temperature", then connect it to energy.',
        lc:'Switching from coal to solar or wind power really helps cool the planet.',
        bonus:'Change your AC or heater by 1°C today, and explain to your family how it connects to climate change.',
      },
      ja: {
        source:'UNDP', title:'地球の平均気温、産業革命前比1.5°Cを初めて超える',
        body:'世界気象機関(WMO)は、2024年が観測史上初めて地球の平均気温が産業革命前を1.5°C以上上回る年になる可能性が高いと発表しました。猛暑、超大型台風、前例のない山火事がそれを裏付けています。パリ協定の目標達成に向けた即時の温室効果ガス削減が求められています。',
        hint:'気候変動に関わるSDGと、エネルギー転換に関わるSDGを一緒に探そう。',
        fc:'素晴らしい!気候行動(13)、クリーンエネルギー(7)、協力(17)、持続可能な都市(11)まで完璧!',
        fp:'気候行動(13)が中心。エネルギーのSDGも一緒に考えよう。',
        fm:'「気温上昇」「気候」からSDGを探し、エネルギー問題とも結びつけよう。',
        lc:'石炭の代わりに太陽光や風力の電気を使う取り組みが、地球の気温を下げる助けになるよ。',
        bonus:'今日、エアコンや暖房の温度を1度だけ調整して、家族に気候変動とのつながりを説明してみよう。',
      },
    },
  },

  // ─── 추가 기사 12개 (2025년 최신 뉴스 기반, 한국어) ───
  {
    source: 'UN뉴스',
    title: '세계 어린이 5명 중 1명, 여전히 극심한 빈곤 속에 살아',
    body: '유니세프가 2025년 세계 어린이 현황 보고서를 통해 전 세계 저·중소득 국가 어린이 4억 1700만 명이 교육, 건강, 영양, 위생, 주거 중 두 가지 이상을 충족하지 못하는 다차원적 빈곤 상태에 있다고 밝혔습니다. 분쟁, 기후 위기, 기술 격차, 원조 삭감이 복합적으로 작용해 빈곤 탈출을 가로막고 있습니다. 특히 사하라 이남 아프리카와 남아시아 어린이들이 가장 큰 영향을 받고 있습니다.',
    tags: ['어린이빈곤', '유니세프', '다차원빈곤', '2025'],
    url: 'https://www.unicef.org/press-releases/more-400-million-children-globally-live-poverty-missing-out-least-two-daily-needs',
    correct: [1, 2, 3, 4],
    hint: '빈곤, 건강, 교육, 영양 등 여러 문제가 동시에 나타나요. 각각 어떤 SDG와 연결될까요?',
    fc: '완벽해요! 빈곤(SDG 1), 기아(SDG 2), 건강(SDG 3), 교육(SDG 4)이 모두 연결된 복합적인 문제예요. 어린이 빈곤이 얼마나 많은 SDGs와 동시에 얽혀 있는지 잘 파악했어요!',
    fp: '잘 찾았어요! 빈곤(SDG 1)은 찾았나요? 빈곤한 어린이들은 건강(SDG 3)과 교육(SDG 4)도 함께 박탈당해요. 여러 문제가 동시에 연결됩니다.',
    fm: '"빈곤"이라는 단어에서 SDG 1을 찾아보세요. 그리고 빈곤한 아이들이 어떤 것들을 못 누리는지 — 밥, 병원, 학교 — 를 SDG 번호와 연결해보세요.',
    lc: '우리가 학교에 다니고, 밥을 먹고, 병원에 갈 수 있다는 것이 당연한 게 아니에요. 이런 것들이 동시에 없는 어린이들을 위해 국제 원조 단체에 관심 갖는 것도 세계시민 행동이에요.',
    bonus: '오늘 저녁 밥을 먹으면서 "오늘 밥을 못 먹은 어린이들"을 한 번만 생각해보고, 음식을 소중히 여겨보세요.',
  },
  {
    source: 'UN뉴스',
    title: 'COP30 기후회의, 화석연료 퇴출 로드맵 합의 없이 마무리',
    body: '브라질 벨렝에서 열린 제30차 유엔기후변화협약 당사국총회(COP30)가 2025년 11월 마무리됐습니다. 기후 재원 1조 3천억 달러 조성 목표는 합의했지만, 화석연료 단계적 퇴출과 산림 벌채 중단 로드맵은 일부 국가의 반대로 끝내 포함되지 못했습니다. 유엔 사무총장은 "기후 위기가 가속화되는 상황에서 더 강한 행동이 필요하다"고 촉구했습니다.',
    tags: ['COP30', '기후협약', '화석연료', '벨렝'],
    url: 'https://news.un.org/en/story/2025/11/1166433',
    correct: [13, 7, 17, 15],
    hint: '기후회의와 직접 연결된 SDG, 에너지 전환, 국제 협력, 산림 보호와 관련된 목표를 찾아보세요.',
    fc: '훌륭해요! 기후행동(SDG 13)이 핵심이고, 화석연료 대신 청정에너지(SDG 7)로의 전환, 각국 협력(SDG 17), 산림 보호(SDG 15)까지 완벽하게 연결했어요!',
    fp: '기후행동(SDG 13)은 반드시 포함해야 해요. "화석연료 퇴출"은 어떤 에너지로 바꿔야 한다는 걸까요? 그 에너지와 관련된 SDG도 찾아보세요.',
    fm: '"기후회의"라는 단어에서 기후와 관련된 SDG를 찾아보세요. 화석연료 대신 쓸 수 있는 에너지, 숲 보호도 각각 SDG가 있어요.',
    lc: '우리가 전기를 아끼거나 대중교통을 이용하는 것이 화석연료 사용을 줄이는 작은 실천이에요. 세계 정상들이 합의하지 못한 일을 우리 각자가 먼저 시작할 수 있어요.',
    bonus: '오늘 집에서 이동할 때 자동차 대신 걷기, 자전거, 버스 중 하나를 선택해보고 그 이유를 가족에게 말해보세요.',
  },
  {
    source: 'UNICEF',
    title: '위기 속 학교 밖 어린이 2억 3400만 명, 역대 최고',
    body: '유니세프와 교육재건기금(ECW)의 2025년 보고서에 따르면 분쟁·재난·기후위기 등으로 교육이 필요한 위기 상황의 어린이가 2억 3400만 명에 달해 역대 최고를 기록했습니다. 이 중 8500만 명은 아예 학교에 다니지 못하고 있으며, 학교에 다니더라도 위기 상황의 어린이 5명 중 1명만이 기초 읽기 능력을 갖추고 있습니다. 난민·장애 어린이·여아가 가장 큰 피해를 보고 있습니다.',
    tags: ['교육위기', '난민', '분쟁', '학교밖청소년'],
    url: 'https://www.educationcannotwait.org/global-estimates-2025-update',
    correct: [4, 16, 10, 1],
    hint: '학교에 못 가는 어린이들과 관련된 교육 SDG와, 그 원인인 분쟁·불평등 관련 SDG를 찾아보세요.',
    fc: '완벽해요! 교육(SDG 4)과 평화(SDG 16)가 핵심이고, 난민·장애·여아 등 불평등(SDG 10), 그리고 빈곤(SDG 1)과의 연결도 훌륭해요!',
    fp: '교육(SDG 4)은 필수예요! 어린이들이 학교에 못 가는 이유가 "분쟁"이라는 점에서 또 다른 SDG도 찾아보세요.',
    fm: '"학교 밖 어린이"에서 교육 관련 SDG를 찾고, 왜 이런 일이 생기는지 — 전쟁, 재난 — 원인과 관련된 SDG도 연결해보세요.',
    lc: '우리가 매일 학교에 가는 것이 전 세계 2억 명 이상의 어린이들에게는 꿈같은 일이에요. 오늘 배움에 감사하고 최선을 다하는 것도 SDG 4 실천이에요.',
    bonus: '오늘 수업에서 집중이 어렵다고 느낄 때, 학교조차 다닐 수 없는 친구들을 떠올려보고 다시 한 번 집중해보세요.',
  },
  {
    source: 'UNEP',
    title: '아마존 열대우림 벌채, COP30에서도 중단 합의 실패',
    body: '2025년 11월 브라질에서 열린 COP30에서 아마존 열대우림 벌채를 2030년까지 중단하는 로드맵 합의에 실패했습니다. "지구의 허파"로 불리는 아마존은 지구 온난화를 완화하는 핵심 탄소 흡수원이지만, 농업·자원 개발을 위한 벌채가 계속되고 있습니다. 환경단체들은 이번 결과를 강하게 비판하며 각국 정부의 즉각적인 행동을 촉구했습니다.',
    tags: ['아마존', '산림벌채', 'COP30', '탄소흡수'],
    url: 'https://www.unep.org/news-and-stories/story/six-issues-will-dominate-cop30',
    correct: [15, 13, 17, 2],
    hint: '"숲"과 직접 관련된 SDG, 기후변화와의 관계, 식량 생산을 위한 벌채와 관련된 SDG를 찾아보세요.',
    fc: '탁월해요! 육상생태계(SDG 15)가 핵심이고, 산림 파괴가 기후변화(SDG 13)를 악화시키며, 농업 목적 벌채는 기아(SDG 2), 국제 협력(SDG 17) 부재도 잘 연결했어요!',
    fp: '육상생태계(SDG 15)와 기후행동(SDG 13)은 꼭 포함해야 해요. 아마존 벌채가 왜 일어나는지 — 농업과 식량 — 와 연결된 SDG도 찾아보세요.',
    fm: '"열대우림"과 "벌채"에서 숲·생태계와 관련된 SDG를 찾아보세요. 숲이 줄면 기후에 어떤 영향을 미칠까요?',
    lc: '우리가 소고기를 덜 먹거나 종이를 아끼는 것이 아마존 벌채를 줄이는 데 도움이 돼요. 소를 키우기 위해 숲을 태우는 것이 지구 반대편 우리와도 연결되어 있어요.',
    bonus: '오늘 종이를 한 장이라도 아껴 쓰고, 왜 종이를 아껴야 하는지 나만의 이유를 한 문장으로 써보세요.',
  },
  {
    source: 'UN뉴스',
    title: '전 세계 어린이 4명 중 3명, 극단적 기후 위험에 노출',
    body: '2025년 유니세프 보고서에 따르면 전 세계 어린이의 약 75%가 매년 폭염, 홍수, 가뭄 등 하나 이상의 극단적 기후 위험에 노출되어 있습니다. 기후 위험과 빈곤은 악순환을 형성해, 가난한 가정의 어린이일수록 기후 재해에 더 취약하고 피해 복구도 어렵습니다. 기후변화에 가장 적게 기여한 나라들이 오히려 가장 큰 피해를 받고 있다는 점에서 불공평한 문제이기도 합니다.',
    tags: ['기후위기', '어린이', '폭염', '불평등'],
    url: 'https://www.unicef.org/reports/state-of-worlds-children/2025',
    correct: [13, 1, 10, 3],
    hint: '기후변화와 직접 관련된 SDG, 가난한 나라가 더 큰 피해를 받는 불평등 측면도 생각해보세요.',
    fc: '완벽해요! 기후행동(SDG 13)이 핵심이고, 빈곤(SDG 1)과 기후의 악순환, 불평등(SDG 10), 건강(SDG 3)까지 연결한 깊이 있는 분석이에요!',
    fp: '기후행동(SDG 13)은 꼭 포함해야 해요. 기후 피해가 가난한 나라에 더 크게 온다는 점에서 불평등(SDG 10)도 생각해보세요.',
    fm: '"기후 위험"에서 SDG 13을 찾아보세요. 그리고 왜 가난한 나라 어린이들이 더 큰 피해를 받는지도 생각해봐요.',
    lc: '우리나라도 최근 폭염과 집중호우가 늘고 있어요. 에너지를 아끼고 쓰레기를 줄이는 것이 지구 반대편 어린이들을 지키는 행동과 연결돼요.',
    bonus: '오늘 날씨를 관찰하고, 최근 1년간 우리 동네에서 느낀 이상한 날씨를 하나 떠올려 노트에 적어보세요.',
  },
  {
    source: 'WHO',
    title: '전 세계 청소년 7명 중 1명, 정신건강 문제 겪고 있어',
    body: '세계보건기구(WHO)에 따르면 10~19세 청소년 약 7명 중 1명이 우울증, 불안장애 등 정신건강 문제를 경험하고 있습니다. 분쟁, 빈곤, 기후 불안, 소셜미디어 과의존이 주요 원인으로 꼽히며, 특히 분쟁 지역 어린이들의 경우 정신건강 지원이 절실하지만 서비스가 극히 부족합니다. WHO는 학교 기반 정신건강 프로그램 확대를 각국에 촉구하고 있습니다.',
    tags: ['청소년정신건강', 'WHO', '우울증', '불안'],
    url: 'https://www.who.int/news/item/mental-health-adolescents',
    correct: [3, 4, 10, 16],
    hint: '건강과 직접 관련된 SDG, 학교 기반 프로그램은 교육과 연결, 서비스 접근 불평등도 생각해보세요.',
    fc: '훌륭해요! 건강(SDG 3)이 핵심이고, 학교 기반 지원(SDG 4), 서비스 불평등(SDG 10), 분쟁 지역 어린이 문제(SDG 16)까지 연결한 완벽한 분석이에요!',
    fp: '건강(SDG 3)은 필수예요! 학교에서 정신건강을 다룬다는 점에서 교육(SDG 4)도 연결돼요. 분쟁 지역 어린이들이 더 취약하다는 불평등도 생각해보세요.',
    fm: '"정신건강 문제"에서 건강과 관련된 SDG를 찾아보세요. 학교에서 프로그램을 만든다면 어떤 SDG와도 연결될까요?',
    lc: '우리 주변 친구들도 스트레스와 불안을 느낄 수 있어요. 먼저 인사하고 이야기를 들어주는 것도 정신건강을 지키는 세계시민 행동이에요.',
    bonus: '오늘 하루 동안 힘들어 보이는 친구에게 "요즘 어때?"라고 한 번 물어봐요. 작은 관심이 큰 힘이 돼요.',
  },
  {
    source: 'UNICEF',
    title: '디지털 격차, 저소득국 어린이 교육 불평등 심화시켜',
    body: '유니세프 2025년 보고서에 따르면 저소득 국가와 고소득 국가 간 디지털 격차가 교육 불평등을 더욱 심화시키고 있습니다. 저소득 국가 어린이의 90% 이상이 기본적인 디지털 기기나 인터넷에 접근하지 못하는 반면, 고소득 국가에서는 AI 기반 학습 도구가 빠르게 도입되고 있습니다. 이 격차가 해소되지 않으면 2030년 SDGs 목표 달성이 어렵다고 경고했습니다.',
    tags: ['디지털격차', '교육불평등', 'AI교육', '기술'],
    url: 'https://www.unicef.org/sustainable-development-goals',
    correct: [4, 10, 9, 17],
    hint: '교육 불평등과 디지털 기술 접근, 국가 간 불평등, 기술 혁신 관련 SDG를 찾아보세요.',
    fc: '탁월해요! 교육(SDG 4)과 불평등(SDG 10)이 핵심이고, 기술·인프라 격차(SDG 9), 국제 협력(SDG 17)까지 완벽하게 연결했어요!',
    fp: '교육(SDG 4)과 불평등(SDG 10)은 잘 찾았어요! "디지털 기기와 인터넷"은 어떤 기술·인프라 관련 SDG와 연결될까요?',
    fm: '"디지털 격차"에서 교육 관련 SDG와 나라 간 차이 관련 SDG를 찾아보세요. 스마트폰과 인터넷은 어떤 SDG와 연결될까요?',
    lc: '우리가 당연하게 쓰는 스마트폰과 인터넷이 없는 어린이들이 전 세계에 수억 명이에요. AI 기술을 배울 기회조차 없는 친구들을 생각해봐요.',
    bonus: '오늘 스마트폰이나 컴퓨터를 사용할 때, "이 기기가 없다면 어떨까?"를 30초만 생각해보세요.',
  },
  {
    source: 'UNEP',
    title: '산호초 절반, 기후변화로 백화 현상 위기',
    body: '유엔환경계획(UNEP)과 국제산호초이니셔티브는 2025년 보고서를 통해 전 세계 산호초의 약 절반이 해수 온도 상승으로 인한 산호 백화 현상으로 심각한 위기에 처했다고 경고했습니다. 산호초는 전 세계 해양 생물의 25%가 의존하는 생태계이며, 연간 약 3천억 달러의 수산업·관광업 가치를 창출합니다. 탄소 배출 감축 없이는 2050년까지 90% 이상이 사라질 수 있다고 전망했습니다.',
    tags: ['산호초', '해양온난화', '생태계', '백화현상'],
    url: 'https://www.unep.org/events/conference/unep-2025-un-ocean-conference',
    correct: [14, 13, 17, 2],
    hint: '"바다"와 직접 관련된 SDG, 해수 온도를 높이는 원인, 수산업과 식량도 생각해보세요.',
    fc: '완벽해요! 해양생태계(SDG 14)가 핵심이고, 기후변화(SDG 13)가 원인, 국제 협력(SDG 17), 수산업 감소로 인한 식량(SDG 2) 문제까지 훌륭하게 연결했어요!',
    fp: '해양생태계(SDG 14)는 꼭 포함해야 해요! 산호초가 사라지는 원인인 기후변화(SDG 13)도 함께 찾아보세요.',
    fm: '"산호초"와 "해양"에서 바다 관련 SDG를 찾아보세요. 산호초가 왜 사라지는지 그 원인도 SDG와 연결해봐요.',
    lc: '우리가 여름에 에어컨을 하나 덜 켜는 것이 탄소 배출을 줄여 바다 온도를 낮추는 데 도움이 돼요. 지구 반대편 바닷속 생물들과 연결된 행동이에요.',
    bonus: '오늘 산호초 사진을 한 번 검색해보고, 산호 백화 현상 전후 사진을 비교해보세요. 느낀 점을 한 문장으로 적어보세요.',
  },
  {
    source: 'UN뉴스',
    title: '전 세계 음식물 쓰레기, 매년 10억 톤 — 기아 인구는 8억 명',
    body: '유엔환경계획(UNEP)의 2025년 식품 폐기물 지수 보고서에 따르면 전 세계에서 매년 약 10억 톤의 음식이 버려지고 있습니다. 이는 생산된 식품의 약 5분의 1에 해당합니다. 반면 전 세계 약 8억 명이 기아 상태에 있어 충격적인 대비를 이룹니다. 음식물 쓰레기는 전 세계 온실가스 배출의 약 8~10%를 차지해 기후변화에도 심각한 영향을 미칩니다.',
    tags: ['음식물쓰레기', '식량낭비', '기아', 'UNEP'],
    url: 'https://www.unep.org/resources/report/unep-food-waste-index-report-2024',
    correct: [12, 2, 13, 17],
    hint: '"음식물 쓰레기"는 소비와 관련된 SDG와 연결돼요. 기아 문제, 온실가스 배출도 각각 어떤 SDG인지 생각해보세요.',
    fc: '훌륭해요! 책임있는 소비(SDG 12)가 핵심이고, 기아(SDG 2), 기후변화(SDG 13), 국제 협력(SDG 17)까지 완벽하게 연결했어요!',
    fp: '음식물 쓰레기에서 소비 관련 SDG를 찾았나요? 버려지는 음식이 기아(SDG 2)와 기후변화(SDG 13)에도 영향을 미쳐요.',
    fm: '"음식을 버린다"는 것은 어떤 소비 관련 SDG와 연결될까요? 또 굶는 사람이 8억 명인데 음식을 10억 톤 버린다면, 어떤 문제가 보이나요?',
    lc: '우리 집에서 버려지는 음식을 한 가지만 줄여도 기아와 기후변화 모두에 도움이 돼요. 냉장고 속 재료를 확인하고 필요한 만큼만 사는 습관이 세계를 바꿔요.',
    bonus: '오늘 집 냉장고를 열어 버려질 것 같은 음식 하나를 찾아 오늘 안에 먹어보세요. 부모님께 식품 낭비를 줄이자고 제안해봐요.',
  },
  {
    source: 'UNICEF',
    title: '시리아·수단 등 분쟁 지역 어린이, 심각한 정신적 외상 겪어',
    body: '유니세프는 2025년 시리아, 수단, 가자지구 등 분쟁 지역에서 폭력을 목격하거나 직접 경험한 어린이 수천만 명이 심각한 정신적 외상(트라우마)을 겪고 있다고 보고했습니다. 유니세프 지원 팀은 안전한 공간에서 그림 그리기, 놀이 치료 등 심리·사회적 지원 프로그램을 운영하고 있습니다. 그러나 수요에 비해 지원 인력과 재원이 턱없이 부족한 실정입니다.',
    tags: ['분쟁', '트라우마', '정신건강', '어린이보호'],
    url: 'https://www.unicefusa.org/stories/6-ways-unicef-supports-youth-mental-health',
    correct: [16, 3, 1, 4],
    hint: '전쟁·폭력과 관련된 SDG, 정신건강 피해, 빈곤과 교육 기회 박탈도 함께 생각해보세요.',
    fc: '완벽해요! 평화와 정의(SDG 16)가 핵심이고, 정신건강(SDG 3), 빈곤(SDG 1), 교육 기회 박탈(SDG 4)까지 훌륭하게 연결했어요!',
    fp: '평화와 정의(SDG 16)는 꼭 포함해야 해요! 분쟁으로 인한 정신건강 피해(SDG 3)도 연결해보세요.',
    fm: '"분쟁 지역"과 "폭력"에서 평화 관련 SDG를 찾아보세요. 그리고 트라우마는 건강과 관련된 SDG와도 연결돼요.',
    lc: '우리가 안전하게 학교에 다니고 친구들과 놀 수 있는 것이 얼마나 소중한지 생각해보세요. 평화가 없으면 다른 모든 SDGs도 이루기 어려워요.',
    bonus: '오늘 하루 "평화"라는 단어를 생각하며, 내가 학교에서 누군가와 다투지 않고 사이좋게 지내는 작은 평화를 실천해보세요.',
  },
  {
    source: 'UNDP',
    title: '재생에너지, 처음으로 전 세계 전력 생산의 30% 돌파',
    body: '국제에너지기구(IEA)에 따르면 2025년 태양광·풍력을 중심으로 한 재생에너지가 처음으로 전 세계 전력 생산의 30%를 넘어섰습니다. 태양광 발전은 현재 지구상에서 가장 저렴한 전력원이 됐으며, 특히 개발도상국에서 빠르게 확산되고 있습니다. 그러나 아프리카와 남아시아 일부 지역은 여전히 전기 접근이 어려운 상황입니다.',
    tags: ['재생에너지', '태양광', '풍력', 'IEA'],
    url: 'https://www.iea.org/reports/renewables-2025',
    correct: [7, 13, 9, 10],
    hint: '재생에너지와 직접 관련된 SDG, 기후변화 완화 효과, 기술 혁신, 에너지 접근 불평등도 생각해보세요.',
    fc: '탁월해요! 청정에너지(SDG 7)가 핵심이고, 기후변화 완화(SDG 13), 기술 혁신(SDG 9), 에너지 접근 불평등(SDG 10)까지 완벽하게 연결했어요!',
    fp: '청정에너지(SDG 7)는 꼭 포함해야 해요! 재생에너지가 늘면 기후변화(SDG 13)에도 도움이 돼요. 아직 전기가 없는 지역의 불평등도 생각해보세요.',
    fm: '"재생에너지"와 "태양광"에서 에너지와 관련된 SDG를 찾아보세요. 화석연료를 줄이면 어떤 효과가 생기는지도 연결해봐요.',
    lc: '우리 학교나 집 옥상에 태양광 패널이 있다면 재생에너지를 직접 사용하는 거예요. 에너지 절약도 재생에너지 확산을 돕는 방법이에요.',
    bonus: '집에서 쓰는 전기가 어떻게 만들어지는지 부모님께 물어보고, 태양광 발전에 대해 함께 이야기해보세요.',
  },
  {
    source: 'UN뉴스',
    title: '전 세계 도시 인구 절반 돌파 — 급격한 도시화로 불평등 심화',
    body: '유엔 인구기금(UNFPA) 2025년 보고서에 따르면 전 세계 인구의 56%가 도시에 살고 있으며, 2050년에는 70%에 달할 전망입니다. 특히 저소득 국가에서 도시화가 급격히 진행되면서 슬럼가 확산, 교통 혼잡, 대기오염, 주거 부족 문제가 심각해지고 있습니다. 반면 잘 계획된 도시는 에너지 효율과 삶의 질을 동시에 높일 수 있다는 점에서 지속가능한 도시 설계가 중요해졌습니다.',
    tags: ['도시화', '슬럼', '대기오염', '주거'],
    url: 'https://www.un.org/sustainabledevelopment/cities/',
    correct: [11, 10, 13, 3],
    hint: '"도시"와 직접 관련된 SDG, 슬럼가의 불평등, 대기오염과 기후변화, 건강 영향도 생각해보세요.',
    fc: '훌륭해요! 지속가능한 도시(SDG 11)가 핵심이고, 도시 내 불평등(SDG 10), 도시 온실가스 배출(SDG 13), 대기오염으로 인한 건강(SDG 3)까지 완벽하게 연결했어요!',
    fp: '지속가능한 도시(SDG 11)는 꼭 포함해야 해요! 슬럼가가 늘어나는 것은 불평등(SDG 10)과도 연결돼요. 대기오염이 건강에 미치는 영향도 생각해보세요.',
    fm: '"도시"와 관련된 SDG를 찾아보세요. 슬럼가가 늘고 대기오염이 심해지면 어떤 SDGs 문제가 생기는지도 연결해봐요.',
    lc: '우리 동네가 살기 좋은 도시가 되려면 어떤 게 필요할까요? 쓰레기를 버리지 않고, 대중교통을 이용하는 것도 지속가능한 도시를 만드는 작은 실천이에요.',
    bonus: '오늘 우리 동네를 걸으면서 더 살기 좋은 동네가 되려면 무엇이 필요한지 한 가지를 생각해보고, 그 이유를 적어보세요.',
  },
];
