// SDG color palette (UN official)
const SDG_COLORS = [
  '#E5243B','#DDA63A','#4C9F38','#C5192D','#FF3A21','#26BDE2','#FCC30B','#A21942',
  '#FD6925','#DD1367','#FD9D24','#BF8B2E','#3F7E44','#0A97D9','#56C02B','#00689D','#19486A',
];

// News DB: correct SDGs apply across languages; localized text per language.
const NEWS_DB = [
  {
    correct: [2,1,13,17],
    tags: { ko:['식량','기아','아프리카','FAO'], en:['food','hunger','Africa','FAO'], ja:['食料','飢餓','アフリカ','FAO'] },
    url: 'https://news.un.org/en/story/2024/07/1152236',
    i18n: {
      ko: {
        source:'UN뉴스', title:'전 세계 7억 3천만 명이 여전히 극심한 굶주림에 시달려',
        body:'유엔 식량농업기구(FAO)는 2024년 보고서에서 전 세계 약 7억 3천만 명이 만성적인 식량 부족 상태에 있다고 밝혔습니다. 특히 사하라 이남 아프리카와 남아시아에서 상황이 심각하며, 기후 변화와 분쟁이 주요 원인으로 꼽힙니다. 어린이 영양실조도 여전히 심각한 문제로 남아 있습니다.',
        hint:'음식이 부족한 사람들과 관련된 목표, 그리고 그 원인인 기후와 가난을 함께 생각해보세요.',
        fc:'훌륭해요! 기아(SDG 2)가 핵심이지만, 빈곤(SDG 1), 기후변화(SDG 13), 국제 협력(SDG 17)과도 깊이 연결돼요.',
        fp:'좋은 시작이에요! 기아(SDG 2)는 잘 찾았어요. 빈곤(SDG 1)과 기후변화(SDG 13)도 함께 생각해보세요.',
        fm:'기사에서 "굶주림"이라는 단어를 주목해보세요. 식량 문제와 기후·빈곤의 관계를 떠올려 봐요.',
        lc:'우리가 음식을 낭비하지 않고 급식을 남기지 않는 것도 SDG 2를 실천하는 거예요.',
        bonus:'오늘 급식에서 음식을 하나도 남기지 않아 보세요. 먹지 못하는 친구들을 생각하며 감사히 먹는 것도 세계시민 행동이에요.',
      },
      en: {
        source:'UN News', title:'730 million people still face severe hunger worldwide',
        body:'In its 2024 report, the UN Food and Agriculture Organization (FAO) said about 730 million people remain chronically food-insecure. The situation is most severe in sub-Saharan Africa and South Asia, with climate change and conflict driving the crisis. Child malnutrition remains a serious problem.',
        hint:'Think about the goal directly linked to people without enough food, plus the climate and poverty causes behind it.',
        fc:'Excellent! Zero Hunger (SDG 2) is the core, but Poverty (1), Climate Action (13) and Partnerships (17) are deeply connected too.',
        fp:'Good start! You spotted Hunger (SDG 2). Try also Poverty (1) and Climate Action (13).',
        fm:'Notice the word "hunger" in the article — then think about how climate and poverty cause it.',
        lc:'Not wasting food at school lunch is already a small act for SDG 2.',
        bonus:'Try to leave no food on your plate today. Eating with gratitude for those who cannot is itself a global-citizen action.',
      },
      ja: {
        source:'UNニュース', title:'世界で7億3千万人が依然として深刻な飢餓に',
        body:'国連食糧農業機関(FAO)は2024年の報告書で、世界で約7億3千万人が慢性的な食料不足の状態にあると発表しました。特にサハラ以南のアフリカと南アジアで状況が深刻で、気候変動と紛争が主な原因とされています。子どもの栄養失調も依然として深刻です。',
        hint:'食べ物が足りない人々に直結する目標と、その原因である気候・貧困を一緒に考えてみよう。',
        fc:'素晴らしい!飢餓(SDG 2)が中心だけど、貧困(1)、気候変動(13)、パートナーシップ(17)とも深くつながっているよ。',
        fp:'いいスタート!飢餓(SDG 2)はバッチリ。貧困(1)と気候変動(13)も一緒に考えてみよう。',
        fm:'記事の「飢餓」という言葉に注目。気候や貧困との関係も考えてみよう。',
        lc:'給食を残さず食べることも、SDG 2の実践のひとつだよ。',
        bonus:'今日の給食を残さず食べてみよう。食べられない人を想い、感謝して食べることも世界市民の行動だよ。',
      },
    },
  },
  {
    correct: [13,3,4,1],
    tags: { ko:['기후변화','어린이','폭염','홍수'], en:['climate','children','heatwave','flood'], ja:['気候変動','子ども','猛暑','洪水'] },
    url: 'https://www.unicef.org/press-releases/1-billion-children',
    i18n: {
      ko: {
        source:'유니세프', title:'기후변화로 어린이 10억 명이 위험에 처해 있어',
        body:'유니세프는 기후변화로 인해 전 세계 어린이 약 10억 명이 폭염, 홍수, 사이클론 등 극단적 기상 현상에 매우 취약한 환경에서 살고 있다고 경고했습니다. 특히 남아시아와 사하라 이남 아프리카 지역 어린이들이 가장 큰 위험에 노출되어 있으며, 이는 교육 기회 박탈과 건강 문제로 이어지고 있습니다.',
        hint:'기후 위기와 직접 관련된 목표, 그리고 건강·교육에 미치는 영향을 함께 떠올려 봐요.',
        fc:'완벽해요! 기후행동(13), 건강(3), 교육(4), 빈곤(1)까지 연결한 뛰어난 분석이에요!',
        fp:'기후행동(13)은 필수예요. 건강(3)과 학교생활(4)에도 영향을 미쳐요.',
        fm:'"기후변화"에서 SDG를 찾고, 건강과 교육에 어떤 영향을 주는지도 연결해보세요.',
        lc:'전기를 아끼고 일회용품을 줄이는 것이 먼 나라 어린이들의 미래와 연결돼 있어요.',
        bonus:'오늘 사용하지 않는 전등과 전자기기 플러그를 뽑아보세요. 가족에게 이유를 설명해보면 더 좋아요.',
      },
      en: {
        source:'UNICEF', title:'One billion children at extreme risk from climate change',
        body:'UNICEF warns that about one billion children worldwide live in environments highly exposed to extreme weather such as heatwaves, floods and cyclones. Children in South Asia and sub-Saharan Africa face the highest risks, which also disrupt their schooling and health.',
        hint:'Start with the goal directly tied to climate, then think about the health and education impacts.',
        fc:'Perfect! Climate Action (13), Health (3), Education (4) and Poverty (1) — a brilliant connection!',
        fp:'Climate Action (13) is essential. It also affects Health (3) and Education (4).',
        fm:'Look for the SDG behind the words "climate change", then link it to health and school.',
        lc:'Saving electricity and cutting single-use items at home is linked to children\'s future across the world.',
        bonus:'Unplug lights and devices you are not using today. Bonus points if you explain why to your family.',
      },
      ja: {
        source:'UNICEF', title:'気候変動で10億人の子どもがリスクに',
        body:'ユニセフは、気候変動により世界で約10億人の子どもが、猛暑・洪水・サイクロンなど極端な気象現象に非常にさらされやすい環境で暮らしていると警告しました。特に南アジアやサハラ以南のアフリカの子どもたちが大きなリスクにさらされており、教育機会の喪失や健康問題にもつながっています。',
        hint:'気候危機に直結する目標と、健康・教育への影響を一緒に考えよう。',
        fc:'完璧!気候(13)、健康(3)、教育(4)、貧困(1)まで結びつけた素晴らしい分析!',
        fp:'気候行動(13)は必須。健康(3)と学校生活(4)にも影響するよ。',
        fm:'「気候変動」からSDGを探し、健康と教育への影響も結びつけてみよう。',
        lc:'電気を節約したり使い捨てを減らすことが、遠い国の子どもたちの未来とつながっているよ。',
        bonus:'今日、使っていない電気と家電のプラグを抜いてみよう。家族にも理由を説明できるとなおよし。',
      },
    },
  },
  {
    correct: [4,5,1,10],
    tags: { ko:['교육','여학생','성평등','유네스코'], en:['education','girls','equality','UNESCO'], ja:['教育','女子','ジェンダー','UNESCO'] },
    url: 'https://news.un.org/en/story/2024/03/1147712',
    i18n: {
      ko: {
        source:'UN뉴스', title:'전 세계 여학생 1억 2천만 명 학교 밖에 있어',
        body:'유네스코 보고서에 따르면 전 세계적으로 약 1억 2천만 명의 여학생이 학교에 다니지 못하고 있습니다. 빈곤, 조혼 문화, 성차별, 안전 문제 등이 주요 원인이며, 교육 격차는 취업 기회와 소득 불평등으로도 이어집니다.',
        hint:'학교에 못 가는 여학생들과 관련된 교육 목표와 성별 불평등 목표를 함께 찾아보세요.',
        fc:'훌륭해요! 교육(4)과 성평등(5)이 핵심이고, 빈곤(1)과 불평등(10)까지 연결했어요!',
        fp:'교육(4)은 찾았나요? "여학생"에서 성별 관련 SDG도 찾아보세요.',
        fm:'"여학생이 학교에 못 간다"에서 교육·성별 관련 SDG를 떠올려 봐요.',
        lc:'학교에서 열심히 배우는 것 자체가 SDG 4를 실천하는 거예요.',
        bonus:'오늘 수업에서 배운 내용 한 가지를 가족에게 가르쳐주세요. 배움을 나누는 것도 교육 나눔이에요.',
      },
      en: {
        source:'UN News', title:'120 million girls out of school worldwide',
        body:'According to a UNESCO report, about 120 million girls are out of school worldwide. Poverty, child marriage, gender discrimination and safety concerns are the main causes, and the education gap leads to wider gaps in jobs and income.',
        hint:'Pick the education goal first, then look for the goal about gender equality.',
        fc:'Excellent! Education (4) and Gender Equality (5) at the core, plus Poverty (1) and Inequality (10).',
        fp:'Did you spot Education (4)? "Girls" should also point to the gender-related SDG.',
        fm:'"Girls out of school" connects directly to education and gender SDGs.',
        lc:'Studying hard at school is, in itself, practicing SDG 4.',
        bonus:'Teach one thing you learned today to your family. Sharing knowledge is also an act of education.',
      },
      ja: {
        source:'UNニュース', title:'世界で1億2千万人の女子が学校に通えない',
        body:'ユネスコの報告書によると、世界で約1億2千万人の女子が学校に通えていません。貧困、早婚の慣習、性差別、安全の問題などが主な原因で、教育の格差は就業機会や所得の不平等にもつながります。',
        hint:'学校に通えない女子に関わる教育目標と、ジェンダー不平等の目標を一緒に探そう。',
        fc:'素晴らしい!教育(4)とジェンダー平等(5)が中心、貧困(1)・不平等(10)まで結びつけたね!',
        fp:'教育(4)は見つかった?「女子」からジェンダー関連のSDGも探してみよう。',
        fm:'「女子が学校に行けない」から、教育とジェンダーのSDGを思い出そう。',
        lc:'学校で一生懸命学ぶこと自体がSDG 4の実践になるよ。',
        bonus:'今日の授業で習ったことを1つ、家族に教えてみよう。学びを分かち合うのも教育のシェアだよ。',
      },
    },
  },
  {
    correct: [6,3,13,1],
    tags: { ko:['식수','위생','어린이','WHO'], en:['water','sanitation','children','WHO'], ja:['水','衛生','子ども','WHO'] },
    url: 'https://www.unicef.org/reports/water-under-fire',
    i18n: {
      ko: {
        source:'유니세프', title:'깨끗한 물 없이 생활하는 어린이 4억 5천만 명',
        body:'유니세프와 세계보건기구(WHO)의 공동 보고서에 따르면, 전 세계 4억 5천만 명의 어린이가 안전한 식수 없이 생활하고 있습니다. 오염된 물 사용으로 인한 설사병은 5세 미만 어린이 사망의 주요 원인 중 하나입니다. 기후변화로 인한 가뭄과 홍수가 상황을 악화시키고 있습니다.',
        hint:'"물"과 직접 관련된 SDG를 먼저 찾고, 오염된 물이 건강에 미치는 영향도 떠올려 보세요.',
        fc:'완벽해요! 깨끗한 물(6), 건강(3), 기후변화(13), 빈곤(1)까지 완벽히 연결했어요!',
        fp:'깨끗한 물(6)이 핵심이에요. 건강(3)도 함께 생각해보세요.',
        fm:'"깨끗한 물"을 SDGs에서 찾고, 오염된 물과 건강의 관계도 생각해보세요.',
        lc:'양치할 때 컵을 사용해 물을 절약해 보세요.',
        bonus:'오늘 물을 사용할 때마다 "이 물은 어디서 올까?"를 생각하고, 물 절약 방법 3가지를 적어보세요.',
      },
      en: {
        source:'UNICEF', title:'450 million children live without safe drinking water',
        body:'A joint UNICEF–WHO report finds 450 million children worldwide live without safe drinking water. Diarrhoea caused by contaminated water is among the leading causes of death for children under five. Climate-driven droughts and floods are making the situation worse.',
        hint:'Start with the SDG directly about "water", then think about its effect on health.',
        fc:'Perfect! Clean Water (6), Health (3), Climate (13) and Poverty (1) — beautifully connected!',
        fp:'Clean Water (6) is the core. Don\'t forget Health (3).',
        fm:'Find "clean water" in the SDGs, then connect dirty water to health.',
        lc:'Using a cup while brushing your teeth is a real way to save water.',
        bonus:'Every time you use water today, ask "where does this come from?" — then list three ways to save water.',
      },
      ja: {
        source:'UNICEF', title:'安全な水を使えない子ども4億5千万人',
        body:'ユニセフとWHOの共同報告書によると、世界で4億5千万人の子どもが安全な飲み水を利用できずに暮らしています。汚れた水による下痢は、5歳未満の子どもの死亡の主な原因の一つです。気候変動による干ばつや洪水が状況を悪化させています。',
        hint:'まず「水」に直結するSDGを探し、汚れた水が健康に与える影響も考えよう。',
        fc:'完璧!きれいな水(6)、健康(3)、気候(13)、貧困(1)までうまくつなげたね!',
        fp:'きれいな水(6)が中心。健康(3)も一緒に考えよう。',
        fm:'「きれいな水」をSDGsから探し、汚れた水と健康の関係も考えてみよう。',
        lc:'歯みがきのときコップを使うと、本当に水を節約できるよ。',
        bonus:'今日、水を使うたびに「この水はどこから?」と考え、節水の方法を3つ書き出してみよう。',
      },
    },
  },
  {
    correct: [14,12,17,3],
    tags: { ko:['플라스틱','해양오염','생태계','UNEP'], en:['plastic','ocean','ecosystem','UNEP'], ja:['プラスチック','海洋汚染','生態系','UNEP'] },
    url: 'https://www.unep.org/news-and-stories/press-release/plastic-pollution',
    i18n: {
      ko: {
        source:'UNDP', title:'해양 플라스틱 오염, 2040년까지 3배 증가 전망',
        body:'유엔환경계획(UNEP)은 현재 추세가 계속된다면 2040년까지 해양으로 유입되는 플라스틱 양이 지금의 3배에 달할 것이라고 경고했습니다. 매년 800만 톤 이상의 플라스틱이 바다로 흘러들어 해양 생태계를 파괴하고 먹이사슬을 통해 인간에게도 영향을 줍니다.',
        hint:'"바다"와 관련된 SDG와 플라스틱 소비 관련 목표를 함께 떠올려 보세요.',
        fc:'탁월해요! 해양(14), 책임있는 소비(12), 협력(17), 건강(3)까지 완벽해요!',
        fp:'해양생태계(14)는 꼭 포함해야 해요. 플라스틱을 줄이는 소비 관련 SDG도 찾아보세요.',
        fm:'"해양"에서 바다 관련 SDG를, 플라스틱 소비 습관에서 또 다른 SDG를 찾아보세요.',
        lc:'일회용 플라스틱 컵 하나를 덜 쓰는 것이 바다를 지키는 행동이에요.',
        bonus:'오늘 하루 일회용 플라스틱을 하나도 사용하지 않는 "플라스틱 프리 챌린지"에 도전해보세요.',
      },
      en: {
        source:'UNDP', title:'Ocean plastic pollution set to triple by 2040',
        body:'UNEP warns that if current trends continue, the amount of plastic flowing into the oceans will triple by 2040. Over 8 million tonnes of plastic enter the sea each year, destroying marine ecosystems and reaching humans through the food chain.',
        hint:'Look for the "ocean" SDG, and the goal about responsible consumption.',
        fc:'Outstanding! Life Below Water (14), Responsible Consumption (12), Partnerships (17) and Health (3) — perfect!',
        fp:'Life Below Water (14) is a must. Add the SDG about reducing consumption too.',
        fm:'Find the ocean SDG, then think about plastic habits and the consumption SDG.',
        lc:'Skipping one single-use plastic cup today is already a small act for the ocean.',
        bonus:'Try a one-day "plastic free" challenge — use zero single-use plastics today.',
      },
      ja: {
        source:'UNDP', title:'海洋プラスチック汚染、2040年までに3倍に',
        body:'国連環境計画(UNEP)は、現在の傾向が続けば2040年までに海に流れ込むプラスチックが現在の3倍になると警告しました。毎年800万トン以上のプラスチックが海に流れ込み、海洋生態系を破壊し、食物連鎖を通じて人間にも影響します。',
        hint:'「海」に関わるSDGと、プラスチック消費に関する目標を一緒に考えよう。',
        fc:'素晴らしい!海(14)、責任ある消費(12)、パートナーシップ(17)、健康(3)まで完璧!',
        fp:'海の生態系(14)は必ず含めよう。プラスチックを減らす消費のSDGも探してみて。',
        fm:'「海」から海のSDG、プラスチックの使い方から別のSDGを探してみよう。',
        lc:'使い捨てプラスチックのコップを1つ減らすことも、海を守る行動だよ。',
        bonus:'今日1日「プラスチックフリーチャレンジ」——使い捨てプラスチックを一切使わないことに挑戦しよう。',
      },
    },
  },
  {
    correct: [4,16,1,10],
    tags: { ko:['분쟁','교육','어린이','난민'], en:['conflict','education','children','refugees'], ja:['紛争','教育','子ども','難民'] },
    url: 'https://news.un.org/en/story/2024/09/1154321',
    i18n: {
      ko: {
        source:'UN뉴스', title:'분쟁 지역 어린이 4천만 명 교육 위기',
        body:'유엔은 현재 전 세계 분쟁 지역에서 약 4천만 명의 어린이가 학교 교육을 받지 못하고 있다고 발표했습니다. 우크라이나, 수단, 가자지구, 미얀마 등지에서 학교 시설이 파괴되거나 어린이들이 피란길에 오르면서 교육이 중단되고 있습니다.',
        hint:'전쟁·분쟁 관련 SDG와 교육 기회 박탈 관련 SDG를 함께 찾아보세요.',
        fc:'훌륭해요! 교육(4)과 평화(16)가 핵심이고, 빈곤(1)·불평등(10)까지 연결했어요!',
        fp:'교육(4)은 반드시 포함해야 해요. "분쟁 지역"에서 평화 관련 SDG도 찾아보세요.',
        fm:'"분쟁"과 "교육"이 두 핵심 단어예요. 각각 관련 SDG를 찾아봐요.',
        lc:'평화로운 환경에서 학교를 다닐 수 있다는 게 얼마나 소중한지 떠올려 보세요.',
        bonus:'학급에서 도움이 필요한 친구가 있는지 살펴보고, 오늘 한 명에게 먼저 말을 걸어보세요.',
      },
      en: {
        source:'UN News', title:'40 million children in conflict zones face education crisis',
        body:'The UN reports about 40 million children in conflict zones worldwide are missing school. In Ukraine, Sudan, Gaza, Myanmar and elsewhere, schools have been destroyed or families displaced, breaking children\'s education and risking a long-term cycle of poverty.',
        hint:'Look for the SDG about peace and the SDG about education together.',
        fc:'Excellent! Education (4) and Peace (16) at the core, plus Poverty (1) and Inequality (10).',
        fp:'Education (4) is a must. "Conflict zones" should also lead you to the peace SDG.',
        fm:'Two key words: "conflict" and "education". Find the SDG for each.',
        lc:'Being able to go to school in peace is something truly precious.',
        bonus:'Look for a classmate who needs help, and be the first to speak to them today.',
      },
      ja: {
        source:'UNニュース', title:'紛争地域の子ども4千万人が教育の危機に',
        body:'国連は、世界の紛争地域で約4千万人の子どもが学校に通えていないと発表しました。ウクライナ、スーダン、ガザ、ミャンマーなどで学校が破壊されたり、子どもたちが避難を余儀なくされたりして教育が中断しています。',
        hint:'戦争・紛争に関わるSDGと、教育の機会喪失に関わるSDGを一緒に探そう。',
        fc:'素晴らしい!教育(4)と平和(16)が中心、貧困(1)・不平等(10)もつなげられたね!',
        fp:'教育(4)は必ず。「紛争地域」から平和のSDGも探してみよう。',
        fm:'「紛争」と「教育」の2つがキーワード。それぞれのSDGを見つけよう。',
        lc:'平和な環境で学校に通えることがどんなに大切か、考えてみよう。',
        bonus:'クラスで助けが必要な友だちはいないかな?今日は1人に自分から声をかけてみよう。',
      },
    },
  },
  {
    correct: [3,1,10,17],
    tags: { ko:['백신','보건','어린이','코로나'], en:['vaccine','health','children','COVID'], ja:['ワクチン','保健','子ども','コロナ'] },
    url: 'https://www.unicef.org/press-releases/children-missed-vaccinations',
    i18n: {
      ko: {
        source:'유니세프', title:'코로나 이후 어린이 백신 접종률 여전히 회복 안 돼',
        body:'유니세프와 WHO는 코로나19 팬데믹 이후 전 세계 어린이 백신 접종률이 아직 팬데믹 이전 수준을 회복하지 못했다고 밝혔습니다. 약 6700만 명의 어린이가 정기 예방접종을 놓쳤으며, 홍역·소아마비 등 예방 가능한 질병 발생이 다시 증가하고 있습니다.',
        hint:'"백신"과 "건강"이 핵심이에요. 가난한 나라에서 더 심각한 불평등 측면도 떠올려 보세요.',
        fc:'완벽해요! 건강(3), 빈곤(1), 불평등(10), 협력(17)까지 연결했어요!',
        fp:'건강(3)은 꼭 포함해야 해요. 불평등 측면도 함께 생각해보세요.',
        fm:'"백신 접종"은 어떤 SDG와 관련 있을까요? 건강 관련 목표를 찾아봐요.',
        lc:'나의 건강을 잘 챙기는 것도 세계시민 의식의 시작이에요.',
        bonus:'오늘 내가 받은 예방접종 기록을 부모님과 함께 확인해보세요.',
      },
      en: {
        source:'UNICEF', title:'Child vaccination rates still below pre-COVID levels',
        body:'UNICEF and WHO say global child vaccination rates have not yet recovered to pre-pandemic levels. About 67 million children missed routine immunizations during COVID-19, and preventable diseases like measles and polio are rising again.',
        hint:'"Vaccines" and "health" are the keys. Also think about inequality — it hits poorer countries harder.',
        fc:'Perfect! Health (3), Poverty (1), Inequality (10) and Partnerships (17) — well connected!',
        fp:'Health (3) is a must. Also think about the inequality angle.',
        fm:'Which SDG matches "vaccination"? Find the one about health.',
        lc:'Looking after your own health is the start of being a global citizen.',
        bonus:'Check your immunization record with your parents today.',
      },
      ja: {
        source:'UNICEF', title:'コロナ後、子どものワクチン接種率がまだ回復せず',
        body:'ユニセフとWHOは、コロナ後も世界の子どものワクチン接種率がパンデミック前の水準まで回復していないと発表しました。約6,700万人の子どもが定期接種を逃しており、はしかやポリオなど予防可能な病気が再び増えています。',
        hint:'「ワクチン」と「健康」が鍵。貧しい国でより深刻な不平等の面も考えてみよう。',
        fc:'完璧!健康(3)、貧困(1)、不平等(10)、協力(17)までつなげたね!',
        fp:'健康(3)は必ず。不平等の側面も一緒に考えよう。',
        fm:'「ワクチン」はどのSDGと関わる?健康の目標を探してみよう。',
        lc:'自分の健康を大切にすることが、世界市民意識のはじまりだよ。',
        bonus:'今日、自分の予防接種の記録を保護者と一緒に確認してみよう。',
      },
    },
  },
  {
    correct: [13,7,17,11],
    tags: { ko:['기후변화','지구온난화','파리협정','WMO'], en:['climate','warming','Paris Agreement','WMO'], ja:['気候変動','温暖化','パリ協定','WMO'] },
    url: 'https://news.un.org/en/story/2024/11/1156789',
    i18n: {
      ko: {
        source:'UNDP', title:'지구 평균 기온, 산업화 이전 대비 1.5°C 첫 돌파',
        body:'세계기상기구(WMO)는 2024년이 관측 역사상 지구 평균 기온이 산업화 이전 수준보다 1.5°C 이상 높아진 첫 번째 해가 될 가능성이 높다고 발표했습니다. 이상 폭염, 초강력 태풍, 전례 없는 산불이 이를 뒷받침합니다. 파리협정 목표 달성을 위한 즉각적인 온실가스 감축이 촉구되고 있습니다.',
        hint:'기후변화 관련 SDG와 에너지 전환 관련 SDG를 함께 찾아보세요.',
        fc:'탁월해요! 기후행동(13), 청정에너지(7), 국제 협력(17), 지속가능 도시(11)까지 완벽해요!',
        fp:'기후행동(13)은 핵심이에요. 에너지 관련 SDG도 함께 생각해보세요.',
        fm:'"기온 상승"과 "기후"에서 SDG를 찾고, 에너지 문제와도 연결해보세요.',
        lc:'석탄 대신 태양광·풍력 전기를 쓰려는 노력이 지구 온도를 낮추는 데 도움이 돼요.',
        bonus:'오늘 에어컨이나 히터 온도를 1도 조절하고, 가족에게 기후변화와 연결해서 설명해보세요.',
      },
      en: {
        source:'UNDP', title:'Global temperature passes 1.5°C above pre-industrial for the first time',
        body:'The World Meteorological Organization (WMO) reports 2024 is likely to be the first year in recorded history where the global average temperature is more than 1.5°C above pre-industrial levels. Heatwaves, super typhoons and unprecedented wildfires support this. Immediate emission cuts are urgently needed to meet the Paris Agreement goal.',
        hint:'Look for the climate SDG and the SDG about clean energy together.',
        fc:'Outstanding! Climate Action (13), Clean Energy (7), Partnerships (17) and Sustainable Cities (11) — perfect!',
        fp:'Climate Action (13) is the core. Also think about the energy SDG.',
        fm:'Find the SDG behind "rising temperature", then connect it to energy.',
        lc:'Switching from coal to solar or wind power really helps cool the planet.',
        bonus:'Change your AC or heater by 1°C today, and explain to your family how it connects to climate change.',
      },
      ja: {
        source:'UNDP', title:'地球の平均気温、産業革命前比1.5°Cを初めて超える',
        body:'世界気象機関(WMO)は、2024年が観測史上初めて地球の平均気温が産業革命前を1.5°C以上上回る年になる可能性が高いと発表しました。猛暑、超大型台風、前例のない山火事がそれを裏付けています。パリ協定の目標達成に向けた即時の温室効果ガス削減が求められています。',
        hint:'気候変動に関わるSDGと、エネルギー転換に関わるSDGを一緒に探そう。',
        fc:'素晴らしい!気候行動(13)、クリーンエネルギー(7)、協力(17)、持続可能な都市(11)まで完璧!',
        fp:'気候行動(13)が中心。エネルギーのSDGも一緒に考えよう。',
        fm:'「気温上昇」「気候」からSDGを探し、エネルギー問題とも結びつけよう。',
        lc:'石炭の代わりに太陽光や風力の電気を使う取り組みが、地球の気温を下げる助けになるよ。',
        bonus:'今日、エアコンや暖房の温度を1度だけ調整して、家族に気候変動とのつながりを説明してみよう。',
      },
    },
  },

  // ─── 추가 기사 12개 (2025년 최신 뉴스 기반, 다국어) ───
  {
    correct: [1, 2, 3, 4],
    tags: {
      ko: ['어린이빈곤', '유니세프', '다차원빈곤', '2025'],
      en: ['child poverty', 'UNICEF', 'multidimensional', '2025'],
      ja: ['子どもの貧困', 'UNICEF', '多次元貧困', '2025'],
    },
    url: 'https://www.unicef.org/press-releases/more-400-million-children-globally-live-poverty-missing-out-least-two-daily-needs',
    i18n: {
      ko: {
        source: 'UN뉴스',
        title: '세계 어린이 5명 중 1명, 여전히 극심한 빈곤 속에 살아',
        body: '유니세프가 2025년 세계 어린이 현황 보고서를 통해 전 세계 저·중소득 국가 어린이 4억 1700만 명이 교육, 건강, 영양, 위생, 주거 중 두 가지 이상을 충족하지 못하는 다차원적 빈곤 상태에 있다고 밝혔습니다. 분쟁, 기후 위기, 기술 격차, 원조 삭감이 복합적으로 작용해 빈곤 탈출을 가로막고 있습니다. 특히 사하라 이남 아프리카와 남아시아 어린이들이 가장 큰 영향을 받고 있습니다.',
        hint: '빈곤, 건강, 교육, 영양 등 여러 문제가 동시에 나타나요. 각각 어떤 SDG와 연결될까요?',
        fc: '완벽해요! 빈곤(SDG 1), 기아(SDG 2), 건강(SDG 3), 교육(SDG 4)이 모두 연결된 복합적인 문제예요. 어린이 빈곤이 얼마나 많은 SDGs와 동시에 얽혀 있는지 잘 파악했어요!',
        fp: '잘 찾았어요! 빈곤(SDG 1)은 찾았나요? 빈곤한 어린이들은 건강(SDG 3)과 교육(SDG 4)도 함께 박탈당해요. 여러 문제가 동시에 연결됩니다.',
        fm: '"빈곤"이라는 단어에서 SDG 1을 찾아보세요. 그리고 빈곤한 아이들이 어떤 것들을 못 누리는지 — 밥, 병원, 학교 — 를 SDG 번호와 연결해보세요.',
        lc: '우리가 학교에 다니고, 밥을 먹고, 병원에 갈 수 있다는 것이 당연한 게 아니에요. 이런 것들이 동시에 없는 어린이들을 위해 국제 원조 단체에 관심 갖는 것도 세계시민 행동이에요.',
        bonus: '오늘 저녁 밥을 먹으면서 "오늘 밥을 못 먹은 어린이들"을 한 번만 생각해보고, 음식을 소중히 여겨보세요.',
      },
      en: {
        source: 'UN News',
        title: '1 in 5 children worldwide still lives in extreme poverty',
        body: 'UNICEF\'s 2025 State of the World\'s Children report finds 417 million children in low- and middle-income countries face multidimensional poverty — missing at least two of education, health, nutrition, water and sanitation, or housing. Conflict, climate crisis, the digital divide and aid cuts combine to block escape from poverty. Children in sub-Saharan Africa and South Asia are most affected.',
        hint: 'Several issues appear at once — poverty, health, education, nutrition. Which SDG matches each?',
        fc: 'Perfect! Poverty (1), Hunger (2), Health (3) and Education (4) are all interlinked. You captured how many SDGs child poverty crosses at once!',
        fp: 'Good catch! Did you spot Poverty (1)? Children in poverty also lose Health (3) and Education (4) — many goals connect at once.',
        fm: 'Start with SDG 1 from the word "poverty". Then connect each thing poor children lack — food, hospital, school — to its SDG.',
        lc: 'Going to school, eating meals and visiting a clinic isn\'t a given for every child. Caring about international aid groups is also a global-citizen action.',
        bonus: 'At dinner today, pause once to think about "children who didn\'t eat today" and treat your food with care.',
      },
      ja: {
        source: 'UNニュース',
        title: '世界の子どもの5人に1人、いまだに極度の貧困に',
        body: 'ユニセフの2025年「世界子供白書」によると、低・中所得国の4億1,700万人の子どもが、教育・健康・栄養・水と衛生・住居のうち2つ以上を満たせない多次元的貧困にあります。紛争、気候危機、デジタル格差、援助削減が重なり、貧困からの脱出を阻んでいます。サハラ以南のアフリカと南アジアの子どもたちが最も大きな影響を受けています。',
        hint: '貧困・健康・教育・栄養など複数の問題が同時に現れているよ。それぞれどのSDGとつながる?',
        fc: '完璧!貧困(1)、飢餓(2)、健康(3)、教育(4)が全部つながった複合課題だね。子どもの貧困がいくつものSDGsと同時に絡んでいることをよく捉えたよ!',
        fp: 'いいね!貧困(1)は見つけた?貧しい子どもたちは健康(3)と教育(4)も同時に奪われがち。複数の問題がつながっているよ。',
        fm: '「貧困」からSDG 1を見つけよう。そして貧しい子どもたちが奪われるもの — ごはん・病院・学校 — をそれぞれのSDGに結びつけてみよう。',
        lc: '学校に通い、ごはんを食べ、病院に行けるのは当たり前ではないんだ。それらを同時に持てない子どものために国際支援に関心を持つのも世界市民の行動だよ。',
        bonus: '今日の夕食のとき「ごはんを食べられなかった子どもたち」のことを一度だけ考え、食べ物を大切にしてみよう。',
      },
    },
  },
  {
    correct: [13, 7, 17, 15],
    tags: {
      ko: ['COP30', '기후협약', '화석연료', '벨렝'],
      en: ['COP30', 'climate', 'fossil fuels', 'Belem'],
      ja: ['COP30', '気候協約', '化石燃料', 'ベレン'],
    },
    url: 'https://news.un.org/en/story/2025/11/1166433',
    i18n: {
      ko: {
        source: 'UN뉴스',
        title: 'COP30 기후회의, 화석연료 퇴출 로드맵 합의 없이 마무리',
        body: '브라질 벨렝에서 열린 제30차 유엔기후변화협약 당사국총회(COP30)가 2025년 11월 마무리됐습니다. 기후 재원 1조 3천억 달러 조성 목표는 합의했지만, 화석연료 단계적 퇴출과 산림 벌채 중단 로드맵은 일부 국가의 반대로 끝내 포함되지 못했습니다. 유엔 사무총장은 "기후 위기가 가속화되는 상황에서 더 강한 행동이 필요하다"고 촉구했습니다.',
        hint: '기후회의와 직접 연결된 SDG, 에너지 전환, 국제 협력, 산림 보호와 관련된 목표를 찾아보세요.',
        fc: '훌륭해요! 기후행동(SDG 13)이 핵심이고, 화석연료 대신 청정에너지(SDG 7)로의 전환, 각국 협력(SDG 17), 산림 보호(SDG 15)까지 완벽하게 연결했어요!',
        fp: '기후행동(SDG 13)은 반드시 포함해야 해요. "화석연료 퇴출"은 어떤 에너지로 바꿔야 한다는 걸까요? 그 에너지와 관련된 SDG도 찾아보세요.',
        fm: '"기후회의"라는 단어에서 기후와 관련된 SDG를 찾아보세요. 화석연료 대신 쓸 수 있는 에너지, 숲 보호도 각각 SDG가 있어요.',
        lc: '우리가 전기를 아끼거나 대중교통을 이용하는 것이 화석연료 사용을 줄이는 작은 실천이에요. 세계 정상들이 합의하지 못한 일을 우리 각자가 먼저 시작할 수 있어요.',
        bonus: '오늘 집에서 이동할 때 자동차 대신 걷기, 자전거, 버스 중 하나를 선택해보고 그 이유를 가족에게 말해보세요.',
      },
      en: {
        source: 'UN News',
        title: 'COP30 ends without a roadmap to phase out fossil fuels',
        body: 'The 30th UN Climate Change Conference (COP30) in Belem, Brazil ended in November 2025. Parties agreed on a $1.3 trillion climate finance goal, but a roadmap to phase out fossil fuels and halt deforestation was blocked by a few countries. The UN Secretary-General urged "stronger action while the climate crisis accelerates".',
        hint: 'Find the SDG tied to climate, plus goals about energy transition, partnerships and forests.',
        fc: 'Outstanding! Climate Action (13) is the core, plus Clean Energy (7), Partnerships (17) and Life on Land (15) for forests — perfect!',
        fp: 'Climate Action (13) is essential. "Phasing out fossil fuels" means switching to what kind of energy? Add that SDG too.',
        fm: '"Climate conference" points to the climate SDG. Energy that replaces fossil fuels and forest protection are each their own SDG.',
        lc: 'Saving electricity and taking public transport are small actions that cut fossil-fuel use. We can start what world leaders failed to agree on.',
        bonus: 'Today, pick walking, biking or the bus over a car for one trip — and tell your family why.',
      },
      ja: {
        source: 'UNニュース',
        title: 'COP30、化石燃料撤廃ロードマップで合意できず閉幕',
        body: 'ブラジル・ベレンで開かれた第30回国連気候変動枠組条約締約国会議(COP30)が2025年11月に閉幕しました。気候資金1.3兆ドルの目標には合意したものの、化石燃料の段階的廃止と森林伐採停止のロードマップは一部の国の反対で盛り込まれませんでした。国連事務総長は「気候危機が加速する中、より強い行動が必要だ」と訴えました。',
        hint: '気候会議に直結するSDG、エネルギー転換、国際協力、森林保護に関わる目標を探そう。',
        fc: '素晴らしい!気候行動(13)が中心、化石燃料に代わるクリーンエネルギー(7)、各国の協力(17)、森林保護(15)まで完璧につなげたね!',
        fp: '気候行動(13)は必須。「化石燃料撤廃」は何のエネルギーへ転換すること?そのエネルギーのSDGも探してみよう。',
        fm: '「気候会議」から気候のSDGを。化石燃料に代わるエネルギーと森林保護にもそれぞれSDGがあるよ。',
        lc: '節電や公共交通の利用は、化石燃料を減らす小さな実践。世界の首脳が合意できなかったことを、私たち一人ひとりが先に始められるよ。',
        bonus: '今日、移動するときに車ではなく徒歩・自転車・バスのいずれかを選び、その理由を家族に話してみよう。',
      },
    },
  },
  {
    correct: [4, 16, 10, 1],
    tags: {
      ko: ['교육위기', '난민', '분쟁', '학교밖청소년'],
      en: ['education crisis', 'refugees', 'conflict', 'out of school'],
      ja: ['教育危機', '難民', '紛争', '不就学'],
    },
    url: 'https://www.educationcannotwait.org/global-estimates-2025-update',
    i18n: {
      ko: {
        source: '유니세프',
        title: '위기 속 학교 밖 어린이 2억 3400만 명, 역대 최고',
        body: '유니세프와 교육재건기금(ECW)의 2025년 보고서에 따르면 분쟁·재난·기후위기 등으로 교육이 필요한 위기 상황의 어린이가 2억 3400만 명에 달해 역대 최고를 기록했습니다. 이 중 8500만 명은 아예 학교에 다니지 못하고 있으며, 학교에 다니더라도 위기 상황의 어린이 5명 중 1명만이 기초 읽기 능력을 갖추고 있습니다. 난민·장애 어린이·여아가 가장 큰 피해를 보고 있습니다.',
        hint: '학교에 못 가는 어린이들과 관련된 교육 SDG와, 그 원인인 분쟁·불평등 관련 SDG를 찾아보세요.',
        fc: '완벽해요! 교육(SDG 4)과 평화(SDG 16)가 핵심이고, 난민·장애·여아 등 불평등(SDG 10), 그리고 빈곤(SDG 1)과의 연결도 훌륭해요!',
        fp: '교육(SDG 4)은 필수예요! 어린이들이 학교에 못 가는 이유가 "분쟁"이라는 점에서 또 다른 SDG도 찾아보세요.',
        fm: '"학교 밖 어린이"에서 교육 관련 SDG를 찾고, 왜 이런 일이 생기는지 — 전쟁, 재난 — 원인과 관련된 SDG도 연결해보세요.',
        lc: '우리가 매일 학교에 가는 것이 전 세계 2억 명 이상의 어린이들에게는 꿈같은 일이에요. 오늘 배움에 감사하고 최선을 다하는 것도 SDG 4 실천이에요.',
        bonus: '오늘 수업에서 집중이 어렵다고 느낄 때, 학교조차 다닐 수 없는 친구들을 떠올려보고 다시 한 번 집중해보세요.',
      },
      en: {
        source: 'UNICEF',
        title: '234 million crisis-affected children need education — a record high',
        body: 'A 2025 UNICEF and Education Cannot Wait (ECW) report says 234 million crisis-affected children — hit by conflict, disasters or climate crises — need urgent education support, a record high. About 85 million are completely out of school, and even those attending classes show only 1 in 5 reaching basic reading skills. Refugees, children with disabilities and girls are most affected.',
        hint: 'Use the education SDG for kids out of school, and another for the causes — conflict and inequality.',
        fc: 'Perfect! Education (4) and Peace (16) at the core, plus Inequality (10) for refugees, disability and girls, and Poverty (1) — beautifully linked!',
        fp: 'Education (4) is a must. The cause being "conflict" should also point you to another SDG.',
        fm: '"Out of school" points to the education SDG. Why does it happen — war, disaster? Find SDGs for those causes too.',
        lc: 'Going to school every day is a dream for over 200 million children. Doing your best today is itself an act of SDG 4.',
        bonus: 'When focus is hard in class today, remember friends who can\'t even attend school — and refocus once more.',
      },
      ja: {
        source: 'UNICEF',
        title: '危機下で学校に通えない子ども2億3,400万人、過去最多',
        body: 'ユニセフと教育再建基金(ECW)の2025年報告書によると、紛争・災害・気候危機などで教育支援が必要な危機下の子どもが過去最多の2億3,400万人に達しました。うち8,500万人は学校にまったく通えておらず、通っていても危機下の子どもの5人に1人しか基礎的な読みができていません。難民・障がい児・女子が最も大きな影響を受けています。',
        hint: '学校に通えない子どもに関わる教育のSDGと、原因である紛争・不平等のSDGを探そう。',
        fc: '完璧!教育(4)と平和(16)が中心、難民・障がい・女子の不平等(10)、貧困(1)まで結びつけたね!',
        fp: '教育(4)は必須!通えない原因が「紛争」という点から、別のSDGも探してみよう。',
        fm: '「学校に通えない子ども」から教育のSDGを。なぜそうなるか — 戦争・災害 — の原因のSDGもつなげよう。',
        lc: '毎日学校に通えることは、世界の2億人以上の子どもにとって夢のような話。今日の学びを大切に最善を尽くすこと自体がSDG 4の実践だよ。',
        bonus: '今日授業で集中が切れたとき、学校にすら通えない子のことを思い出して、もう一度集中してみよう。',
      },
    },
  },
  {
    correct: [15, 13, 17, 2],
    tags: {
      ko: ['아마존', '산림벌채', 'COP30', '탄소흡수'],
      en: ['Amazon', 'deforestation', 'COP30', 'carbon sink'],
      ja: ['アマゾン', '森林伐採', 'COP30', '炭素吸収'],
    },
    url: 'https://www.unep.org/news-and-stories/story/six-issues-will-dominate-cop30',
    i18n: {
      ko: {
        source: 'UNEP',
        title: '아마존 열대우림 벌채, COP30에서도 중단 합의 실패',
        body: '2025년 11월 브라질에서 열린 COP30에서 아마존 열대우림 벌채를 2030년까지 중단하는 로드맵 합의에 실패했습니다. "지구의 허파"로 불리는 아마존은 지구 온난화를 완화하는 핵심 탄소 흡수원이지만, 농업·자원 개발을 위한 벌채가 계속되고 있습니다. 환경단체들은 이번 결과를 강하게 비판하며 각국 정부의 즉각적인 행동을 촉구했습니다.',
        hint: '"숲"과 직접 관련된 SDG, 기후변화와의 관계, 식량 생산을 위한 벌채와 관련된 SDG를 찾아보세요.',
        fc: '탁월해요! 육상생태계(SDG 15)가 핵심이고, 산림 파괴가 기후변화(SDG 13)를 악화시키며, 농업 목적 벌채는 기아(SDG 2), 국제 협력(SDG 17) 부재도 잘 연결했어요!',
        fp: '육상생태계(SDG 15)와 기후행동(SDG 13)은 꼭 포함해야 해요. 아마존 벌채가 왜 일어나는지 — 농업과 식량 — 와 연결된 SDG도 찾아보세요.',
        fm: '"열대우림"과 "벌채"에서 숲·생태계와 관련된 SDG를 찾아보세요. 숲이 줄면 기후에 어떤 영향을 미칠까요?',
        lc: '우리가 소고기를 덜 먹거나 종이를 아끼는 것이 아마존 벌채를 줄이는 데 도움이 돼요. 소를 키우기 위해 숲을 태우는 것이 지구 반대편 우리와도 연결되어 있어요.',
        bonus: '오늘 종이를 한 장이라도 아껴 쓰고, 왜 종이를 아껴야 하는지 나만의 이유를 한 문장으로 써보세요.',
      },
      en: {
        source: 'UNEP',
        title: 'No deal at COP30 to halt Amazon deforestation',
        body: 'COP30 in Brazil (Nov 2025) failed to agree on a roadmap to end Amazon deforestation by 2030. Known as "the lungs of the Earth", the Amazon is a key carbon sink that slows global warming, yet logging for agriculture and resource extraction continues. Environmental groups strongly criticized the outcome and urged immediate government action.',
        hint: 'Find the SDG directly about forests, the link to climate, and the SDG for the food/agriculture driver of logging.',
        fc: 'Excellent! Life on Land (15) is the core, deforestation worsens Climate (13), agriculture-driven logging connects to Hunger (2), and Partnerships (17) is missing — well linked!',
        fp: 'Life on Land (15) and Climate (13) are musts. Also add the SDG behind why the Amazon is logged — agriculture and food.',
        fm: 'Find the SDG for "rainforest" and "deforestation". What happens to climate when forests shrink?',
        lc: 'Eating less beef and saving paper actually help reduce Amazon logging. Forests burned to raise cattle are linked to us across the world.',
        bonus: 'Save at least one sheet of paper today, and write one sentence on why paper matters.',
      },
      ja: {
        source: 'UNEP',
        title: 'アマゾン熱帯雨林の伐採、COP30でも停止合意に失敗',
        body: '2025年11月にブラジルで開かれたCOP30で、アマゾン熱帯雨林の伐採を2030年までに停止するロードマップでの合意に失敗しました。「地球の肺」と呼ばれるアマゾンは温暖化を緩和する重要な炭素吸収源ですが、農業や資源開発のための伐採が続いています。環境団体はこの結果を強く批判し、各国政府に即時の行動を求めました。',
        hint: '「森」に直結するSDG、気候との関係、食料生産のための伐採に関わるSDGを探そう。',
        fc: '素晴らしい!陸の豊かさ(15)が中心、森林破壊が気候(13)を悪化、農業目的の伐採は飢餓(2)、協力(17)の不足までよく結びつけたね!',
        fp: '陸の豊かさ(15)と気候行動(13)は必須。アマゾン伐採がなぜ起きるか — 農業と食料 — のSDGも探してみよう。',
        fm: '「熱帯雨林」「伐採」から森や生態系のSDGを探そう。森が減ると気候にどんな影響がある?',
        lc: '牛肉を少し減らしたり紙を大切に使うことが、アマゾンの伐採を減らす助けになるよ。牛を育てるために森が焼かれていることは、地球の裏側の私たちともつながっているんだ。',
        bonus: '今日、紙を1枚でも大切に使い、なぜ紙を大切にするのか自分の言葉で1文書いてみよう。',
      },
    },
  },
  {
    correct: [13, 1, 10, 3],
    tags: {
      ko: ['기후위기', '어린이', '폭염', '불평등'],
      en: ['climate', 'children', 'heatwave', 'inequality'],
      ja: ['気候危機', '子ども', '猛暑', '不平等'],
    },
    url: 'https://www.unicef.org/reports/state-of-worlds-children/2025',
    i18n: {
      ko: {
        source: 'UN뉴스',
        title: '전 세계 어린이 4명 중 3명, 극단적 기후 위험에 노출',
        body: '2025년 유니세프 보고서에 따르면 전 세계 어린이의 약 75%가 매년 폭염, 홍수, 가뭄 등 하나 이상의 극단적 기후 위험에 노출되어 있습니다. 기후 위험과 빈곤은 악순환을 형성해, 가난한 가정의 어린이일수록 기후 재해에 더 취약하고 피해 복구도 어렵습니다. 기후변화에 가장 적게 기여한 나라들이 오히려 가장 큰 피해를 받고 있다는 점에서 불공평한 문제이기도 합니다.',
        hint: '기후변화와 직접 관련된 SDG, 가난한 나라가 더 큰 피해를 받는 불평등 측면도 생각해보세요.',
        fc: '완벽해요! 기후행동(SDG 13)이 핵심이고, 빈곤(SDG 1)과 기후의 악순환, 불평등(SDG 10), 건강(SDG 3)까지 연결한 깊이 있는 분석이에요!',
        fp: '기후행동(SDG 13)은 꼭 포함해야 해요. 기후 피해가 가난한 나라에 더 크게 온다는 점에서 불평등(SDG 10)도 생각해보세요.',
        fm: '"기후 위험"에서 SDG 13을 찾아보세요. 그리고 왜 가난한 나라 어린이들이 더 큰 피해를 받는지도 생각해봐요.',
        lc: '우리나라도 최근 폭염과 집중호우가 늘고 있어요. 에너지를 아끼고 쓰레기를 줄이는 것이 지구 반대편 어린이들을 지키는 행동과 연결돼요.',
        bonus: '오늘 날씨를 관찰하고, 최근 1년간 우리 동네에서 느낀 이상한 날씨를 하나 떠올려 노트에 적어보세요.',
      },
      en: {
        source: 'UN News',
        title: '3 in 4 children worldwide exposed to extreme climate risks',
        body: 'A 2025 UNICEF report finds about 75% of the world\'s children face at least one extreme climate risk each year — heatwaves, floods or droughts. Climate risk and poverty form a vicious cycle: poorer families\' children are more vulnerable and recover more slowly. Countries that contributed least to climate change suffer the most, making it deeply unfair.',
        hint: 'Start with the climate SDG, then think about the inequality of poor nations being hit hardest.',
        fc: 'Perfect! Climate Action (13) is the core, plus the cycle with Poverty (1), Inequality (10), and Health (3) — a deep analysis!',
        fp: 'Climate Action (13) is essential. Climate hits poor countries harder, so include Inequality (10) too.',
        fm: '"Climate risk" points to SDG 13. Also think about why children in poor countries suffer more.',
        lc: 'Heatwaves and heavy rains are increasing where we live too. Saving energy and cutting waste protects children on the other side of the planet.',
        bonus: 'Watch the weather today, recall one strange weather event from the past year in your area, and write it down.',
      },
      ja: {
        source: 'UNニュース',
        title: '世界の子どもの4人に3人が極端な気候リスクにさらされる',
        body: '2025年のユニセフ報告書によると、世界の子どもの約75%が毎年、猛暑・洪水・干ばつなど1つ以上の極端な気候リスクにさらされています。気候リスクと貧困は悪循環を生み、貧しい家庭の子どもほど気候災害に弱く、復旧も難しい状況です。気候変動への寄与が最も少ない国がいちばん大きな被害を受けているという点で、不公平な問題でもあります。',
        hint: '気候変動に直結するSDGと、貧しい国がより大きな被害を受ける不平等の側面も考えよう。',
        fc: '完璧!気候行動(13)が中心、貧困(1)との悪循環、不平等(10)、健康(3)まで結びつけた深い分析だね!',
        fp: '気候行動(13)は必須。気候被害が貧しい国でより大きい点で、不平等(10)も考えよう。',
        fm: '「気候リスク」からSDG 13を。そして、なぜ貧しい国の子どもがより大きな被害を受けるのかも考えてみよう。',
        lc: '日本でも猛暑や豪雨が増えているよ。省エネやごみを減らすことが、地球の反対側の子どもたちを守る行動につながるんだ。',
        bonus: '今日の天気を観察し、最近1年で感じた地元のおかしな天気を1つ思い出してノートに書いてみよう。',
      },
    },
  },
  {
    correct: [3, 4, 10, 16],
    tags: {
      ko: ['청소년정신건강', 'WHO', '우울증', '불안'],
      en: ['adolescent mental health', 'WHO', 'depression', 'anxiety'],
      ja: ['思春期メンタルヘルス', 'WHO', 'うつ', '不安'],
    },
    url: 'https://www.who.int/news/item/mental-health-adolescents',
    i18n: {
      ko: {
        source: 'WHO',
        title: '전 세계 청소년 7명 중 1명, 정신건강 문제 겪고 있어',
        body: '세계보건기구(WHO)에 따르면 10~19세 청소년 약 7명 중 1명이 우울증, 불안장애 등 정신건강 문제를 경험하고 있습니다. 분쟁, 빈곤, 기후 불안, 소셜미디어 과의존이 주요 원인으로 꼽히며, 특히 분쟁 지역 어린이들의 경우 정신건강 지원이 절실하지만 서비스가 극히 부족합니다. WHO는 학교 기반 정신건강 프로그램 확대를 각국에 촉구하고 있습니다.',
        hint: '건강과 직접 관련된 SDG, 학교 기반 프로그램은 교육과 연결, 서비스 접근 불평등도 생각해보세요.',
        fc: '훌륭해요! 건강(SDG 3)이 핵심이고, 학교 기반 지원(SDG 4), 서비스 불평등(SDG 10), 분쟁 지역 어린이 문제(SDG 16)까지 연결한 완벽한 분석이에요!',
        fp: '건강(SDG 3)은 필수예요! 학교에서 정신건강을 다룬다는 점에서 교육(SDG 4)도 연결돼요. 분쟁 지역 어린이들이 더 취약하다는 불평등도 생각해보세요.',
        fm: '"정신건강 문제"에서 건강과 관련된 SDG를 찾아보세요. 학교에서 프로그램을 만든다면 어떤 SDG와도 연결될까요?',
        lc: '우리 주변 친구들도 스트레스와 불안을 느낄 수 있어요. 먼저 인사하고 이야기를 들어주는 것도 정신건강을 지키는 세계시민 행동이에요.',
        bonus: '오늘 하루 동안 힘들어 보이는 친구에게 "요즘 어때?"라고 한 번 물어봐요. 작은 관심이 큰 힘이 돼요.',
      },
      en: {
        source: 'WHO',
        title: '1 in 7 adolescents worldwide lives with a mental health condition',
        body: 'WHO reports about 1 in 7 adolescents (10–19) experiences a mental health condition such as depression or anxiety. Conflict, poverty, climate anxiety and heavy social-media use are key drivers; mental-health services are urgently needed yet severely lacking, especially in conflict zones. WHO urges nations to scale up school-based mental-health programs.',
        hint: 'Use the health SDG. School-based programs link to education. Also think about who can\'t access services.',
        fc: 'Excellent! Health (3) is the core, plus Education (4) for school programs, Inequality (10) in access, and Peace (16) for conflict-zone children — perfect!',
        fp: 'Health (3) is essential. Mental-health programs at school also link to Education (4). Children in conflict zones being more vulnerable points to inequality too.',
        fm: '"Mental health" points to the health SDG. If schools run programs, which SDG does that connect to?',
        lc: 'Friends around us may feel stress and anxiety too. Saying hello first and listening is a real act for mental health.',
        bonus: 'Ask one friend who seems down "how are you these days?" today. A small attention can help a lot.',
      },
      ja: {
        source: 'WHO',
        title: '世界の思春期世代の7人に1人、メンタルヘルスの課題を抱える',
        body: 'WHOによると、10〜19歳の約7人に1人が、うつや不安など何らかのメンタルヘルスの課題を抱えています。紛争、貧困、気候不安、SNSへの依存などが主な要因とされ、特に紛争地域の子どもには支援が切実ですが、サービスが大きく不足しています。WHOは学校を基盤としたメンタルヘルスプログラムの拡充を各国に呼びかけています。',
        hint: '健康に直結するSDG。学校でのプログラムは教育とつながる。サービスへのアクセス不平等も考えよう。',
        fc: '素晴らしい!健康(3)が中心、学校支援で教育(4)、サービス不平等(10)、紛争地域の子ども(16)までつなげた完璧な分析!',
        fp: '健康(3)は必須!学校で扱う点で教育(4)もつながる。紛争地域の子どもの脆弱さから不平等も考えよう。',
        fm: '「メンタルヘルス」から健康のSDGを。学校でプログラムを行うなら、どのSDGとつながる?',
        lc: '身近な友だちもストレスや不安を感じているかも。先にあいさつし話を聞くことも、メンタルヘルスを守る世界市民の行動だよ。',
        bonus: '今日1日、つらそうな友だちに「最近どう?」と一度声をかけてみよう。小さな関心が大きな力になるよ。',
      },
    },
  },
  {
    correct: [4, 10, 9, 17],
    tags: {
      ko: ['디지털격차', '교육불평등', 'AI교육', '기술'],
      en: ['digital divide', 'education', 'AI', 'technology'],
      ja: ['デジタル格差', '教育不平等', 'AI教育', '技術'],
    },
    url: 'https://www.unicef.org/sustainable-development-goals',
    i18n: {
      ko: {
        source: '유니세프',
        title: '디지털 격차, 저소득국 어린이 교육 불평등 심화시켜',
        body: '유니세프 2025년 보고서에 따르면 저소득 국가와 고소득 국가 간 디지털 격차가 교육 불평등을 더욱 심화시키고 있습니다. 저소득 국가 어린이의 90% 이상이 기본적인 디지털 기기나 인터넷에 접근하지 못하는 반면, 고소득 국가에서는 AI 기반 학습 도구가 빠르게 도입되고 있습니다. 이 격차가 해소되지 않으면 2030년 SDGs 목표 달성이 어렵다고 경고했습니다.',
        hint: '교육 불평등과 디지털 기술 접근, 국가 간 불평등, 기술 혁신 관련 SDG를 찾아보세요.',
        fc: '탁월해요! 교육(SDG 4)과 불평등(SDG 10)이 핵심이고, 기술·인프라 격차(SDG 9), 국제 협력(SDG 17)까지 완벽하게 연결했어요!',
        fp: '교육(SDG 4)과 불평등(SDG 10)은 잘 찾았어요! "디지털 기기와 인터넷"은 어떤 기술·인프라 관련 SDG와 연결될까요?',
        fm: '"디지털 격차"에서 교육 관련 SDG와 나라 간 차이 관련 SDG를 찾아보세요. 스마트폰과 인터넷은 어떤 SDG와 연결될까요?',
        lc: '우리가 당연하게 쓰는 스마트폰과 인터넷이 없는 어린이들이 전 세계에 수억 명이에요. AI 기술을 배울 기회조차 없는 친구들을 생각해봐요.',
        bonus: '오늘 스마트폰이나 컴퓨터를 사용할 때, "이 기기가 없다면 어떨까?"를 30초만 생각해보세요.',
      },
      en: {
        source: 'UNICEF',
        title: 'Digital divide widens education inequality for low-income children',
        body: 'A 2025 UNICEF report says the digital divide between low- and high-income countries is widening education inequality. Over 90% of children in low-income countries lack basic digital devices or internet, while high-income countries adopt AI-driven learning tools rapidly. Without closing this gap, reaching the 2030 SDGs will be difficult.',
        hint: 'Look for the education SDG, the inequality SDG, and the SDG about technology and infrastructure.',
        fc: 'Outstanding! Education (4) and Inequality (10) at the core, plus Innovation (9) for the tech gap and Partnerships (17) — perfect!',
        fp: 'You found Education (4) and Inequality (10). Which SDG covers devices and internet — i.e. infrastructure?',
        fm: '"Digital divide" links to education and to inequality between countries. Smartphones and internet point to which SDG?',
        lc: 'Hundreds of millions of children don\'t have the phones and internet we take for granted. Some don\'t even get a chance to learn AI.',
        bonus: 'When you use your phone or computer today, pause 30 seconds and ask: "What if I didn\'t have this device?"',
      },
      ja: {
        source: 'UNICEF',
        title: 'デジタル格差が低所得国の子どもの教育不平等を拡大',
        body: 'ユニセフの2025年報告書によると、低所得国と高所得国の間のデジタル格差が教育の不平等をさらに広げています。低所得国の子どもの90%以上が基本的なデジタル機器やインターネットを利用できない一方、高所得国ではAIを活用した学習ツールが急速に導入されています。この格差を埋めないと、2030年のSDGs達成は難しいと警告しています。',
        hint: '教育の不平等とデジタル接続、国家間の不平等、技術革新に関わるSDGを探そう。',
        fc: '素晴らしい!教育(4)と不平等(10)が中心、技術・インフラ格差(9)、国際協力(17)まで完璧!',
        fp: '教育(4)と不平等(10)はバッチリ!「デジタル機器とインターネット」は技術・インフラのどのSDGとつながる?',
        fm: '「デジタル格差」から教育のSDGと国家間の差のSDGを探そう。スマホやネットはどのSDGと?',
        lc: '当たり前に使うスマホやネットを持てない子どもが世界に数億人いる。AIを学ぶ機会すらない友だちのことを考えてみよう。',
        bonus: '今日スマホやパソコンを使うときに「この機器がなかったらどうかな?」と30秒だけ考えてみよう。',
      },
    },
  },
  {
    correct: [14, 13, 17, 2],
    tags: {
      ko: ['산호초', '해양온난화', '생태계', '백화현상'],
      en: ['coral reefs', 'ocean warming', 'ecosystem', 'bleaching'],
      ja: ['サンゴ礁', '海洋温暖化', '生態系', '白化現象'],
    },
    url: 'https://www.unep.org/events/conference/unep-2025-un-ocean-conference',
    i18n: {
      ko: {
        source: 'UNEP',
        title: '산호초 절반, 기후변화로 백화 현상 위기',
        body: '유엔환경계획(UNEP)과 국제산호초이니셔티브는 2025년 보고서를 통해 전 세계 산호초의 약 절반이 해수 온도 상승으로 인한 산호 백화 현상으로 심각한 위기에 처했다고 경고했습니다. 산호초는 전 세계 해양 생물의 25%가 의존하는 생태계이며, 연간 약 3천억 달러의 수산업·관광업 가치를 창출합니다. 탄소 배출 감축 없이는 2050년까지 90% 이상이 사라질 수 있다고 전망했습니다.',
        hint: '"바다"와 직접 관련된 SDG, 해수 온도를 높이는 원인, 수산업과 식량도 생각해보세요.',
        fc: '완벽해요! 해양생태계(SDG 14)가 핵심이고, 기후변화(SDG 13)가 원인, 국제 협력(SDG 17), 수산업 감소로 인한 식량(SDG 2) 문제까지 훌륭하게 연결했어요!',
        fp: '해양생태계(SDG 14)는 꼭 포함해야 해요! 산호초가 사라지는 원인인 기후변화(SDG 13)도 함께 찾아보세요.',
        fm: '"산호초"와 "해양"에서 바다 관련 SDG를 찾아보세요. 산호초가 왜 사라지는지 그 원인도 SDG와 연결해봐요.',
        lc: '우리가 여름에 에어컨을 하나 덜 켜는 것이 탄소 배출을 줄여 바다 온도를 낮추는 데 도움이 돼요. 지구 반대편 바닷속 생물들과 연결된 행동이에요.',
        bonus: '오늘 산호초 사진을 한 번 검색해보고, 산호 백화 현상 전후 사진을 비교해보세요. 느낀 점을 한 문장으로 적어보세요.',
      },
      en: {
        source: 'UNEP',
        title: 'Half of all coral reefs at risk from bleaching due to climate change',
        body: 'UNEP and the International Coral Reef Initiative warn in their 2025 report that about half of the world\'s coral reefs face severe bleaching from rising sea temperatures. Reefs support 25% of all marine life and generate roughly $300 billion a year in fisheries and tourism. Without cutting carbon emissions, more than 90% could be lost by 2050.',
        hint: 'Look for the "ocean" SDG, the cause of warming seas, and the SDG about fish and food.',
        fc: 'Perfect! Life Below Water (14) at the core, Climate (13) as the cause, Partnerships (17), and Hunger (2) via fisheries — beautifully linked!',
        fp: 'Life Below Water (14) is a must. Climate Action (13) is the cause behind the disappearing reefs — add it too.',
        fm: '"Coral reefs" and "ocean" point to the marine SDG. Why are they vanishing? That cause has its own SDG.',
        lc: 'Turning off one extra AC in summer cuts carbon and helps cool the ocean. It is linked to sea creatures on the other side of the world.',
        bonus: 'Search for coral reef photos today, compare before and after bleaching, and write one sentence about how you feel.',
      },
      ja: {
        source: 'UNEP',
        title: 'サンゴ礁の半分、気候変動による白化の危機に',
        body: '国連環境計画(UNEP)と国際サンゴ礁イニシアチブは2025年報告書で、世界のサンゴ礁の約半分が海水温の上昇による白化現象で深刻な危機にあると警告しました。サンゴ礁は世界の海洋生物の25%が依存する生態系で、年間約3,000億ドルの水産・観光価値を生みます。炭素排出を減らさなければ、2050年までに90%以上が失われる可能性があるとしています。',
        hint: '「海」に直結するSDG、海水温を上げる原因、水産と食料についても考えよう。',
        fc: '完璧!海の豊かさ(14)が中心、気候(13)が原因、協力(17)、水産減少による飢餓(2)までうまく結びつけたね!',
        fp: '海の豊かさ(14)は必須!サンゴ礁が消える原因の気候(13)も一緒に探そう。',
        fm: '「サンゴ礁」「海」から海のSDGを。なぜ消えるのか、その原因にもSDGがあるよ。',
        lc: '夏にエアコンを1台減らすだけでも炭素排出が減り、海水温を下げる助けになる。地球の裏側の海の生き物とつながる行動だよ。',
        bonus: '今日、サンゴ礁の写真を検索して白化の前後を見比べ、感じたことを1文書いてみよう。',
      },
    },
  },
  {
    correct: [12, 2, 13, 17],
    tags: {
      ko: ['음식물쓰레기', '식량낭비', '기아', 'UNEP'],
      en: ['food waste', 'food loss', 'hunger', 'UNEP'],
      ja: ['食品ロス', '食料浪費', '飢餓', 'UNEP'],
    },
    url: 'https://www.unep.org/resources/report/unep-food-waste-index-report-2024',
    i18n: {
      ko: {
        source: 'UN뉴스',
        title: '전 세계 음식물 쓰레기, 매년 10억 톤 — 기아 인구는 8억 명',
        body: '유엔환경계획(UNEP)의 2025년 식품 폐기물 지수 보고서에 따르면 전 세계에서 매년 약 10억 톤의 음식이 버려지고 있습니다. 이는 생산된 식품의 약 5분의 1에 해당합니다. 반면 전 세계 약 8억 명이 기아 상태에 있어 충격적인 대비를 이룹니다. 음식물 쓰레기는 전 세계 온실가스 배출의 약 8~10%를 차지해 기후변화에도 심각한 영향을 미칩니다.',
        hint: '"음식물 쓰레기"는 소비와 관련된 SDG와 연결돼요. 기아 문제, 온실가스 배출도 각각 어떤 SDG인지 생각해보세요.',
        fc: '훌륭해요! 책임있는 소비(SDG 12)가 핵심이고, 기아(SDG 2), 기후변화(SDG 13), 국제 협력(SDG 17)까지 완벽하게 연결했어요!',
        fp: '음식물 쓰레기에서 소비 관련 SDG를 찾았나요? 버려지는 음식이 기아(SDG 2)와 기후변화(SDG 13)에도 영향을 미쳐요.',
        fm: '"음식을 버린다"는 것은 어떤 소비 관련 SDG와 연결될까요? 또 굶는 사람이 8억 명인데 음식을 10억 톤 버린다면, 어떤 문제가 보이나요?',
        lc: '우리 집에서 버려지는 음식을 한 가지만 줄여도 기아와 기후변화 모두에 도움이 돼요. 냉장고 속 재료를 확인하고 필요한 만큼만 사는 습관이 세계를 바꿔요.',
        bonus: '오늘 집 냉장고를 열어 버려질 것 같은 음식 하나를 찾아 오늘 안에 먹어보세요. 부모님께 식품 낭비를 줄이자고 제안해봐요.',
      },
      en: {
        source: 'UN News',
        title: 'World wastes 1 billion tonnes of food a year — while 800 million go hungry',
        body: 'UNEP\'s 2025 Food Waste Index Report says roughly 1 billion tonnes of food are wasted globally each year — about a fifth of all food produced. At the same time around 800 million people are hungry, a shocking contrast. Food waste also accounts for 8–10% of global greenhouse-gas emissions, making it a major climate driver.',
        hint: '"Food waste" links to the SDG on consumption. Hunger and greenhouse gases are each their own SDG too.',
        fc: 'Excellent! Responsible Consumption (12) is the core, plus Hunger (2), Climate (13) and Partnerships (17) — perfectly linked!',
        fp: 'Did you find the consumption SDG for "food waste"? Wasted food also affects Hunger (2) and Climate (13).',
        fm: '"Throwing food away" connects to which consumption SDG? With 800 million hungry, what does dumping 1 billion tonnes show?',
        lc: 'Cutting one wasted food item at home helps both hunger and climate. Checking the fridge and buying only what you need can change the world.',
        bonus: 'Open the fridge today, find one item about to be thrown out, and eat it. Suggest reducing food waste to your family.',
      },
      ja: {
        source: 'UNニュース',
        title: '世界の食品ロス、年10億トン — 一方で飢餓人口は8億人',
        body: '国連環境計画(UNEP)の2025年食品廃棄物指数報告書によると、世界では毎年約10億トンの食品が廃棄されており、生産された食品のおよそ5分の1にあたります。一方で世界には約8億人の飢餓状態にある人々がおり、衝撃的な対比を生んでいます。食品ロスは世界の温室効果ガス排出の約8〜10%を占め、気候変動にも深刻な影響を与えています。',
        hint: '「食品ロス」は消費に関わるSDGに直結。飢餓や温室効果ガスも、それぞれどのSDG?',
        fc: '素晴らしい!責任ある消費(12)が中心、飢餓(2)、気候(13)、協力(17)まで完璧に結びつけたね!',
        fp: '食品ロスから消費のSDGは見つけた?捨てられる食品は飢餓(2)や気候(13)にも影響するよ。',
        fm: '「食べ物を捨てる」はどの消費のSDG?8億人が飢えているのに10億トン捨てる…どんな問題が見える?',
        lc: '家庭で捨てる食品を1つ減らすだけで、飢餓と気候の両方に役立つ。冷蔵庫を確認し必要な分だけ買う習慣が世界を変えるよ。',
        bonus: '今日、冷蔵庫を開けて捨てそうな食品を1つ見つけて今日中に食べよう。家族に食品ロス削減を提案してみよう。',
      },
    },
  },
  {
    correct: [16, 3, 1, 4],
    tags: {
      ko: ['분쟁', '트라우마', '정신건강', '어린이보호'],
      en: ['conflict', 'trauma', 'mental health', 'child protection'],
      ja: ['紛争', 'トラウマ', 'メンタルヘルス', '子ども保護'],
    },
    url: 'https://www.unicefusa.org/stories/6-ways-unicef-supports-youth-mental-health',
    i18n: {
      ko: {
        source: '유니세프',
        title: '시리아·수단 등 분쟁 지역 어린이, 심각한 정신적 외상 겪어',
        body: '유니세프는 2025년 시리아, 수단, 가자지구 등 분쟁 지역에서 폭력을 목격하거나 직접 경험한 어린이 수천만 명이 심각한 정신적 외상(트라우마)을 겪고 있다고 보고했습니다. 유니세프 지원 팀은 안전한 공간에서 그림 그리기, 놀이 치료 등 심리·사회적 지원 프로그램을 운영하고 있습니다. 그러나 수요에 비해 지원 인력과 재원이 턱없이 부족한 실정입니다.',
        hint: '전쟁·폭력과 관련된 SDG, 정신건강 피해, 빈곤과 교육 기회 박탈도 함께 생각해보세요.',
        fc: '완벽해요! 평화와 정의(SDG 16)가 핵심이고, 정신건강(SDG 3), 빈곤(SDG 1), 교육 기회 박탈(SDG 4)까지 훌륭하게 연결했어요!',
        fp: '평화와 정의(SDG 16)는 꼭 포함해야 해요! 분쟁으로 인한 정신건강 피해(SDG 3)도 연결해보세요.',
        fm: '"분쟁 지역"과 "폭력"에서 평화 관련 SDG를 찾아보세요. 그리고 트라우마는 건강과 관련된 SDG와도 연결돼요.',
        lc: '우리가 안전하게 학교에 다니고 친구들과 놀 수 있는 것이 얼마나 소중한지 생각해보세요. 평화가 없으면 다른 모든 SDGs도 이루기 어려워요.',
        bonus: '오늘 하루 "평화"라는 단어를 생각하며, 내가 학교에서 누군가와 다투지 않고 사이좋게 지내는 작은 평화를 실천해보세요.',
      },
      en: {
        source: 'UNICEF',
        title: 'Children in Syria, Sudan and other conflict zones suffer severe trauma',
        body: 'UNICEF reported in 2025 that tens of millions of children in conflict zones — Syria, Sudan, Gaza and elsewhere — who have witnessed or experienced violence are living with severe trauma. UNICEF teams run psychosocial-support programs in safe spaces with drawing, play therapy and more, but staff and funding fall far short of the need.',
        hint: 'Find the SDG for war and peace. Also think about the impact on mental health, education and poverty.',
        fc: 'Perfect! Peace and Justice (16) is the core, plus Health (3) for mental health, Poverty (1), and Education (4) — wonderfully linked!',
        fp: 'Peace (16) is a must. Mental-health impacts from conflict also link to Health (3).',
        fm: '"Conflict zones" and "violence" point to the peace SDG. Trauma also links to the health SDG.',
        lc: 'Going to school safely and playing with friends is precious. Without peace, every other SDG is hard to reach.',
        bonus: 'Keep the word "peace" in mind today, and practice a small peace by getting along — not arguing — with someone at school.',
      },
      ja: {
        source: 'UNICEF',
        title: 'シリアやスーダンなど紛争地域の子ども、深刻なトラウマに',
        body: 'ユニセフは2025年、シリア、スーダン、ガザなどの紛争地域で暴力を目撃したり経験した数千万人の子どもが深刻なトラウマを抱えていると報告しました。ユニセフのチームは安全な場所での絵を描く活動や遊び療法などの心理社会的支援プログラムを行っていますが、需要に対して人員や資金がまったく足りていません。',
        hint: '戦争や暴力に関わるSDG。メンタルヘルスや、貧困・教育の喪失も一緒に考えよう。',
        fc: '完璧!平和と公正(16)が中心、メンタルヘルス(3)、貧困(1)、教育の喪失(4)までよく結びつけたね!',
        fp: '平和(16)は必須!紛争によるメンタルヘルスの被害(3)もつなげよう。',
        fm: '「紛争地域」「暴力」から平和のSDGを。トラウマは健康のSDGともつながるよ。',
        lc: '安全に学校に通い、友だちと遊べることがどれほど大切か考えよう。平和がなければ他のSDGsを達成するのも難しい。',
        bonus: '今日1日「平和」という言葉を意識して、学校で誰かと言い争わず仲良く過ごす小さな平和を実践してみよう。',
      },
    },
  },
  {
    correct: [7, 13, 9, 10],
    tags: {
      ko: ['재생에너지', '태양광', '풍력', 'IEA'],
      en: ['renewable energy', 'solar', 'wind', 'IEA'],
      ja: ['再生可能エネルギー', '太陽光', '風力', 'IEA'],
    },
    url: 'https://www.iea.org/reports/renewables-2025',
    i18n: {
      ko: {
        source: 'UNDP',
        title: '재생에너지, 처음으로 전 세계 전력 생산의 30% 돌파',
        body: '국제에너지기구(IEA)에 따르면 2025년 태양광·풍력을 중심으로 한 재생에너지가 처음으로 전 세계 전력 생산의 30%를 넘어섰습니다. 태양광 발전은 현재 지구상에서 가장 저렴한 전력원이 됐으며, 특히 개발도상국에서 빠르게 확산되고 있습니다. 그러나 아프리카와 남아시아 일부 지역은 여전히 전기 접근이 어려운 상황입니다.',
        hint: '재생에너지와 직접 관련된 SDG, 기후변화 완화 효과, 기술 혁신, 에너지 접근 불평등도 생각해보세요.',
        fc: '탁월해요! 청정에너지(SDG 7)가 핵심이고, 기후변화 완화(SDG 13), 기술 혁신(SDG 9), 에너지 접근 불평등(SDG 10)까지 완벽하게 연결했어요!',
        fp: '청정에너지(SDG 7)는 꼭 포함해야 해요! 재생에너지가 늘면 기후변화(SDG 13)에도 도움이 돼요. 아직 전기가 없는 지역의 불평등도 생각해보세요.',
        fm: '"재생에너지"와 "태양광"에서 에너지와 관련된 SDG를 찾아보세요. 화석연료를 줄이면 어떤 효과가 생기는지도 연결해봐요.',
        lc: '우리 학교나 집 옥상에 태양광 패널이 있다면 재생에너지를 직접 사용하는 거예요. 에너지 절약도 재생에너지 확산을 돕는 방법이에요.',
        bonus: '집에서 쓰는 전기가 어떻게 만들어지는지 부모님께 물어보고, 태양광 발전에 대해 함께 이야기해보세요.',
      },
      en: {
        source: 'UNDP',
        title: 'Renewables top 30% of global electricity generation for the first time',
        body: 'According to the IEA, in 2025 renewables — led by solar and wind — supplied more than 30% of the world\'s electricity for the first time. Solar is now the cheapest power source on Earth and is spreading fastest in developing countries. Yet parts of Africa and South Asia still lack basic access to electricity.',
        hint: 'Use the SDG on clean energy, plus climate, innovation, and the inequality of energy access.',
        fc: 'Outstanding! Clean Energy (7) at the core, plus Climate (13), Innovation (9) and Inequality (10) in access — perfectly linked!',
        fp: 'Clean Energy (7) is a must. More renewables help Climate (13). Don\'t forget regions still without electricity — that\'s inequality.',
        fm: '"Renewables" and "solar" point to the energy SDG. What happens when we cut fossil fuels?',
        lc: 'If your home or school has solar panels, you are directly using renewables. Saving energy also helps spread them.',
        bonus: 'Ask your parents where your home\'s electricity comes from, and talk together about solar power.',
      },
      ja: {
        source: 'UNDP',
        title: '再生可能エネルギー、初めて世界の発電量の30%を突破',
        body: '国際エネルギー機関(IEA)によると、2025年に太陽光や風力を中心とする再生可能エネルギーが、世界の発電量の30%を初めて超えました。太陽光発電は今や地球上で最も安い電源となり、特に発展途上国で急速に広がっています。一方で、アフリカや南アジアの一部では今も電気へのアクセスが難しい状況です。',
        hint: '再エネに直結するSDG、気候緩和、技術革新、エネルギー接続の不平等も考えよう。',
        fc: '素晴らしい!クリーンエネルギー(7)が中心、気候(13)、技術革新(9)、アクセス不平等(10)まで完璧!',
        fp: 'クリーンエネルギー(7)は必須!再エネが増えれば気候(13)にも良い。電気がない地域の不平等も考えよう。',
        fm: '「再エネ」「太陽光」からエネルギーのSDGを。化石燃料を減らすとどんな効果?',
        lc: '家や学校の屋根に太陽光パネルがあれば、再エネを直接使っているということ。省エネも再エネ普及を助けるよ。',
        bonus: '家で使う電気がどう作られるか保護者に尋ね、太陽光発電について一緒に話してみよう。',
      },
    },
  },
  {
    correct: [11, 10, 13, 3],
    tags: {
      ko: ['도시화', '슬럼', '대기오염', '주거'],
      en: ['urbanization', 'slums', 'air pollution', 'housing'],
      ja: ['都市化', 'スラム', '大気汚染', '住宅'],
    },
    url: 'https://www.un.org/sustainabledevelopment/cities/',
    i18n: {
      ko: {
        source: 'UN뉴스',
        title: '전 세계 도시 인구 절반 돌파 — 급격한 도시화로 불평등 심화',
        body: '유엔 인구기금(UNFPA) 2025년 보고서에 따르면 전 세계 인구의 56%가 도시에 살고 있으며, 2050년에는 70%에 달할 전망입니다. 특히 저소득 국가에서 도시화가 급격히 진행되면서 슬럼가 확산, 교통 혼잡, 대기오염, 주거 부족 문제가 심각해지고 있습니다. 반면 잘 계획된 도시는 에너지 효율과 삶의 질을 동시에 높일 수 있다는 점에서 지속가능한 도시 설계가 중요해졌습니다.',
        hint: '"도시"와 직접 관련된 SDG, 슬럼가의 불평등, 대기오염과 기후변화, 건강 영향도 생각해보세요.',
        fc: '훌륭해요! 지속가능한 도시(SDG 11)가 핵심이고, 도시 내 불평등(SDG 10), 도시 온실가스 배출(SDG 13), 대기오염으로 인한 건강(SDG 3)까지 완벽하게 연결했어요!',
        fp: '지속가능한 도시(SDG 11)는 꼭 포함해야 해요! 슬럼가가 늘어나는 것은 불평등(SDG 10)과도 연결돼요. 대기오염이 건강에 미치는 영향도 생각해보세요.',
        fm: '"도시"와 관련된 SDG를 찾아보세요. 슬럼가가 늘고 대기오염이 심해지면 어떤 SDGs 문제가 생기는지도 연결해봐요.',
        lc: '우리 동네가 살기 좋은 도시가 되려면 어떤 게 필요할까요? 쓰레기를 버리지 않고, 대중교통을 이용하는 것도 지속가능한 도시를 만드는 작은 실천이에요.',
        bonus: '오늘 우리 동네를 걸으면서 더 살기 좋은 동네가 되려면 무엇이 필요한지 한 가지를 생각해보고, 그 이유를 적어보세요.',
      },
      en: {
        source: 'UN News',
        title: 'More than half the world now lives in cities — rapid urbanization deepens inequality',
        body: 'A 2025 UNFPA report says 56% of the world\'s population already lives in cities, projected to reach 70% by 2050. Rapid urbanization in low-income countries is fueling slum expansion, traffic congestion, air pollution and housing shortages. Well-planned cities, however, can boost both energy efficiency and quality of life, making sustainable urban design crucial.',
        hint: 'Look for the SDG about cities, inequality from slums, climate from urban emissions, and the health impact of pollution.',
        fc: 'Excellent! Sustainable Cities (11) at the core, plus Inequality (10) within cities, Climate (13) from emissions, and Health (3) from air pollution — perfectly linked!',
        fp: 'Sustainable Cities (11) is a must. Growing slums link to Inequality (10). Also think about how air pollution affects health.',
        fm: '"Cities" points to the urban SDG. Slums and worsening air pollution connect to which other SDGs?',
        lc: 'What would make our neighborhood a great place to live? Not littering and taking public transport also build a sustainable city.',
        bonus: 'Walk around your neighborhood today, think of one thing that would make it better, and write down the reason.',
      },
      ja: {
        source: 'UNニュース',
        title: '世界の半数以上が都市暮らしへ — 急速な都市化が不平等を拡大',
        body: '国連人口基金(UNFPA)の2025年報告書によると、世界人口の56%がすでに都市に暮らしており、2050年には70%に達する見通しです。特に低所得国で都市化が急速に進み、スラム拡大、交通渋滞、大気汚染、住宅不足が深刻化しています。一方、よく計画された都市はエネルギー効率と生活の質を同時に高められるため、持続可能な都市設計が重要になっています。',
        hint: '「都市」に直結するSDG、スラムの不平等、大気汚染と気候、健康への影響も考えよう。',
        fc: '素晴らしい!持続可能な都市(11)が中心、都市の不平等(10)、温室効果ガス(13)、大気汚染による健康(3)まで完璧!',
        fp: '持続可能な都市(11)は必須!スラム拡大は不平等(10)とも関係。大気汚染が健康に与える影響も考えよう。',
        fm: '「都市」のSDGを探そう。スラムが増え大気汚染が悪化すると、どのSDGsに?',
        lc: '私たちの町が住みよい都市になるには何が必要?ごみを捨てず公共交通を使うことも、持続可能な都市づくりの小さな実践だよ。',
        bonus: '今日、自分の町を歩きながら、もっと住みよくするために必要なことを1つ考えて、その理由を書いてみよう。',
      },
    },
  },

  // ─── 추가 기사 10개 — SDG 5·6·8 중심으로 다양성 보강 ───

  // 1) SDG 8 주력 — 아동 노동
  {
    correct: [8, 1, 4, 16],
    tags: {
      ko: ['아동노동', 'ILO', '어린이', '노동착취'],
      en: ['child labour', 'ILO', 'children', 'exploitation'],
      ja: ['児童労働', 'ILO', '子ども', '搾取'],
    },
    url: 'https://www.ilo.org/global/topics/child-labour/lang--en/index.htm',
    i18n: {
      ko: {
        source: 'ILO',
        title: '세계 어린이 1억 6천만 명, 학교 대신 일터에서 일해',
        body: '국제노동기구(ILO)와 유니세프 공동 보고서에 따르면 전 세계 5~17세 어린이 약 1억 6천만 명이 아동 노동에 종사하고 있습니다. 이 중 약 7900만 명은 위험한 환경에서 일하며 건강과 안전을 위협받고 있습니다. 코로나19 팬데믹, 분쟁, 기후위기로 인한 빈곤 심화가 아동 노동 증가의 주요 원인입니다. 학교에 가야 할 나이에 일하는 어린이들은 교육 기회를 박탈당해 빈곤의 악순환에 빠지게 됩니다.',
        hint: '학교 대신 일하는 어린이들과 관련된 노동·경제 SDG, 교육 박탈, 빈곤의 악순환을 생각해보세요.',
        fc: '완벽해요! 양질의 일자리(SDG 8)가 핵심이고, 빈곤(SDG 1), 교육 기회 박탈(SDG 4), 어린이 보호와 평화(SDG 16)까지 훌륭하게 연결했어요!',
        fp: '양질의 일자리(SDG 8)는 찾았나요? 아동 노동을 하는 어린이들은 학교(SDG 4)에 갈 수 없고, 이는 빈곤(SDG 1)으로 이어져요.',
        fm: '"학교 대신 일터"에서 노동 관련 SDG를 찾아보세요. 어린이가 일하면 어떤 기회를 잃게 되는지도 SDG와 연결해봐요.',
        lc: '우리가 학교에서 배우는 동안 같은 나이의 어린이들이 공장이나 밭에서 일하고 있어요. 공정무역 인증 제품을 선택하는 것도 아동 노동을 줄이는 행동이에요.',
        bonus: '오늘 집에 있는 제품 하나의 원산지를 확인해보고, 어떤 나라의 어린이들이 만들었을지 생각해보세요.',
      },
      en: {
        source: 'ILO',
        title: '160 million children work instead of going to school',
        body: 'A joint ILO–UNICEF report finds about 160 million children aged 5–17 are engaged in child labour worldwide. Some 79 million work in hazardous conditions that threaten their health and safety. COVID-19, conflict and climate-driven poverty are driving the rise in child labour. Working at an age when they should be studying, these children are robbed of education and trapped in a cycle of poverty.',
        hint: 'Think about the SDG for decent work, plus the loss of education, poverty cycle and child protection.',
        fc: 'Perfect! Decent Work (8) at the core, plus Poverty (1), loss of Education (4), and child protection under Peace & Justice (16) — beautifully linked!',
        fp: 'Did you find Decent Work (8)? Children in child labour miss school (SDG 4), which deepens poverty (SDG 1).',
        fm: '"Working instead of school" points to the work/economy SDG. What opportunities do working children lose? Connect each to its SDG.',
        lc: 'While we study at school, children our age work in factories or fields. Choosing fair-trade products is an action to reduce child labour.',
        bonus: 'Check the country of origin of one product at home today, and think about who might have made it.',
      },
      ja: {
        source: 'ILO',
        title: '世界で1億6,000万人の子どもが学校ではなく職場で働く',
        body: 'ILOとユニセフの共同報告書によると、世界で5〜17歳の子どもの約1億6,000万人が児童労働に従事しています。うち約7,900万人が危険な環境で働き、健康と安全が脅かされています。コロナ禍、紛争、気候危機による貧困の深刻化が主な要因です。学ぶべき年齢に働く子どもたちは教育を奪われ、貧困の悪循環にはまっています。',
        hint: '学校ではなく働く子どもに関わる労働・経済のSDG、教育の喪失、貧困の悪循環を考えよう。',
        fc: '完璧!働きがい(8)が中心、貧困(1)、教育喪失(4)、子ども保護としての平和と公正(16)まで結びつけたね!',
        fp: '働きがい(8)は見つけた?児童労働の子どもは学校(4)に行けず、貧困(1)につながるよ。',
        fm: '「学校より職場」から働きのSDGを。働く子どもは何を失う?それぞれSDGと結びつけよう。',
        lc: '私たちが学校で学んでいる間、同じ年の子どもたちが工場や畑で働いている。フェアトレード商品を選ぶことも児童労働を減らす行動だよ。',
        bonus: '家にある製品を1つ選んで原産国を確認し、どこの国の子どもたちが作ったか考えてみよう。',
      },
    },
  },

  // 2) SDG 5 주력 — 여성 과학자 성별 격차
  {
    correct: [5, 4, 10, 17],
    tags: {
      ko: ['성평등', 'STEM', '여성과학자', 'UN여성기구'],
      en: ['gender equality', 'STEM', 'women scientists', 'UN Women'],
      ja: ['ジェンダー平等', 'STEM', '女性研究者', 'UN Women'],
    },
    url: 'https://www.unwomen.org/en/news/stories/2025/2/women-in-science',
    i18n: {
      ko: {
        source: 'UN Women',
        title: '과학·기술 분야 여성 연구자, 여전히 30% 미만',
        body: '유네스코와 UN여성기구의 2025년 보고서에 따르면 전 세계 과학·기술·공학·수학(STEM) 분야 연구자 중 여성 비율이 여전히 30%에 미치지 못합니다. 여학생들은 어릴 때부터 "과학은 남자 것"이라는 사회적 편견으로 인해 진로 선택에 영향을 받고, 여성 과학자들은 경력 단절, 임금 격차, 리더십 기회 부족 등의 문제에 직면합니다. 유엔은 2030년까지 STEM 분야 성별 격차를 절반으로 줄일 것을 목표로 하고 있습니다.',
        hint: '과학 분야의 성별 불평등과 관련된 SDG, 교육 기회, 나라 간 불평등, 국제 협력도 생각해보세요.',
        fc: '훌륭해요! 성평등(SDG 5)이 핵심이고, 교육과 진로 기회(SDG 4), 불평등 해소(SDG 10), 국제 협력(SDG 17)까지 완벽하게 연결했어요!',
        fp: '성평등(SDG 5)은 꼭 포함해야 해요! 여학생들이 과학 진로를 선택하지 못하는 것은 교육(SDG 4)과도 연결돼요.',
        fm: '"여성 연구자"와 "성별 격차"에서 성평등 관련 SDG를 찾아보세요. 교육 기회 불평등도 어떤 SDG와 연결될까요?',
        lc: '우리 반 여학생들도 미래에 과학자, 엔지니어, 의사가 될 수 있어요. "과학은 남자 것"이라는 편견을 없애는 것도 SDG 5 실천이에요.',
        bonus: '오늘 "내가 가장 좋아하는 과목"을 친구에게 이야기하고, 성별과 상관없이 모두가 좋아하는 것을 자유롭게 선택할 수 있다고 응원해주세요.',
      },
      en: {
        source: 'UN Women',
        title: 'Women researchers still under 30% in science and technology',
        body: 'A 2025 UNESCO and UN Women report finds women account for less than 30% of researchers in STEM fields globally. From an early age, social stereotypes about "science being for boys" influence girls\' career choices, while female scientists face career breaks, pay gaps and lack of leadership opportunities. The UN aims to halve the STEM gender gap by 2030.',
        hint: 'Look for the SDG about gender equality in science, education opportunities, inequality and global partnerships.',
        fc: 'Excellent! Gender Equality (5) at the core, plus Education (4) for career access, Inequality (10) and Partnerships (17) — well linked!',
        fp: 'Gender Equality (5) is a must! Girls not choosing science careers also links to Education (4).',
        fm: '"Women researchers" and "gender gap" point to the gender SDG. How does unequal education opportunity connect?',
        lc: 'Girls in our class can be future scientists, engineers and doctors. Challenging the "science is for boys" stereotype is itself SDG 5 in action.',
        bonus: 'Tell a friend your favourite subject today, and encourage everyone that they are free to choose what they love — regardless of gender.',
      },
      ja: {
        source: 'UN Women',
        title: '科学・技術分野の女性研究者、今も30%未満',
        body: 'ユネスコとUN Womenの2025年報告書によると、世界のSTEM分野の研究者に占める女性の割合は30%に満たないままです。女子は幼いころから「理科は男の子のもの」という社会的な偏見の影響を受け、女性研究者はキャリアの中断や賃金格差、リーダー機会の不足に直面しています。国連は2030年までにSTEM分野の性別格差を半分にすることを目標としています。',
        hint: '科学分野のジェンダー不平等のSDG、教育機会、不平等解消、国際協力も考えよう。',
        fc: '素晴らしい!ジェンダー平等(5)が中心、教育機会(4)、不平等解消(10)、協力(17)まで完璧!',
        fp: 'ジェンダー平等(5)は必須!女子が科学の進路を選べないことは教育(4)とも関係しているよ。',
        fm: '「女性研究者」「性別格差」からジェンダーのSDGを。教育機会の不平等はどのSDG?',
        lc: 'クラスの女子も将来、科学者・エンジニア・医師になれる。「理科は男の子のもの」という偏見をなくすのもSDG 5の実践だよ。',
        bonus: '今日、友だちに好きな科目を話して、性別に関わらずみんなが好きなものを自由に選べると応援しよう。',
      },
    },
  },

  // 3) SDG 6 주력 — 위생 시설 위기
  {
    correct: [6, 3, 1, 4],
    tags: {
      ko: ['위생', '화장실', '수인성질병', 'UNICEF'],
      en: ['sanitation', 'toilet', 'waterborne disease', 'UNICEF'],
      ja: ['衛生', 'トイレ', '水因性疾患', 'UNICEF'],
    },
    url: 'https://www.unicef.org/reports/state-worlds-sanitation',
    i18n: {
      ko: {
        source: '유니세프',
        title: '안전한 화장실 없는 사람 35억 명 — 위생 위기가 건강을 위협해',
        body: '유니세프와 세계보건기구(WHO)의 2025년 공동 보고서에 따르면 전 세계 약 35억 명의 사람들이 안전하게 관리된 위생 시설 없이 생활하고 있습니다. 특히 개방 배변이 남아 있는 지역에서는 콜레라, 장티푸스 등 수인성 전염병이 빈발합니다. 학교에 화장실이 없어 등교를 꺼리는 여학생들도 많아 교육 불평등으로도 이어집니다. 깨끗한 물과 위생은 건강한 삶의 가장 기본입니다.',
        hint: '"화장실"과 "위생"은 어떤 SDG와 관련될까요? 건강, 빈곤, 교육과의 연결도 생각해보세요.',
        fc: '완벽해요! 깨끗한 물과 위생(SDG 6)이 핵심이고, 수인성 질병으로 인한 건강(SDG 3), 빈곤(SDG 1), 여학생 등교 기피로 인한 교육(SDG 4)까지 훌륭하게 연결했어요!',
        fp: '깨끗한 물과 위생(SDG 6)은 꼭 포함해야 해요! 위생 시설 부족이 건강(SDG 3)에 어떤 영향을 미치는지도 생각해보세요.',
        fm: '"화장실"과 "위생"에서 물·위생 관련 SDG를 찾아보세요. 불결한 위생이 건강, 학교생활, 빈곤과 어떻게 연결되는지도 생각해봐요.',
        lc: '학교 화장실을 깨끗하게 쓰는 것도 위생 실천이에요. 전 세계 수십억 명이 이런 기본적인 것조차 없다는 걸 생각해보세요.',
        bonus: '오늘 화장실을 사용한 뒤 꼭 손을 씻고, "손 씻기가 질병 예방에 왜 중요한지" 한 문장으로 설명해보세요.',
      },
      en: {
        source: 'UNICEF',
        title: '3.5 billion people without safe sanitation — a global health crisis',
        body: 'A 2025 UNICEF–WHO joint report says about 3.5 billion people worldwide lack safely managed sanitation. In areas where open defecation still occurs, waterborne diseases like cholera and typhoid are common. Many girls also avoid school because of missing toilets, deepening education inequality. Clean water and sanitation are the most basic foundation for a healthy life.',
        hint: '"Toilet" and "sanitation" — which SDG covers them? Also connect to health, poverty and education.',
        fc: 'Perfect! Clean Water and Sanitation (6) at the core, plus Health (3) from disease, Poverty (1), and Education (4) from girls avoiding school — brilliantly linked!',
        fp: 'Clean Water and Sanitation (6) is a must. How does poor sanitation affect Health (3)?',
        fm: '"Toilet" and "hygiene" point to the water/sanitation SDG. Connect poor conditions to health, schooling and poverty.',
        lc: 'Keeping the school toilet clean is its own sanitation practice. Billions of people don\'t even have that basic thing.',
        bonus: 'Wash your hands after using the toilet today, and explain in one sentence why handwashing prevents disease.',
      },
      ja: {
        source: 'UNICEF',
        title: '安全なトイレを使えない人35億人 — 衛生危機が健康を脅かす',
        body: 'ユニセフとWHOの2025年共同報告書によると、世界で約35億人が安全に管理された衛生設備なしで暮らしています。野外排泄が残る地域ではコレラや腸チフスなどの水因性感染症が頻発します。学校にトイレがないため通学を嫌がる女子も多く、教育の不平等にもつながります。清潔な水と衛生は健康な生活の最も基本的な土台です。',
        hint: '「トイレ」「衛生」はどのSDGと関わる?健康・貧困・教育とのつながりも考えよう。',
        fc: '完璧!きれいな水と衛生(6)が中心、水因性疾患による健康(3)、貧困(1)、女子の通学忌避による教育(4)まで結びつけたね!',
        fp: 'きれいな水と衛生(6)は必須!衛生施設の不足が健康(3)にどう影響するか考えよう。',
        fm: '「トイレ」「衛生」から水・衛生のSDGを。不衛生が健康・通学・貧困とどうつながるか考えよう。',
        lc: '学校のトイレをきれいに使うことも衛生の実践。世界の数十億人にはその基本的なものすらないことを考えよう。',
        bonus: '今日、トイレの後は必ず手を洗い、「手洗いが病気予防に大切な理由」を1文で説明してみよう。',
      },
    },
  },

  // 4) SDG 8 주력 — 청소년 실업(NEET)
  {
    correct: [8, 10, 9, 4],
    tags: {
      ko: ['청소년실업', 'NEET', 'ILO', '디지털격차'],
      en: ['youth unemployment', 'NEET', 'ILO', 'digital skills'],
      ja: ['若者の失業', 'NEET', 'ILO', 'デジタルスキル'],
    },
    url: 'https://www.ilo.org/global/research/global-reports/weso/trends-youth/2025/lang--en/index.htm',
    i18n: {
      ko: {
        source: 'ILO',
        title: '전 세계 청소년 5명 중 1명, 교육도 취업도 훈련도 못 받아',
        body: '국제노동기구(ILO)의 2025년 세계 청소년 고용 동향 보고서에 따르면 전 세계 15~24세 청소년 약 2억 2000만 명이 교육·취업·직업훈련 중 어느 것도 받지 못하는 상태(NEET)에 있습니다. 저소득 국가의 여성 청소년일수록 이 비율이 높으며, 디지털 기술 격차가 청년 취업을 더욱 어렵게 만들고 있습니다. ILO는 직업 훈련, 디지털 역량 강화, 녹색 경제 일자리 확대를 해법으로 제시했습니다.',
        hint: '청소년 고용과 관련된 SDG, 교육 기회, 디지털 기술 불평등, 기술 혁신을 생각해보세요.',
        fc: '탁월해요! 양질의 일자리(SDG 8)가 핵심이고, 불평등(SDG 10), 디지털·기술 혁신(SDG 9), 직업 교육(SDG 4)까지 완벽하게 연결했어요!',
        fp: '양질의 일자리(SDG 8)는 필수예요! 디지털 기술을 배우지 못하는 청소년 문제(SDG 9)와 불평등(SDG 10)도 생각해보세요.',
        fm: '"청소년 고용"과 "취업"에서 일자리 관련 SDG를 찾아보세요. 디지털 기술 격차는 어떤 SDG와 연결될까요?',
        lc: '우리가 지금 배우는 디지털 기술, 외국어, 다양한 역량들이 미래의 좋은 일자리와 연결돼요. 배움의 기회를 충분히 활용하는 것도 SDG 실천이에요.',
        bonus: '오늘 미래에 어떤 일을 하고 싶은지 생각하고, 그 일을 위해 지금 배울 수 있는 것 하나를 적어보세요.',
      },
      en: {
        source: 'ILO',
        title: '1 in 5 young people not in education, employment or training',
        body: 'ILO\'s 2025 World Employment and Social Outlook: Trends for Youth finds about 220 million people aged 15–24 are not in education, employment or training (NEET). The rate is highest among young women in low-income countries. The digital skills gap makes youth employment even harder. ILO proposes vocational training, digital upskilling and green economy jobs as solutions.',
        hint: 'Find the SDG for youth employment, plus education, digital skills inequality, and innovation.',
        fc: 'Outstanding! Decent Work (8) at the core, plus Inequality (10), Innovation (9) for digital gaps, and Education (4) for training — perfectly linked!',
        fp: 'Decent Work (8) is a must. The digital skills gap for youth also links to Innovation (9) and Inequality (10).',
        fm: '"Youth employment" and "jobs" point to the work SDG. The digital skills divide — which SDG covers that?',
        lc: 'The digital skills, languages and capabilities you are learning now link to good future jobs. Making the most of learning opportunities is itself an SDG action.',
        bonus: 'Think about what job you would like in the future, then write down one thing you can start learning now for it.',
      },
      ja: {
        source: 'ILO',
        title: '世界の若者の5人に1人、教育も仕事も訓練も受けられず',
        body: 'ILOの2025年「世界雇用・社会見通し：若者の動向」によると、15〜24歳の若者のうち約2億2,000万人が、教育・就労・職業訓練のいずれも受けていない「NEET」状態にあります。低所得国の若い女性ほどその割合が高く、デジタルスキルの格差が若者の就職をさらに困難にしています。ILOは職業訓練、デジタルスキル強化、グリーンエコノミーの雇用拡大を解決策として提示しています。',
        hint: '若者の雇用に関わるSDG、教育機会、デジタル不平等、技術革新を考えよう。',
        fc: '素晴らしい!働きがい(8)が中心、不平等(10)、デジタル格差と技術革新(9)、教育と訓練(4)まで完璧!',
        fp: '働きがい(8)は必須!デジタルスキルを学べない問題は技術革新(9)と不平等(10)に関係するよ。',
        fm: '「若者の雇用」「就職」から仕事のSDGを。デジタルスキルの格差はどのSDG?',
        lc: '今学んでいるデジタルスキルや語学、さまざまな力が、将来の良い仕事につながる。学びの機会を活かすこともSDGの実践だよ。',
        bonus: '将来どんな仕事をしたいか考え、そのために今学べることを1つ書いてみよう。',
      },
    },
  },

  // 5) SDG 5·16 주력 — 여성 폭력
  {
    correct: [5, 16, 3, 10],
    tags: {
      ko: ['젠더폭력', 'UN여성기구', '여성인권', '불평등'],
      en: ['gender-based violence', 'UN Women', 'women\'s rights', 'inequality'],
      ja: ['ジェンダー暴力', 'UN Women', '女性の権利', '不平等'],
    },
    url: 'https://www.unwomen.org/en/what-we-do/ending-violence-against-women/facts-and-figures',
    i18n: {
      ko: {
        source: 'UN Women',
        title: '세계 여성 3명 중 1명, 평생 한 번 이상 폭력 피해 경험',
        body: 'UN여성기구와 WHO의 2025년 공동 보고서에 따르면 전 세계 여성 3명 중 1명(약 10억 명)이 평생 한 번 이상 신체적·성적 폭력을 경험합니다. 분쟁 지역, 재난 상황, 경제적 어려움 속에서 폭력 피해 위험이 더욱 높아집니다. 이는 피해 여성의 신체적·정신적 건강에 심각한 영향을 미치며, 사회 전체의 발전을 가로막는 중요한 인권 문제입니다. 유엔은 각국에 강력한 피해자 보호 법제와 예방 교육 강화를 촉구하고 있습니다.',
        hint: '성별과 관련된 SDG, 폭력과 평화, 건강 피해, 불평등 측면을 함께 생각해보세요.',
        fc: '완벽해요! 성평등(SDG 5)과 평화·정의(SDG 16)가 핵심이고, 피해자의 신체·정신 건강(SDG 3), 불평등(SDG 10)까지 훌륭하게 연결했어요!',
        fp: '성평등(SDG 5)은 꼭 포함해야 해요! 폭력 피해는 건강(SDG 3)에도 영향을 미쳐요. 평화와 정의(SDG 16)도 연결해보세요.',
        fm: '"여성 폭력"에서 성별 관련 SDG와 평화·정의 관련 SDG를 함께 찾아보세요.',
        lc: '학교에서 서로를 존중하고 언어 폭력이나 따돌림을 하지 않는 것도 평화와 성평등을 실천하는 작은 행동이에요.',
        bonus: '오늘 주변 친구에게 존중의 말 한마디를 건네보세요. 서로 존중하는 문화가 폭력 없는 세상을 만들어요.',
      },
      en: {
        source: 'UN Women',
        title: '1 in 3 women worldwide experiences violence at least once in her lifetime',
        body: 'A 2025 UN Women–WHO joint report says 1 in 3 women globally — about 1 billion — has experienced physical or sexual violence at least once. Risk is highest in conflict zones, disaster situations and economic hardship. Violence deeply affects survivors\' physical and mental health and is a critical human-rights issue that holds societies back. The UN urges stronger victim-protection laws and prevention education.',
        hint: 'Find the gender SDG, the peace and justice SDG, health impacts and the inequality angle.',
        fc: 'Perfect! Gender Equality (5) and Peace & Justice (16) at the core, plus Health (3) for survivors and Inequality (10) — wonderfully linked!',
        fp: 'Gender Equality (5) is a must. Violence also impacts Health (3). Connect Peace & Justice (16) too.',
        fm: '"Violence against women" points to both the gender SDG and the peace/justice SDG.',
        lc: 'Respecting each other at school and not bullying or using harsh words is a small practice of peace and gender equality.',
        bonus: 'Say one respectful word to a friend today. A culture of mutual respect builds a world without violence.',
      },
      ja: {
        source: 'UN Women',
        title: '世界の女性3人に1人、生涯に少なくとも1度は暴力被害に',
        body: 'UN WomenとWHOの2025年共同報告書によると、世界の女性3人に1人(約10億人)が生涯に少なくとも1度、身体的・性的暴力を経験します。紛争地域、災害時、経済的困難の中で被害リスクが高まります。これは被害を受けた女性の身体・精神の健康に深刻な影響を与えるとともに、社会全体の発展を妨げる重大な人権問題です。国連は各国に強力な被害者保護法制と予防教育の強化を求めています。',
        hint: 'ジェンダーのSDG、暴力と平和、健康への被害、不平等の側面を考えよう。',
        fc: '完璧!ジェンダー平等(5)と平和・公正(16)が中心、被害者の健康(3)、不平等(10)まで結びつけたね!',
        fp: 'ジェンダー平等(5)は必須!暴力被害は健康(3)にも影響。平和と公正(16)もつなげよう。',
        fm: '「女性への暴力」からジェンダーのSDGと平和・公正のSDGを一緒に探そう。',
        lc: '学校で互いを尊重し、言葉の暴力やいじめをしないことも、平和とジェンダー平等を実践する小さな行動だよ。',
        bonus: '今日、周りの友だちに尊重の言葉を1つかけてみよう。互いを尊重する文化が暴力のない世界を作るよ。',
      },
    },
  },

  // 6) SDG 15 주력 — 생물다양성 위기
  {
    correct: [15, 14, 13, 17],
    tags: {
      ko: ['생물다양성', '멸종위기', 'IUCN', '서식지파괴'],
      en: ['biodiversity', 'extinction', 'IUCN', 'habitat loss'],
      ja: ['生物多様性', '絶滅危惧', 'IUCN', '生息地破壊'],
    },
    url: 'https://www.unep.org/resources/kunming-montreal-global-biodiversity-framework',
    i18n: {
      ko: {
        source: 'UNEP',
        title: '지구 생물 100만 종, 인간 활동으로 멸종 위기에 처해',
        body: '유엔 생물다양성협약(CBD)과 국제자연보전연맹(IUCN)은 2025년 보고서에서 현재 지구상 약 100만 종의 동식물이 인간 활동으로 인해 멸종 위기에 처해 있다고 밝혔습니다. 서식지 파괴, 오염, 기후변화, 외래종 침입이 주요 원인입니다. 생물다양성 손실은 식량 안보, 의약품 개발, 기후 조절 등 인간 삶 전체에 영향을 미쳐, 쿤밍-몬트리올 생물다양성 협약 이행이 시급합니다.',
        hint: '"육상 생태계"와 직접 관련된 SDG, 해양 생태계, 기후변화와의 연관, 국제 협력도 생각해보세요.',
        fc: '탁월해요! 육상생태계(SDG 15)가 핵심이고, 해양생태계(SDG 14), 기후변화(SDG 13), 국제 협력(SDG 17)까지 완벽하게 연결했어요!',
        fp: '육상생태계(SDG 15)는 꼭 포함해야 해요! 동물들이 사는 바다도 위협받고 있어요. 기후변화(SDG 13)가 멸종에 어떤 영향을 미치는지도 생각해보세요.',
        fm: '"멸종 위기"와 "생물다양성"에서 생태계 관련 SDG를 찾아보세요. 육지와 바다 생태계가 모두 위협받고 있어요.',
        lc: '우리 주변에서 볼 수 있는 참새, 개구리, 잠자리도 모두 생물다양성의 일부예요. 자연을 아끼는 마음이 100만 종의 생물을 지키는 시작이에요.',
        bonus: '오늘 집 근처 공원이나 학교 화단에서 곤충이나 새를 한 종 찾아보고, 그 이름을 검색해보세요.',
      },
      en: {
        source: 'UNEP',
        title: 'One million plant and animal species at risk of extinction from human activity',
        body: 'The UN Convention on Biological Diversity (CBD) and IUCN warn in a 2025 report that about one million species of plants and animals face extinction from human activity. Key causes include habitat destruction, pollution, climate change and invasive species. Biodiversity loss threatens food security, medicine and climate regulation, making urgent implementation of the Kunming-Montreal Biodiversity Framework critical.',
        hint: 'Look for the land-ecosystem SDG, ocean ecosystems, climate change links, and global partnerships.',
        fc: 'Outstanding! Life on Land (15) at the core, Life Below Water (14), Climate Action (13) and Partnerships (17) — perfectly linked!',
        fp: 'Life on Land (15) is a must. Animals on both land and sea are under threat. How does Climate (13) drive extinction?',
        fm: '"Extinction" and "biodiversity" point to the ecosystem SDGs. Both land and ocean ecosystems are affected.',
        lc: 'Sparrows, frogs and dragonflies near your home are all part of biodiversity. Caring about nature is the first step to protecting one million species.',
        bonus: 'Find one insect or bird near your home or school today and look up its name.',
      },
      ja: {
        source: 'UNEP',
        title: '地球の動植物100万種、人間活動によって絶滅の危機に',
        body: '国連生物多様性条約(CBD)とIUCNは2025年報告書で、現在地球上の約100万種の動植物が人間活動により絶滅の危機にあると発表しました。生息地の破壊、汚染、気候変動、外来種の侵入が主な原因です。生物多様性の損失は食料安全保障、医薬品開発、気候調節など人間生活全体に影響し、昆明・モントリオール生物多様性枠組みの実施が急務とされています。',
        hint: '「陸の生態系」に直結するSDG、海洋生態系、気候変動との関連、国際協力も考えよう。',
        fc: '素晴らしい!陸の豊かさ(15)が中心、海の豊かさ(14)、気候(13)、協力(17)まで完璧!',
        fp: '陸の豊かさ(15)は必須!動物は海でも陸でも脅かされている。気候(13)が絶滅にどう影響するかも考えよう。',
        fm: '「絶滅危惧」「生物多様性」から生態系のSDGを。陸と海、両方の生態系が脅かされているよ。',
        lc: '身近なスズメ、カエル、トンボもみんな生物多様性の一部。自然を大切にする気持ちが100万種を守る第一歩だよ。',
        bonus: '今日、家の近くや学校で虫や鳥を1種見つけ、その名前を調べてみよう。',
      },
    },
  },

  // 7) SDG 8·12 주력 — 패스트패션과 노동 착취
  {
    correct: [8, 12, 10, 17],
    tags: {
      ko: ['패스트패션', '의류노동자', 'ILO', '공정무역'],
      en: ['fast fashion', 'garment workers', 'ILO', 'fair trade'],
      ja: ['ファストファッション', '衣料労働者', 'ILO', 'フェアトレード'],
    },
    url: 'https://www.ilo.org/global/industries-and-sectors/textiles-clothing-leather-footwear/lang--en/index.htm',
    i18n: {
      ko: {
        source: 'ILO',
        title: '패스트패션 이면에 숨겨진 불공정 — 의류 노동자 80% 최저임금도 못 받아',
        body: '국제노동기구(ILO)와 유엔환경계획(UNEP)의 2025년 보고서에 따르면 전 세계 의류 및 섬유 산업 노동자의 약 80%가 최저 생활임금을 받지 못하고 있습니다. 이들 대부분은 방글라데시, 캄보디아, 에티오피아 등 저소득 국가의 여성 노동자들로, 열악한 환경에서 하루 10~12시간 일합니다. 패스트패션의 빠른 트렌드 소비는 과도한 생산과 쓰레기를 낳아 환경 오염도 심화시킵니다.',
        hint: '의류 노동자들과 관련된 노동·경제 SDG, 책임있는 소비와 생산, 나라 간 불평등도 생각해보세요.',
        fc: '훌륭해요! 양질의 일자리(SDG 8)가 핵심이고, 책임있는 소비·생산(SDG 12), 불평등(SDG 10), 국제 협력(SDG 17)까지 완벽하게 연결했어요!',
        fp: '양질의 일자리(SDG 8)는 꼭 포함해야 해요! 옷을 많이 사고 버리는 것은 책임있는 소비(SDG 12)와도 연결돼요.',
        fm: '"의류 노동자"와 "불공정"에서 일자리 관련 SDG를 찾아보세요. 옷을 많이 사는 소비 문화는 어떤 SDG와 연결될까요?',
        lc: '우리가 옷을 오래 입고, 중고 옷을 사거나 나눠 입으면 의류 노동자들의 착취를 줄이고 환경도 지킬 수 있어요. 소비자의 선택이 세계를 바꿔요.',
        bonus: '오늘 옷장을 열어서 "이 옷은 왜 샀지?"를 한 벌씩 생각해보고, 앞으로 옷을 살 때 어떤 기준을 가질지 정해보세요.',
      },
      en: {
        source: 'ILO',
        title: 'Behind fast fashion: 80% of garment workers earn below a living wage',
        body: 'A 2025 ILO–UNEP report finds about 80% of workers in the global garment and textile industry earn below a living wage. Most are women in low-income countries like Bangladesh, Cambodia and Ethiopia, working 10–12-hour days in poor conditions. Fast fashion\'s rapid trend cycles drive overproduction and waste, deepening environmental pollution.',
        hint: 'Find the SDG for decent work for garment workers, responsible consumption, inequality between countries, and partnerships.',
        fc: 'Excellent! Decent Work (8) at the core, plus Responsible Consumption (12), Inequality (10) and Partnerships (17) — beautifully linked!',
        fp: 'Decent Work (8) is a must. Buying and discarding lots of clothes also connects to Responsible Consumption (12).',
        fm: '"Garment workers" and "unfair" point to the work SDG. What SDG covers the culture of buying lots of clothes?',
        lc: 'Wearing clothes longer, buying second-hand and sharing reduces garment-worker exploitation and protects the environment. Consumer choices can change the world.',
        bonus: 'Open your wardrobe today and ask "why did I buy this?" for each item, then decide your personal standard for future clothing purchases.',
      },
      ja: {
        source: 'ILO',
        title: 'ファストファッションの裏側 — 衣料労働者の80%が最低生活賃金未満',
        body: 'ILOと国連環境計画(UNEP)の2025年報告書によると、世界の衣料・繊維産業の労働者の約80%が最低生活賃金を受け取れていません。多くはバングラデシュ、カンボジア、エチオピアなどの低所得国の女性労働者で、劣悪な環境で1日10〜12時間働いています。ファストファッションの急速なトレンド消費は過剰生産とごみを生み、環境汚染を深刻化させます。',
        hint: '衣料労働者の仕事に関わるSDG、責任ある消費と生産、国家間の不平等も考えよう。',
        fc: '素晴らしい!働きがい(8)が中心、責任ある消費・生産(12)、不平等(10)、協力(17)まで完璧!',
        fp: '働きがい(8)は必須!服をたくさん買って捨てるのは責任ある消費(12)とも関係するよ。',
        fm: '「衣料労働者」「不公平」から仕事のSDGを。服をたくさん買う消費文化はどのSDG?',
        lc: '服を長く着たり、古着を買ったり分け合うことで、労働者の搾取を減らし環境も守れる。消費者の選択が世界を変えるよ。',
        bonus: '今日クローゼットを開けて「なぜこの服を買ったのか」を1枚ずつ考え、これから服を買うときの基準を決めよう。',
      },
    },
  },

  // 8) SDG 6·12·14 — 산업 폐수로 오염된 강
  {
    correct: [6, 12, 14, 3],
    tags: {
      ko: ['수질오염', '산업폐수', 'UNEP', '담수위기'],
      en: ['water pollution', 'industrial wastewater', 'UNEP', 'freshwater'],
      ja: ['水質汚染', '産業廃水', 'UNEP', '淡水危機'],
    },
    url: 'https://www.unep.org/resources/report/global-freshwater-demand-will-exceed-supply-40-2030-warns-un-report',
    i18n: {
      ko: {
        source: 'UNEP',
        title: '산업 폐수로 오염된 강, 전 세계 물 안보 위협',
        body: '유엔환경계획(UNEP)의 2025년 담수 현황 보고서에 따르면 전 세계 강과 호수의 약 3분의 1이 산업 폐수, 농업 화학물질, 생활하수로 심각하게 오염되어 있습니다. 오염된 물은 수억 명의 식수 안전을 위협하고, 어류와 수생 생태계를 파괴합니다. 특히 플라스틱 폐수가 강을 통해 바다로 유입되어 해양 오염까지 연결됩니다. 강을 되살리기 위한 산업 규제와 국제 협력이 시급합니다.',
        hint: '"물 오염"과 직접 관련된 SDG, 책임있는 생산, 해양 생태계, 건강에 미치는 영향을 생각해보세요.',
        fc: '완벽해요! 깨끗한 물(SDG 6)이 핵심이고, 오염을 일으키는 산업 생산(SDG 12), 강에서 바다로 이어지는 해양 오염(SDG 14), 건강(SDG 3)까지 훌륭하게 연결했어요!',
        fp: '깨끗한 물(SDG 6)은 꼭 포함해야 해요! 플라스틱 폐수가 강에서 바다로 이어지는 것은 해양 생태계(SDG 14)와도 연결돼요.',
        fm: '"오염된 강"에서 물 관련 SDG를 찾아보세요. 플라스틱 오염이 바다로 이어진다면, 어떤 SDG와 연결될까요?',
        lc: '싱크대에 기름을 붓지 않고, 화학 세제 사용을 줄이는 것도 강과 바다를 지키는 행동이에요. 우리 집 아래의 하수가 결국 강과 바다로 흘러가요.',
        bonus: '오늘 집에서 사용하는 세제 하나를 골라 환경 친화적 제품으로 바꾸자고 부모님께 제안해보세요.',
      },
      en: {
        source: 'UNEP',
        title: 'Industrial wastewater pollutes rivers, threatening global water security',
        body: 'UNEP\'s 2025 Global Freshwater Status Report says about one third of the world\'s rivers and lakes are severely polluted by industrial wastewater, agricultural chemicals and sewage. Contaminated water threatens safe drinking water for hundreds of millions and destroys fish and aquatic ecosystems. Plastic wastewater flowing from rivers to the sea deepens ocean pollution. Industrial regulation and international cooperation are urgently needed.',
        hint: 'Find the SDG for water pollution, responsible production, ocean ecosystems and health impacts.',
        fc: 'Perfect! Clean Water (6) at the core, industrial pollution linking to Responsible Consumption (12), river-to-ocean pollution for Life Below Water (14), and Health (3) — beautifully linked!',
        fp: 'Clean Water (6) is a must. Plastic flowing from rivers into the sea also links to Life Below Water (14).',
        fm: '"Polluted rivers" points to the water SDG. Plastic flowing into the ocean — which SDG covers that?',
        lc: 'Not pouring oil down the drain and reducing chemical cleaners protects rivers and the sea. Wastewater from our home flows to rivers and oceans.',
        bonus: 'Choose one household detergent today and suggest switching to an eco-friendly version to your family.',
      },
      ja: {
        source: 'UNEP',
        title: '産業廃水で汚染された川、世界の水安全保障を脅かす',
        body: '国連環境計画(UNEP)の2025年「世界淡水現状報告書」によると、世界の川や湖の約3分の1が産業廃水、農業化学物質、生活排水で深刻に汚染されています。汚染された水は数億人の飲料水の安全を脅かし、魚や水生生態系を破壊します。プラスチック廃水が川を通じて海に流れ込み、海洋汚染にもつながります。川を取り戻すための産業規制と国際協力が急務です。',
        hint: '「水の汚染」に直結するSDG、責任ある生産、海洋生態系、健康への影響を考えよう。',
        fc: '完璧!きれいな水(6)が中心、産業による汚染(12)、川から海への海洋汚染(14)、健康(3)まで結びつけたね!',
        fp: 'きれいな水(6)は必須!プラスチック廃水が川から海へ流れることは海の生態系(14)ともつながるよ。',
        fm: '「汚染された川」から水のSDGを。プラスチックが海に流れ込むと、どのSDG?',
        lc: 'シンクに油を流さず、化学洗剤を減らすことも川と海を守る行動。家の排水は結局川や海につながっているよ。',
        bonus: '今日、家で使っている洗剤を1つ選んで、環境に優しい製品に変えようと保護者に提案してみよう。',
      },
    },
  },

  // 9) SDG 10·4·8 주력 — 장애인 포용
  {
    correct: [10, 4, 8, 11],
    tags: {
      ko: ['장애인', '포용', 'WHO', '배리어프리'],
      en: ['disability', 'inclusion', 'WHO', 'barrier-free'],
      ja: ['障がい者', 'インクルージョン', 'WHO', 'バリアフリー'],
    },
    url: 'https://www.who.int/news-room/fact-sheets/detail/disability-and-health',
    i18n: {
      ko: {
        source: 'UNDP',
        title: '전 세계 장애인 13억 명, 교육·취업·이동에서 여전히 불평등한 기회',
        body: '세계보건기구(WHO)와 세계은행의 2025년 보고서에 따르면 전 세계 인구의 약 16%인 13억 명이 어떤 형태로든 장애를 가지고 있습니다. 그러나 이들 중 많은 수가 교육, 취업, 의료, 교통 등에서 여전히 불평등한 대우를 받습니다. 저소득 국가에서는 장애 어린이의 절반 이상이 학교에 다니지 못하며, 도시 내 장벽 없는 이동권 보장도 부족합니다. 포용적 사회 설계가 모두를 위한 지속가능한 발전의 핵심입니다.',
        hint: '장애인 차별과 관련된 불평등 SDG, 교육 기회, 일자리, 도시 접근성도 생각해보세요.',
        fc: '훌륭해요! 불평등 감소(SDG 10)가 핵심이고, 장애 어린이의 교육(SDG 4), 장애인의 취업(SDG 8), 이동권과 도시 접근성(SDG 11)까지 완벽하게 연결했어요!',
        fp: '불평등 감소(SDG 10)는 꼭 포함해야 해요! 장애 어린이들이 학교에 못 가는 것은 교육(SDG 4)과도 연결돼요.',
        fm: '"장애인"과 "불평등"에서 관련 SDG를 찾아보세요. 학교, 취업, 도시 이동이 각각 어떤 SDG와 연결될지 생각해봐요.',
        lc: '휠체어를 위한 경사로, 점자블록, 수어 자막이 있는 학교와 도시가 모두를 위한 공간이에요. 우리 학교에도 이런 배려가 있는지 살펴봐요.',
        bonus: '우리 학교 주변에서 장애인을 위한 편의시설(경사로, 점자블록 등)을 하나 찾아보고, 더 필요한 것이 무엇인지 생각해보세요.',
      },
      en: {
        source: 'UNDP',
        title: '1.3 billion people with disabilities still face unequal access to education, jobs and mobility',
        body: 'A 2025 WHO–World Bank report says about 1.3 billion people — 16% of the global population — live with some form of disability. Yet many still face unequal treatment in education, employment, healthcare and transport. In low-income countries, over half of children with disabilities do not attend school, and barrier-free city mobility remains insufficient. Inclusive design is key to sustainable development for all.',
        hint: 'Find the SDG for inequality, then link it to education, jobs and accessible cities.',
        fc: 'Excellent! Reduced Inequalities (10) at the core, plus Education (4) for children with disabilities, Decent Work (8) for employment, and Sustainable Cities (11) for access — perfectly linked!',
        fp: 'Reduced Inequalities (10) is a must. Children with disabilities missing school also links to Education (4).',
        fm: '"Disability" and "unequal" point to the inequality SDG. How do school, employment and city access each connect to an SDG?',
        lc: 'Ramps for wheelchairs, tactile paving and sign-language captions make schools and cities welcoming for everyone. Check if your school has these features.',
        bonus: 'Look for one disability-access feature near your school (ramp, tactile paving, etc.) and think about what else might be needed.',
      },
      ja: {
        source: 'UNDP',
        title: '世界の障がい者13億人、教育・就職・移動に依然不平等な機会',
        body: 'WHOと世界銀行の2025年報告書によると、世界人口の約16%にあたる13億人が何らかの障がいを抱えています。しかし、教育・就労・医療・交通において依然として不平等な扱いを受けている人が多くいます。低所得国では障がいのある子どもの半数以上が学校に通えず、都市でのバリアフリーも不十分です。包摂的な社会設計が、すべての人のための持続可能な発展の鍵です。',
        hint: '障がい者差別と不平等のSDG、教育・雇用・都市アクセスも考えよう。',
        fc: '素晴らしい!不平等の解消(10)が中心、障がい児の教育(4)、障がい者の就職(8)、移動権と都市アクセス(11)まで完璧!',
        fp: '不平等の解消(10)は必須!障がい児が学校に通えないことは教育(4)ともつながるよ。',
        fm: '「障がい者」「不平等」からSDGを。学校・就職・都市移動がそれぞれどのSDGとつながるか考えよう。',
        lc: 'スロープ、点字ブロック、手話の字幕がある学校や都市は、みんなのための場所。自分の学校にそんな配慮があるか探してみよう。',
        bonus: '学校の近くでバリアフリー設備(スロープや点字ブロックなど)を1つ見つけ、さらに何が必要か考えてみよう。',
      },
    },
  },

  // 10) SDG 8·10·1·17 주력 — 난민의 일할 권리
  {
    correct: [8, 10, 1, 17],
    tags: {
      ko: ['난민', 'UNHCR', '강제이주', '취업권'],
      en: ['refugees', 'UNHCR', 'displacement', 'right to work'],
      ja: ['難民', 'UNHCR', '強制移住', '就労権'],
    },
    url: 'https://www.unhcr.org/global-trends-report-2024',
    i18n: {
      ko: {
        source: 'UNHCR',
        title: '전 세계 난민 1억 2000만 명 돌파 — 일할 권리마저 빼앗겨',
        body: '유엔난민기구(UNHCR)의 2025년 보고서에 따르면 전 세계 강제 이주 인구가 사상 최초로 1억 2000만 명을 넘어섰습니다. 분쟁, 박해, 기후변화가 주요 원인입니다. 많은 난민들이 체류 국가에서 공식 취업이 허용되지 않아 불법 노동이나 착취에 노출되고 있으며, 이는 빈곤 심화로 이어집니다. UNHCR은 난민의 법적 취업권 보장과 직업 훈련 지원을 각국에 촉구하고 있습니다.',
        hint: '강제 이주·난민과 관련된 일자리 SDG, 빈곤, 불평등, 국제 협력을 생각해보세요.',
        fc: '훌륭해요! 양질의 일자리(SDG 8)가 핵심이고, 빈곤(SDG 1), 불평등(SDG 10), 국제 협력(SDG 17)까지 완벽하게 연결했어요!',
        fp: '양질의 일자리(SDG 8)는 찾았나요? 일을 할 수 없는 난민들은 빈곤(SDG 1)에 빠지고 불평등(SDG 10)이 심화돼요.',
        fm: '"난민"과 "취업"에서 일자리 관련 SDG를 찾아보세요. 난민이 일을 못 하면 어떤 문제가 생기는지 연결해봐요.',
        lc: '우리 이웃에 외국에서 온 친구들이 있다면 먼저 인사하고 도움을 주는 것도 글로벌 연대예요. 다름을 존중하는 마음이 포용적인 사회를 만들어요.',
        bonus: '오늘 우리 반이나 학교에서 다른 나라에서 온 친구가 있다면, 그 나라의 문화나 음식에 대해 궁금한 것을 물어봐요.',
      },
      en: {
        source: 'UNHCR',
        title: '120 million forcibly displaced people — many denied the right to work',
        body: 'UNHCR\'s 2025 report says the global number of forcibly displaced people has surpassed 120 million for the first time, driven by conflict, persecution and climate change. Many refugees are not legally allowed to work in host countries, leaving them exposed to illegal labour and exploitation, deepening their poverty. UNHCR urges countries to guarantee refugees\' legal right to work and provide vocational training.',
        hint: 'Think about the SDG for decent work for refugees, plus poverty, inequality and international cooperation.',
        fc: 'Excellent! Decent Work (8) at the core, plus Poverty (1), Inequality (10) and Partnerships (17) — well linked!',
        fp: 'Decent Work (8) is key. Refugees who cannot work fall into poverty (1) and face deepening inequality (10).',
        fm: '"Refugees" and "right to work" point to the jobs SDG. What happens if refugees cannot work?',
        lc: 'If there are friends from other countries near you, greeting them first and offering help is also global solidarity. Respecting difference builds an inclusive society.',
        bonus: 'If there is a friend from another country in your class or school today, ask about a food or custom from their country.',
      },
      ja: {
        source: 'UNHCR',
        title: '世界の難民が1億2,000万人を突破 — 働く権利さえ奪われる',
        body: 'UNHCRの2025年報告書によると、紛争、迫害、気候変動を原因とする世界の強制移住者数が初めて1億2,000万人を超えました。多くの難民が滞在国で正式な就労を認められておらず、非合法労働や搾取にさらされ、貧困が深刻化しています。UNHCRは難民の法的就労権の保障と職業訓練の支援を各国に求めています。',
        hint: '強制移住・難民と仕事のSDG、貧困・不平等・国際協力を考えよう。',
        fc: '素晴らしい!働きがい(8)が中心、貧困(1)、不平等(10)、国際協力(17)まで完璧!',
        fp: '働きがい(8)は見つけた?仕事ができない難民は貧困(1)に陥り、不平等(10)が深まるよ。',
        fm: '「難民」「就労」から仕事のSDGを。難民が働けないとどんな問題が?',
        lc: '近くに外国から来た友だちがいたら、先にあいさつして助け合うのもグローバルな連帯。違いを尊重する心が包摂的な社会を作るよ。',
        bonus: '今日、クラスや学校に別の国から来た友だちがいたら、その国の料理や習慣について気になることを聞いてみよう。',
      },
    },
  },
];
